### ISSUE TITLE
imgadm does not work behind proxies

### ISSUE THREAD

**Issue by khushil** [joyent/smartos-live#120]
When using the downloadable image on local machines, at times we are forced behind corporate firewalls and have to use the export vars http_proxy / https_proxy to access the outside world.

When setting http_proxy and https_proxy imgadm seems to ignore these settings and try a direct connect which will error in net.js with ETIMEDOUT.

imgadm should support http_proxy and https_proxy.

**Comment by trentm** [comment]
This is fixed now in #master. I'm sorry that it took this long.

**Comment by bapt** [comment]
Usually applications accepts both HTTP_PROXY and http_proxy. imgadm only supports lower case. Would be nice to also accept upper case version
