### ISSUE TITLE
Any users on smartmachine can execute mdata-get.

### ISSUE THREAD

**Issue by sawanoboly** [joyent/smartos-live#163]
0500 is better than 0555 as for the premission of mdata-get? 

Example,  Using smartmachine standard at joyentcloud. Any user can get credential passwords.
It is not good for administrator.

**Comment by bahamas10** [comment]
```
$ mdata-get foo
ERROR: could not initialise protocol: Could not find metadata socket.
$ sudo mdata-get foo
bar
```

is this still the case?
