### ISSUE TITLE
'recovery' boot option should have (root/root) in grub menu name

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#169]
Things should self-document.

As people keep asking about it, 'recovery' boot option should have (root/root) in the grub menu on both usb and iso. And possibly (root/$SINGLE_USER_ROOT_PASSWORD) to the 'install' boot options, if space allows.

It's possible many people skip testing smartos entirely when faced with this problem.

**Comment by rmustacc** [comment]
Resolved in ea46441.
