### ISSUE TITLE
dladm set-linkprop maxbw return dladm: warning: invalid link property

### ISSUE THREAD

**Issue by alcir** [joyent/smartos-live#182]
From the global zone
`dladm set-linkprop -z d491e12d-8a02-49eb-9ac9-d0ba577b4c90 -p maxbw=0 net0`

Return
`dladm: warning: invalid link property 'maxbw'`

However the property is updated

**Comment by bassu** [comment]
Tripped me up. But limits are applied (default unit is megabits/s).

**Comment by rzezeski** [comment]
I wrote [OS-6007](https://smartos.org/bugview/OS-6007) to track the original issue reported (setting maxbw complains but still works).

@ferebee I will also look into your issue and see if I can duplicate it.

**Comment by rzezeski** [comment]
If you pass the `-t` option to set-linkprop then dladm will not complain (because these zone VNICs are temporary links).

**Comment by rzezeski** [comment]
> I also find that if I change maxbw several times on a zone, the interface will stop passing packets, as if maxbw were set to 0. I can only get it back by stopping and restarting the zone with vmadm.

@ferebee I tracked this down and wrote it up as [OS-6151](https://smartos.org/bugview/OS-6151). A fix should be incoming in the next week.

**Comment by rzezeski** [comment]
The original bug reported in this ticket was fixed as part of [OS-6007](OS-6007). It landed in commit joyent/illumos-joyent@fc23aa9bfe9a967a31614f6829d88243205132e0 (platform version [20170330T015208Z](http://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/smartos.html#20170330T015208Z)).

The second issue can be tracked in #357/[OS-6151](https://smartos.org/bugview/OS-6151).
