### ISSUE TITLE
/var/svc/provisioning timed out.

### ISSUE THREAD

**Issue by NukeRusich** [joyent/smartos-live#193]
"So, I'm unable to find a support area, so based on illumos itself having support on the issue tracker, I'll just come here for SmartOS.

SmartOS Live Image v0.147+ build: 20130222T000747Z (remotely hosted dedicated server)"

"timed out waiting for /var/svc/provisioning to move  for a8113f9e-f9e4-46de-b350-352ffa360073"

Any way to resolve this issue?

JSON manifest for the new Zone:

```
{                              
 "brand": "joyent",            
 "image_uuid": "cf7e2f40-9276-11e2-af9a-0bad2233fb0b",
 "alias": "ekunia-v1.2",             
 "hostname": "ekunia-v1.2",          
 "max_physical_memory": 32667,   
 "zfs_root_compression": "lzjb",
 "dns_domain": "ekunia.com",
 "quota": 0,                  
 "nics": [                     
  {                            
    "nic_tag": "admin",        
    "ip": "192.95.30.28",       
    "netmask": "255.255.255.0",
    "mac": "82:3c:a3:ac:44:33",
    "gateway": "192.95.30.255"    
  }                            
 ]                             
}
```

**Comment by pomfei** [comment]
@Ekunia  I added the "primary": "true" but still time out. 
and the template i used is from https://docs.project-fifo.net/en/stable/general/installation.html

**Comment by lloydde** [comment]
@pomfei this is a long closed issue. If you are able to isolate and replicate the issue using a recent image from https://smartos.org/ please open a new detailed issue. If you need community assistance please join the mailing list at https://smartos.org/smartos-mailing-list/ .
