### ISSUE TITLE
imgadm does not work when you have 1000's of ZFS datasets

### ISSUE THREAD

**Issue by jacques** [joyent/smartos-live#200]
[root@jfk-gz-01 (JFK) ~]# imgadm list
imgadm: error (InternalError): could not load images: Error: maxBuffer exceeded.
[root@jfk-gz-01 (JFK) ~]# imgadm import 60ed3a3e-92c7-11e2-ba4a-9b6d5feaa0c4 
Importing image 60ed3a3e-92c7-11e2-ba4a-9b6d5feaa0c4 (base 1.9.1) from "https://images.joyent.com"
100% [=============================]  time 38.0s  eta 0.0s
imgadm: error (InternalError): error running "/usr/sbin/zfs list -t filesystem,volume -o origin,name -pH": 
[root@jfk-gz-01 (JFK) ~]# zfs list | wc -l
    4996

**Comment by beuford** [comment]
+1

**Comment by trentm** [comment]
Fixed in https://smartos.org/bugview/OS-3873

commit 3de3d422bedfa8f16dfd24a4e2c95820dc2af8fe

**Comment by jacques** [comment]
Thanks @trentm
