### ISSUE TITLE
Nightly "No such file or directory" from sdc-lastcomm

### ISSUE THREAD

**Issue by smokris** [joyent/smartos-live#202]
Every night for the last week I've been getting emails like the following:

    From: Super-User <root@my-smartos-server>
    Subject: Cron <root@my-smartos-server> /smartdc/bin/sdc-lastcomm -R 30
    Date: 2013.04.17 20:00:01 EDT
    To: root@my-smartos-server

    find: stat() error ./20130417183242.not_terminated.my-smartos-server: No such file or directory

There _is_ a `find` invocation in `/smartdc/bin/sdc-lastcomm` but it doesn't seem to be doing anything unusual:

    find . -mtime +$DAYS -exec rm -f "{}" \;

The only situation I think would trigger that error would be for the `not_terminated` file to be deleted after `find` has started enumerating files but before it's actually deleted the file... Though given that there are only about 30 files in `/var/audit` I wouldn't expect that there would be much window of opportunity for that to happen; certainly not enough to happen consistently every night for the last week.

Any ideas?

**Comment by lloydde** [comment]
~~~
[root@headnode (coal-1) ~]# uname -a
SunOS headnode 5.11 joyent_20150331T183020Z i86pc i386 i86pc
From root@headnode.example.com Sun Apr 12 03:00:00 2015
Date: Sun, 12 Apr 2015 03:00:00 GMT
From: Super-User <root@headnode.example.com>
Message-Id: <201504120300.t3C300HT038301@headnode.example.com>
To: root@headnode.example.com
Subject: Cron <root@headnode> /smartdc/bin/sdc-lastcomm -R 30
Content-Length: 88
 
find: stat() error ./20150412000055.not_terminated.headnode: No such file or directory
~~~

**Comment by lloydde** [comment]
Continue to hit this every few days on my single server testing env.

**Comment by unclejack** [comment]
I'm seeing this as well.

**Comment by sjorge** [comment]
Been seeing this on and off, happening a lot the last few weeks.

**Comment by dietsche** [comment]
same here:

>From root@smarts Wed Sep 30 00:00:00 2015
>Date: Wed, 30 Sep 2015 00:00:00 GMT
>From: Super-User <root@smarts >
>Message-Id: <201509300000.t8U000gI060918@smarts >
>To: root@smarts
>Subject: Cron <root@smarts> /smartdc/bin/sdc-lastcomm -R 30
>Content-Length: 85
>
>find: stat() error ./20150929000000.not_terminated.vader: No such file or directory

**Comment by bahamas10** [comment]
fixed!

https://smartos.org/bugview/OS-4813
https://github.com/joyent/smartos-live/commit/f5bd628

**Comment by lloydde** [comment]
@bahamas10 You are gold!
