### ISSUE TITLE
Possible miscount of mac addresses on Intel nic

### ISSUE THREAD

**Issue by asonge** [joyent/smartos-live#206]
Symptoms:
Every time I reboot, a different subset of zones can access the network, never more than 4 vnics. Running snoop, even in non-promiscuous mode, allows me to access all the zones. Currently running `snoop -P -o /dev/null -q`, which uses next to no CPU as a workaround.

Output of `# prtconf -d | grep -i net`:
`pci8086,2002 (pciex8086,1503) [Intel Corporation 82579V Gigabit Network Connection], instance #0`

**Comment by bahamas10** [comment]
@asonge can we close this issue if it is no longer reproducible?

**Comment by asonge** [comment]
Yes

**Comment by bahamas10** [comment]
great, thanks!
