### ISSUE TITLE
base64 13.1.0 : mysql-server and percona-server go into maintenance after installation

### ISSUE THREAD

**Issue by trentster** [joyent/smartos-live#210]
pkgin in mysql-server
svcadm enable mysql:default

[ May  7 23:29:40 svc.startd could not set context for method:  ]
[ May  7 23:29:40 chdir: No such file or directory ("/var/mysql") ]
[ May  7 23:29:40 Method "start" exited with status 96. ]

pkgin in percona-server
svcadm enable percona-server:default

[ May  8 00:09:09 svc.startd could not set context for method:  ]
[ May  8 00:09:09 chdir: No such file or directory ("/var/mysql") ]
[ May  8 00:09:09 Method "start" exited with status 96. ]

**Comment by churnd** [comment]
What was the fix?  I'm seeing the same thing with the mariadb 10.0.2 package right now.
