### ISSUE TITLE
proper support for ipv6 in vmadm

### ISSUE THREAD

**Issue by wiedi** [joyent/smartos-live#231]
vmadm should support configuration of ipv6 adresses.
There are documented workarounds [1][2] and also some code in the right direction [3][4].

Sadly the workarounds rely on allowing ip_spoofing.

- [1] <http://wiki.smartos.org/display/DOC/Setting+up+IPv6+in+a+Zone>
- [2] <http://fnordig.de/2012/09/16/getting-ipvworking-with-smartos-and-kvm/>
- [3] <https://github.com/joshie/smartos-live/tree/ip6>
- [4] <https://github.com/nshalman/smartos-live/commit/a4376266f22387cb0ccac142f586275ae7829078>

**Comment by bahamat** [comment]
See also #431.

**Comment by melloc** [comment]
Closed by 837b134, which adds support for IPv6 and multiple IPs to vmadm and SmartOS zones.

For those using IP spoofing protection, there are two issues worth mentioning here:

- [OS-4667](https://smartos.org/bugview/OS-4667), which currently prevents using SLAAC addresses from within a zone. DHCPv6 addresses work fine, though.
- [OS-4683](https://smartos.org/bugview/OS-4683), which currently prevents using dynamic addresses from DHCPv4 or IPv6 autoconfiguration on interfaces that also have static addresses. (This means that you can't use static IPv6 with DHCPv4, for example.)

**Comment by wiedi** [comment]
fantastic, thanks so much! :)
