### ISSUE TITLE
KVM instance network broken when using IPv4 DHCP and IPv6 SLAAC

### ISSUE THREAD

**Issue by bahamat** [joyent/smartos-live#234]
My network is primarily IPv6. IPv4 is only used for legacy connectivity but all "real" management and operation runs over IPv6.

KVM instances constantly complain:

```
IPv6: eth0: IPv6 duplicate address 2001:db8::c046:a8ff:feba:a41a detected!
```

This happens with every KVM instance I create.

My `nic` configuration is:

```
"nics": [
  {
    "nic_tag": "admin",
    "ip": "dhcp",
    "primary": "true",
    "allow_ip_spoofing": "true"
  }
],
```
- When I ping the IPv6 address I get no response.
- There is no IPv4 address configured on the interface.

I have tried with both cents-6 and debian images, about 20 times and all have had the same behavior:

```
# imgadm list
UUID                                  NAME          VERSION  OS       PUBLISHED           
94384a12-bbeb-11e2-aec2-2bfa9742484b  debian-6.0.7  2.4.2    linux    2013-05-13T19:19:01Z
30e9e4c8-bbf2-11e2-ac3b-3b598ee13393  centos-6      2.4.2    linux    2013-05-13T19:42:33Z
```

**Comment by trinhpham** [comment]
Although it's not caused by SmartOS but it would be helpful if you can post your solution here.

PS: I'm facing this problem, and Google takes me here with no solution T_T

**Comment by bahamat** [comment]
The duplicate address was a bug in SmartOS that was fixed long ago. If you’re still running something from 2013 you need to upgrade.

The dhcp issue was a problem on the dhcp server. In my case an SRX hardware appliance, so almost certainly not relevant to you.

**Comment by trinhpham** [comment]
Thanks for your kind reply, @bahamat
I figure out that the problem comes by one of my DHCP relay server. Don't know the reason, but restart it get the issue fixed.
