### ISSUE TITLE
Can't create zone when using DHCP

### ISSUE THREAD

**Issue by bahamat** [joyent/smartos-live#235]
My network is primarily IPv6. IPv4 is only used for legacy connectivity but all "real" management and operation runs over IPv6.

Creating a zone with `dhcp` and `nic_tag` of `admin` fails with the following error:

```
timed out waiting for /var/svc/provisioning to move  for <uuid>
```

This happens with either joyent or joyent-minimal brands. I haven't tried sngl yet.

My `nic` configuration:

```
"nics": [
  {
    "nic_tag": "admin",
    "ip": "dhcp",
    "primary": "true",
    "allow_ip_spoofing": "true"
  }
]
```

If I use a static IP provisioning succeeds.

**Comment by madsmith** [comment]
Sorry to drag up old news, but what was the solution for this issue?  I'm having a similar problem where my zone is basically running but just sits there claiming it's waiting for provisioning.

**Comment by bahamat** [comment]
In my case, it was that the dhcp server was not responding to requests from new hosts.

Run `snoop` from the global zone to see if `DHCPOFFER`s are being sent from your dhcp server. If the dhcp server is functioning properly you should see them.
