### ISSUE TITLE
Setting up nameservers with DHCP

### ISSUE THREAD

**Issue by schmurfy** [joyent/smartos-live#281]
I can't find how to tell SmartOs that the nameservers it uses should be taken from the dhcp answer, I tried:

```
dns_resolvers=dhcp
```

```
dns_resolvers=
```

```
# dns_resolvers=
```

with all of these the result is the same, nothing in /etc/resolv.conf :(
I tried to look at the startup scripts but i can't figure what I am supposed to do to have the behavior I want...

**Comment by RSully** [comment]
Sorry for bumping an old thread, but to clarify, to use DHCP to set DNS servers, should the line `dns_resolvers` be commented/omitted, or should it be set to `dhcp`?
