### ISSUE TITLE
zone static routes: vmadm update does not work

### ISSUE THREAD

**Issue by bsdhsr** [joyent/smartos-live#303]
Here's what was tried:

vmadm update 5a69d7f4-d5b8-44c4-a5b4-162cad9021b4 '{"set_routes": {"172.16.50.0/24": "172.16.100.203"}}'

 vmadm update 5a69d7f4-d5b8-44c4-a5b4-162cad9021b4 '{ "routes": { "172.16.50.0/24", "172.16.100.203" } }'

And also (improvising a bit):
vmadm update 5a69d7f4-d5b8-44c4-a5b4-162cad9021b4 '{ "routes": { "vpn": { "172.16.50.0/24", "172.16.100.203" } } }'

I am not sure about the syntax, got it from the vmadm manpage.

However, with either of them, a subsequent "vmadm get" yields no results.

**Comment by pannon** [comment]
This seem to be still an issue - are there any workaround to overcome this?

**Comment by pannon** [comment]
Just a quick update: actually @Licenser 's suggestion works with the echo statement. I was able to update VM NIC's this way - even default routes.
