### ISSUE TITLE
Terribly slow virtio write speeds in Windows guest and recommendation of latest Virtio drivers

### ISSUE THREAD

**Issue by bassu** [joyent/smartos-live#320]
SmartOS with default zfs params (either dual mirror or raidz1 with or without SLOG):

1. Virtio drivers signed by Joyent give 2 MB/s sequential writes.
2. Virtio drivers from Red Hat give 23 MB/s sequential write.

Writes outside the guest or in Linux guest average on 150 MB/s.

I have compared this to Joyent Cloud, where I see they are using old
Joyent signed Virtio drivers, but the sequential writes in Windows
instances are over there are 160 MB/s.

This is easily reproducible with latest SmartOS and independent on what hardware is used.

```zfs_zone_delay_enable``` was disabled during all tests.

#### zpool iostat -v ####
````
                              capacity     operations    bandwidth
pool                       alloc   free   read  write   read  write
-------------------------  -----  -----  -----  -----  -----  -----
zones                      2.84T  4.41T      0  1.55K      0  29.2M
  raidz1                   2.84T  4.41T      0  1.55K      0  29.2M
    c0t50014EE2089F83E2d0      -      -      0  1.55K      0  9.86M
    c0t50014EE208A21B1Ad0      -      -      0  1.55K      0  9.86M
    c0t50014EE25DF5259Fd0      -      -      0  1.55K      0  9.86M
    c0t50014EE2B34A1BF1d0      -      -      0  1.55K      0  9.86M
-------------------------  -----  -----  -----  -----  -----  -----
````

#### screenshot ####
![slow-virtio](https://cloud.githubusercontent.com/assets/977697/2765786/40d90ab8-ca28-11e3-8d9c-99584b4a1682.png)

**Comment by matthiasg** [comment]
What are the drivers currently accepted as being the fastest ones for KVM windows. I tried the stable and latest from fedora and they don't really impress. (This is with all SSD pool with and without ZIL)

**Comment by sjorge** [comment]
If possible, try with bhyve instead of KVM. The performance is much better. (As in night and day)

On bhyve I use the latest drivers, on KVM I got the best performance with rather old ones: https://pkg.blackdot.be/extras/virtio-win-0.1-49.iso

~ sjorge

**Comment by matthiasg** [comment]
I was under the impression that bhyve is still not quite production ready.
The few windows machines we have all have important business workloads
running on them so bad place to experiment.

is there a way to convert kvm drives to bhyve to run a few tests ?

**Comment by matthiasg** [comment]
@sjorge well it seem bhyve still has some issues, at least in the documentation department. I simply get a black screen when connecting with vnc (no password set), bhyve does not yet support providing a dhcp server so no assigned ips and booting from cd image is also not documented as far as I can see.

Does anybody have any experience booting a windows kvm virtio boot disk in bhyve ?

**Comment by sjorge** [comment]
I’ve only used it for new VMs, but if you are trying to boot an existing one you probably need to set bootrom to bios, which means no VNC (works fine with UEFI bootrom).

To boot from a CD I usually add it afterwords as a 2nd disk after copying the iso to the zoneroot. model=ahci, media=cdrom works fine for those.

Aside from some the things mentioned (no VNC with bios bootrom, no cdrom=... on the command line to boot once with a cdrom) things just work. I have a mix of windows 10, FreeBSD and OmniOS running (all UEFI though)

~ sjorge
