### ISSUE TITLE
vmadm update quota fails if zone is out of space

### ISSUE THREAD

**Issue by stevenwilliamson** [joyent/smartos-live#329]
Running vmadm update on a zone that is already out of space fails.

vmadm update 95c544f6-074f-11e4-af8c-6b02c101223e quota=30
ENOSPC, open '/zones/95c544f6-074f-11e4-af8c-6b02c101223e/config/metadata.json.new'

Granted you should not ideally reach this point. But been able to allocate more resources on the fly one would expect if this did occur a remedial action would be to just increase the quota.

Potentially /zones/"uuid"/config should be it's own dataset with a small reservation ?

**Comment by schmurfy** [comment]
I always got that one xD
I agree that while you can get away by settings the zfs quota directly before using vmadm update it would be nice for vmadm update to work anyway in that case.

If someone needs this, do not forget the unit when calling `zfs set`, the quota for vmadm is in GB but you need to append "G" to the number for `zfs set quota`

**Comment by joshwilsdon** [comment]
fixed with bfd46958d86958bc3b1a4ce9fccd0f9649aec908

**Comment by schmurfy** [comment]
nice ! thanks :)
