### ISSUE TITLE
Use Joyent fixed GRUB for RICHMOND-16 issue instead of old one.

### ISSUE THREAD

**Issue by Licenser** [joyent/smartos-live#336]
It seems that the GRUB used by the USBKey generation is still a old one instead of the one fixed for a problem with bad memory ranges in certain conditions (Supermicro X9 boards with some special bios settings related to "Network stack"0.

Here is the change that fixed the issue: https://github.com/joyent/illumos-joyent/commit/b6074390f3ef84676ad2ba8f216cd685b0b92e04

Info on this was provided by wesolows - thanks mate! :D

**Comment by jlevon** [comment]
This is no longer relevant at all, closing.
