### ISSUE TITLE
lx-brand init script should not set /etc/resolveconf/resolv.conf but use /etc/resolvconf/resolv.conf.d/head

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#380]
Sometimes the lx branded ubuntu zone ends up with an empty /etc/resolv.conf... 
It happens every now and then so I suspect resolvconf somehow wipes it.

As per http://manpages.ubuntu.com/manpages/lucid/man8/resolvconf.8.html adding the entries into /etc/resolvconf/resolv.conf.d/head is probably better.

**Comment by leecallen** [comment]
I observed this problem on 2015-10/8 using:
SmartOS: joyent_20150528T153328Z
Image: a21a64a0-0809-11e5-a64f-ff80e8e8086f (lx-ubuntu-14.04           20150601)
Portion of JSON file:
  "resolvers": ["192.168.0.1"],
  "nics": [
    {
      "nic_tag": "admin",
      "ip": "192.168.0.118",
      "netmask": "255.255.255.0",
      "gateway": "192.168.0.1",
      "primary": true
    }
  ],

**Comment by pfmooney** [comment]
Issues with resolv.conf are commonly associated with old PIs and images.
It's worth updating both to see if that solves the issue.

**Comment by leecallen** [comment]
yes, updating the PI and using a newer ubuntu LX image solved the problem.
