### ISSUE TITLE
auditset manifest is missing

### ISSUE THREAD

**Issue by bbhoss** [joyent/smartos-live#393]
For auditing to work in Illumos, it looks like the auditset service needs to be enabled. We already have the svc method, but it seems the manifest is missing. enabling auditd and auditset ([manifest](https://github.com/joyent/illumos-joyent/blob/master/usr/src/cmd/auditset/auditset.xml)) makes auditing work as needed. I'm also going to propose that auditset be enabled by default, as all it does is reads config from SMF and sets the kernel flags accordingly. This way a user doesn't have to worry about forgetting to enable this service, it just works across reboots transparently. This was originally just supposed to be an implementation detail anyways according to [this](http://webcache.googleusercontent.com/search?q=cache:YUvSyJi95NwJ:https://www.mail-archive.com/opensolaris-arc%40opensolaris.org/msg01021.html+&cd=1&hl=en&ct=clnk&gl=us)

There was some confusion initially about whether audit_control was needed. It is not. I am planning on writing up a blog post about auditing on SmartOS soon to clarify this.

**Comment by jjelinek** [comment]
It would be great to see a blog documenting your experience with auditing. I had filed a SmartOS bug (OS-3767) to track the non-persistence of the audit flags. Once I confirm this fix, I'll close 393 as a dup of OS-3767. Thanks for digging in to these issues and working through them!

**Comment by jjelinek** [comment]
I filed OS-3771 for the obsolete information about audit_control in the man pages

**Comment by jjelinek** [comment]
This was fixed under OS-3767.
