### ISSUE TITLE
lx zone networking is incomplete

### ISSUE THREAD

**Issue by snltd** [joyent/smartos-live#432]
the `ip` command doesn't work in an lx-ubuntu-14.04 zone. 

```
root@375a9693-c6a4-4376-a637-cf853e34074d:~# ifconfig eth0 | sed 1q
eth0      Link encap:Ethernet  HWaddr 72:3d:10:7d:1b:09
root@375a9693-c6a4-4376-a637-cf853e34074d:~# ip link show eth0
Device "eth0" does not exist.
```

running `strace` tells me

```
/proc/net", R_OK)               = 0
access("/proc/net/unix", R_OK)          = 0
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
ioctl(4, SIOCGIFINDEX, {ifr_name="eth0", ???}) = -1 EINVAL (Invalid argument)
close(4)                                = 0
write(2, "Device \"eth0\" does not exist.\n", 30Device "eth0" does not exist.
) = 30
exit_group(1)
```

on a working VM, the `ioctl()` call looks like this:

```
ioctl(4, SIOCGIFINDEX, {ifr_name="eth0", ifr_index=2}) = 0
close(4)                                = 0
```

I also notice `/proc/sys/net` does not exist in an lx zone.

System information:

```
$ grep SmartOS /etc/release
                       SmartOS 20150320T034246Z x86_64
$ imgadm list | grep lx
818cc79e-ceb3-11e4-99ee-7bc8c674e754  lx-ubuntu-14.04         20150320    other    2015-03-20T03:45:09Z
```

**Comment by lloydde** [comment]
@snltd what led you to discover this? Exploring or did you discover it trying to run a real workload?

Interesting, this fails on 
~~~bash
# ip link show eth0
Device "eth0" does not exist.
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
# uname -a
Linux 4460d070-2c59-c333-e20e-daea127abe34 3.13.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# /native/sbin/uname -a
SunOS 4460d070-2c59-c333-e20e-daea127abe34 5.11 joyent_20150327T214450Z i86pc i386 i86pc
~~~

But succeeds on CentOS:
~~~bash
# ip link show eth0
2: eth0: <BROADCAST,MULTICAST,UP> mtu 1500 qlen 1
    link/generic 
# cat /etc/centos-release
CentOS release 6.6 (Final)
# uname -a
Linux 9d3998df-8de9-c2a5-a1b7-863de06ef94d 2.6.32 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# /native/sbin/uname -a
SunOS 9d3998df-8de9-c2a5-a1b7-863de06ef94d 5.11 joyent_20150327T214450Z i86pc i386 i86pc
~~~

**Comment by snltd** [comment]
It came from a real workload: I was trying to make the same puppet run that we use on our 14.04 kvm instances. That actually seemed to raise a more serious issue, where the ruby interpreter crashes, but these errors came first. I dug through the facter source and chased it down to the `ip` shellout.

**Comment by bcantrill** [comment]
It looks like it's assuming that it can drop a SIOCGIFINDEX on
/proc/net/unix to list interfaces -- which seems weird even for Linux. (The
"ip" on CentOS -- which appears to be much older -- does the more
conventional thing of ioctl'ing a socket to list interfaces.) In any case,
this needs to work; we'll get it fixed. Meanwhile, could we please also get
a ticket open on the ruby core? We don't need much more detail than the
core itself to get started.

**Comment by snltd** [comment]
I've opened another issue for the puppet/ruby crash. I'm afraid I haven't really dug into that one at all.

**Comment by bcantrill** [comment]
Scratch what I said, BTW -- I missed a rather important line in the strace output. ;)

**Comment by lloydde** [comment]
Created https://smartos.org/bugview/OS-4138

**Comment by pfmooney** [comment]
This should be fixed with the resolution of OS-4238.
