### ISSUE TITLE
sdc uploads not found on SmartOS

### ISSUE THREAD

**Issue by RSully** [joyent/smartos-live#435]
Email from cron on SmartOS:

> find: cannot open /var/log/sdc/upload/: No such file or directory

**Comment by ryancnelson** [comment]
this is in 
https://github.com/joyent/smartos-live/blob/f311853cd8b896183302122acf18bb39ca6cdd33/overlay/generic/etc/cron.d/crontabs/root

... that crontab entry assumes the existence of directory /var/log/sdc/upload
we should probably put in a test 

similarly, but already-fixed, in 
https://github.com/joyent/sdc-platform/blob/8ba19f62f7c3e74f96303d0570ca403d7622f5ff/overlay/etc/cron.d/crontabs/root 
... there's a test, then cron if the test passes, like:
" [ -x /opt/smartdc/bin/sdc-phonehome ] && /opt/smartdc/bin/sdc-phonehome "

**Comment by RSully** [comment]
Crontab file also exists in smartos-live besides sdc-platform.

**Comment by jclulow** [comment]
Fixed via #438
