### ISSUE TITLE
"imgadm create" images can't be imported with imgadm on SmartOS

### ISSUE THREAD

**Issue by xen0l** [joyent/smartos-live#442]
HI,

I am not sure where to report this and if it is considered a bug, but I will try. Commit 5da0f52723652140dc3446e47d12fecb30a5b1c6 introduced support of min_platform requirement in imgadm. This causes problems on SmartOS when I try to import OS image created with "imgadm create". The problem is in the created image manifest:

```
[root@smartos /opt]# imgadm create -c gzip e50c6f89-2eff-4a51-a90a-9d091d95100e name=foo version=2.0.0
Inheriting from origin image c02a2044-c1bd-11e4-bd8c-dfc1db8b0182 (base64 14.4.0)
Manifest:
    {
      "v": 2,
      "uuid": "e4268f1c-b536-4402-8d6f-4e498bd83ec6",
      "name": "foo",
      "version": "2.0.0",
      "type": "zone-dataset",
      "os": "smartos",
      "requirements": {
        "min_platform": {
          "undefined": "20150226T162528Z"
        },
        "networks": [
          {
            "description": "public",
            "name": "net0"
          }
        ]
      }
    }
Snapshotting to "zones/e50c6f89-2eff-4a51-a90a-9d091d95100e@final"
Sending image file to "foo-2.0.0.zfs"
Saving manifest to "foo-2.0.0.imgmanifest"
```

This manifest will fail when I try to import it via imgadm:
```
[root@smartos /opt]# imgadm install -m foo-2.0.0.imgmanifest -f foo-2.0.0.zfs.gz 
Installing image e4268f1c-b536-4402-8d6f-4e498bd83ec6 (foo@2.0.0)
imgadm install: error (MinPlatform): current platform version, 6.5/20150226T162528Z, does not satisfy requirements.min_platform={"undefined":"20150226T162528Z"}
```

The problem is located [here](https://github.com/joyent/smartos-live/blob/master/src/img/lib/imgadm.js#L3173). SDC Version is not set on SmartOS, as /.smartdc_version doesn't exists and it will output undefined. 

The workaround is to remove problematic lines from image manifest. Doing so can result in user experience breakage with SmartOS, when the user will try to import new image on too old SmartOS version and will be suprised that the zone does not work due to binary compatibility issues. I think that  this should be solved directly in imgadm and "imgadm create" generated manifests as imgadm is the official tool to work with images on SmartOS. What should be used instead of SDC Version value for non-SDC installations?

**Comment by rmustacc** [comment]
What version of SmartOS are you using here? We should have backed out that commit from the release two weeks ago when we respun it (though there was a brief window where a broken version was out) and with the forthcoming release, it should actually have the .smartdc_version file due to the recent platform unification.

**Comment by xen0l** [comment]
The one released on 2015-04-02. If it's going to be shipped with the next version, then this issue can be closed.

**Comment by rmustacc** [comment]
Which one, what's uname -v? We had to rerelease because of this exact problem.

**Comment by xen0l** [comment]
20150402T212529Z. I guess I will have to update or wait for the next release.

Adam
