### ISSUE TITLE
[information] vmadm destroy will destroy ALL datasets added to a zone

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#452]
Just information for other people as it's not really a bug per se.

If you add more datasets using zonecfg to a zone, say from a pool for bulk data. `vmadm destroy uuid` will also destroy that dataset! Instead of just the ones that are inside zones/uuid/*.

Makes sense from a vmadm point of view, may have horrifying results if you don't pay attention!
Probably a good idea to set `"indestructible_delegated": true`.

**Comment by jblachly** [comment]
I was bitten by this when just getting started.

**Comment by sjorge** [comment]
I few people have been, usually for the same reason that it was unexpected for datasets not under zones/uuid to be destroyed.

**Comment by pfmooney** [comment]
@sjorge Aye.  Restricting deletions to children of the zones/<uuid> volume might be an acceptable compromise.

**Comment by aqw** [comment]
I'm unsure when it change, but I can confirm that this is no longer the case in `20200520T174734Z`. I was able to add a dataset on `tank` to a zone (on `zones`). I used `vmadm delete` to destroy the zone, and the delegated dataset remained on `tank`.

**Comment by sjorge** [comment]
Yeah this can be closed, I fixed this with help of @danmcd earlier this year.
