### ISSUE TITLE
lx create doesn't allow filesystem options

### ISSUE THREAD

**Issue by jjlawren** [joyent/smartos-live#453]
I'm trying to create an lx zone with several read-only lofs mounts, but vmadm does not accept the json:

> "filesystems": [
> {
>  "source": "/dataset1",
>  "target": "/dataset1",
>  "options": "ro",
>  "type": "lofs"
> }
> 
> # vmadm create -f lx-zone.json
> invalid value(s) for: filesystems.*.options

**Comment by sjorge** [comment]
Options is an array so use: "options": [ "ro" ], works fine for me.
