### ISSUE TITLE
Page fault in module "kvm" due to a NULL pointer dereference

### ISSUE THREAD

**Issue by GernotS** [joyent/smartos-live#455]
in todays build I Encounter a page fault as soon as a KVM starts.
BAD TRAP: type=e (#pf Page fault) rp=ffffff002f6f73a0 addr=0 occurred in module "kvm" due to a NULL pointer dereference.
Dump available.

**Comment by pfmooney** [comment]
I have the core in Manta and am taking a look at it.

**Comment by pfmooney** [comment]
This is likely the result of crossing the signalfd flag day boundary without doing a clean build.
See Jerry's recent email on smartos-discuss.

Let me know if the problem persists after a full clean build.

Thanks

**Comment by GernotS** [comment]
I did a full build with gmake update, removed all stamps before building but the problem persists.

**Comment by rmustacc** [comment]
gmake update and gmake clean don't do a clobber inside of illumos which means that you'll still be getting that incremental build most likely. You'll want to do a dmake clobber inside of projects/illumos.

**Comment by pfmooney** [comment]
@rmustacc It's the stuff in illumos-kvm that needs to be rebuilt.

**Comment by GernotS** [comment]
rebuilding smartos-live/projects/local/kvm sorted the issue.
thanks!
