### ISSUE TITLE
 Unable to boot Windows 10 Enterprise Preview

### ISSUE THREAD

**Issue by naisanza** [joyent/smartos-live#456]
I'm running into an issue with booting a Windows 10 Enterprise Preview disc. After starting the VM it errors with `genunix: [ID 722105 kern.warning] WARNING: ip_Interface_cleanup: cannot open /devices/pseudo/udp6@0:udp6: error 13`.

The `vmadm` command I'm using is `vmadm start <UUID> order=cd,once=d cdrom=/virtio-win-0.1-100.iso,ide cdrom=/Windows10_TechnicalPreview_x64_EN-US_9926.iso,ide`.

The json spec that I'm using to create the VM with, `win-10-enterprise-preview.json`:
```
{
    "alias": "win10",
    "brand": "kvm",
    "vcpus": 1,
    "autoboot": false,
    "ram": 4096,
    "resolvers": ["8.8.8.8", "8.8.4.4"],
    "disks": [
	{
	    "boot": true,
	    "model": "virtio",
	    "size": 40960
	}
    ],
    "nics": [
	{
	    "nic_tag": "admin",
	    "model": "virtio",
	    "ip": "dhcp",
	    "primary": 1
	}
    ]
}
```

Screenshot of VMware Player v7.1.0 build-2496824: 
![unable-to-boot-windows-10](https://cloud.githubusercontent.com/assets/1614425/8195055/ad39006c-144d-11e5-80b8-16236c396789.png)

SmartOS version:
```
[root@00-0c-29-91-9f-1d ~]# cat /zones/currbooted .
joyent_20150417T032339Z
```

**Comment by rmustacc** [comment]
You'll want to check the QEMU log file to see what actually went wrong. Usually can be found in /zones/<uuid>/root/tmp, IIRC.

**Comment by davefinster** [comment]
@naisanza There will be vm.log[.n] and vm.startvm.log that might provide some insight. What is the RAM capacity of your host?

As an aside, on default settings Windows 10 will panic as you enter the installer on the latest build. This is completely unsupported by SmartOS officially (going by vmadm) but if you run 'vmadm update <zone-uuid> cpu_type=core2duo' and start your zone, you should be able to get into the installer, once you work out this issue.

**Comment by naisanza** [comment]
@rmustacc the logs were where you mentioned they would be

@davefinster the host has 16 GB; of which 4 GB is assigned to SmartOS, and 4 GB is provisioned to the Windows 10 VM; and the Windows 10 VM is the only one that I'm starting

Directory listing of /zones/UUID/root/tmp:
```
[root@00-0c-29-91-9f-1d /zones/81b5f425-a11a-40b5-bff7-29a444542ed2/root/tmp]# ls -hltr
total 11
-rw-r--r--   1 root     root           0 Jun 16 21:27 vm.log.1
-rw-r--r--   1 root     root           0 Jun 16 21:27 vm.log.0
-rw-r--r--   1 root     root          30 Jun 16 21:29 vm.metadata
-rw-r--r--   1 root     root        1.4K Jun 16 21:29 vm.startvm.log
srwxr-xr-x   1 root     root           0 Jun 16 21:29 vm.qmp
srwxr-xr-x   1 root     root           0 Jun 16 21:29 vm.console
srwxr-xr-x   1 root     root           0 Jun 16 21:29 vm.ttyb
-rw-------   1 root     root           5 Jun 16 21:29 vm.pid
-rw-r--r--   1 root     root           0 Jun 16 21:30 vm.log
```

Contents of vm.startvm.log:
```
+ [[ -x /startvm.zone ]]
+ exec /smartdc/bin/qemu-exec /smartdc/bin/qemu-system-x86_64 -m 4096 -name 81b5f425-a11a-40b5-bff7-29a444542ed2 -uuid 81b5f425-a11a-40b5-bff7-29a444542ed2 -cpu qemu64 -drive file=/dev/zvol/rdsk/zones/81b5f425-a11a-40b5-bff7-29a444542ed2-disk0,if=virtio,index=0,media=disk,boot=on -drive file=/virtio-win-0.1-100.iso,if=ide,index=1,media=cdrom -drive file=/Windows10_TechnicalPreview_x64_EN-US_9926.iso,if=ide,index=2,media=cdrom -boot order=cd,once=d -device virtio-net-pci,mac=72:75:d2:e5:4c:f5,tx=timer,x-txtimer=200000,x-txburst=128,vlan=0 -net vnic,name=net0,vlan=0,ifname=net0 -smbios 'type=1,manufacturer=Joyent,product=SmartDC HVM,version=7.20150417T032339Z,serial=81b5f425-a11a-40b5-bff7-29a444542ed2,uuid=81b5f425-a11a-40b5-bff7-29a444542ed2,sku=001,family=Virtual Machine' -pidfile /tmp/vm.pid -vga std -chardev socket,id=qmp,path=/tmp/vm.qmp,server,nowait -qmp chardev:qmp -chardev socket,id=serial0,path=/tmp/vm.console,server,nowait -serial chardev:serial0 -chardev socket,id=serial1,path=/tmp/vm.ttyb,server,nowait -serial chardev:serial1 -vnc unix:/tmp/vm.vnc -parallel none -usb -usbdevice tablet -k en-us
/tmp/vm.log.8: No such file or directory
/tmp/vm.log.7: No such file or directory
/tmp/vm.log.6: No such file or directory
/tmp/vm.log.5: No such file or directory
/tmp/vm.log.4: No such file or directory
/tmp/vm.log.3: No such file or directory
/tmp/vm.log.2: No such file or directory
/tmp/vm.log.1: No such file or directory
vm.startvm.log (END) 
```

**Comment by naisanza** [comment]
Edit: I changed the title since I found it is also affecting me from booting a `ubuntu-15.04-desktop-amd64.iso` disc 

It may be something with VMware, so I'm going to recreate another SmartOS VM.

The json spec that I used to create the VM with:
```
  "alias": "elk",
  "brand": "kvm",
  "vcpus": 2,
  "autoboot": false,
  "ram": 2048,
  "resolvers": ["8.8.8.8", "8.8.4.4"],
  "disks": [
    {
      "boot": true,
      "model": "virtio",
      "size": 40960
    }
  ],
  "nics": [
    {
      "nic_tag": "admin",
      "model": "virtio",
      "ip": "dhcp",
      "primary": 1
    }
  ]
}
```

vm.startvm.log:
```
+ [[ -x /startvm.zone ]]
+ exec /smartdc/bin/qemu-exec /smartdc/bin/qemu-system-x86_64 -m 2048 -name 036d7f93-e7e3-428b-9f13-fc35b845ec80 -uuid 036d7f93-e7e3-428b-9f13-fc35b845ec80 -cpu qemu64 -smp 2 -drive file=/dev/zvol/rdsk/zones/036d7f93-e7e3-428b-9f13-fc35b845ec80-disk0,if=virtio,index=0,media=disk,boot=on -drive file=/ubuntu-15.04-desktop-amd64.iso,if=ide,index=1,media=cdrom -boot order=cd,once=d -device virtio-net-pci,mac=52:d0:f1:31:87:2c,tx=timer,x-txtimer=200000,x-txburst=128,vlan=0 -net vnic,name=net0,vlan=0,ifname=net0 -smbios 'type=1,manufacturer=Joyent,product=SmartDC HVM,version=7.20150417T032339Z,serial=036d7f93-e7e3-428b-9f13-fc35b845ec80,uuid=036d7f93-e7e3-428b-9f13-fc35b845ec80,sku=001,family=Virtual Machine' -pidfile /tmp/vm.pid -vga std -chardev socket,id=qmp,path=/tmp/vm.qmp,server,nowait -qmp chardev:qmp -chardev socket,id=serial0,path=/tmp/vm.console,server,nowait -serial chardev:serial0 -chardev socket,id=serial1,path=/tmp/vm.ttyb,server,nowait -serial chardev:serial1 -vnc unix:/tmp/vm.vnc -parallel none -usb -usbdevice tablet -k en-us
/tmp/vm.log.8: No such file or directory
/tmp/vm.log.7: No such file or directory
/tmp/vm.log.6: No such file or directory
/tmp/vm.log.5: No such file or directory
/tmp/vm.log.4: No such file or directory
/tmp/vm.log.3: No such file or directory
/tmp/vm.log.2: No such file or directory
/tmp/vm.log.1: No such file or directory
/tmp/vm.log.0: No such file or directory
/tmp/vm.log: No such file or directory
vm.startvm.log (END) 
```

**Comment by rmustacc** [comment]
Did you explicitly enable nested virtualization in VMware's advanced CPU options?

**Comment by naisanza** [comment]
@rmustacc I followed this documentation, https://communities.vmware.com/docs/DOC-8970, and enabled `Virtualize Intel VT-x/EPT or AMD-V/RVI`.

**Comment by davefinster** [comment]
I remember seeing similar behaviour when I was trying SmartOS on a box that had VT-x support but not EPT. It would let me create and start KVMs but obviously they wouldn't work and would crash afterwards. That being said, this was back in 2013.

The error message that your seeing is pretty common when shutting down a KVM - it's just the tidy up operations. It might also be worth looking in /zones/<zone uuid>/cores to see if there is a core dump from qemu and if so, upload it somewhere.

**Comment by naisanza** [comment]
@rmustacc Now, what do I need to install video (and possibly sound) drivers?



To fix the boot issue:

I had to lower the memory used by the VMs in order to boot. Apparently, there is a memory cap that I wasn't aware of, so setting a VM with 4096 MB of RAM really meant it would suck up to a gig more than SmartOS had (by default); SmartOS only had 4096 MB of RAM to give.

![smartos-running](https://cloud.githubusercontent.com/assets/1614425/8246095/77274690-1606-11e5-8de5-b941efc70627.png)

Now, Windows 10 is booted

![windows-booted](https://cloud.githubusercontent.com/assets/1614425/8246382/d988d9a2-160b-11e5-999d-e981f95f191a.png)

I also installed Ubuntu 15.04

![linux-booted](https://cloud.githubusercontent.com/assets/1614425/8246383/dc5b0a6a-160b-11e5-8015-83c0d8e97b85.png)


Also, lastly, I followed VMware's documentation (http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=287) and given a+rw access to the NAT device (vmnet8) for dhcp assignment to work correctly.

![rw-for-all](https://cloud.githubusercontent.com/assets/1614425/8246262/942d1da2-1609-11e5-8bf7-042ecdb47451.png)

**Comment by rmustacc** [comment]
Not really sure what drivers you're referring to from a video and sound point of view. We don't emulate any audio devices generally and the video device options, all relatively naive are available in vmadm(1M). In general, I would be surprised if there were any third party drivers required for that.

With respect to the question of SmartOS vs. SDC, there's no real difference. At the end of the day, it'll just pass things to vmadm, which itself isn't going to try and stop you from overprovisioning memory. However, KVM always locks down the memory that it uses. To answer that though, we'd need to see the json files you passed to vmadm create and in the case of SDC, the packages you used.

**Comment by davefinster** [comment]
On the topic of memory lock down, also keep in mind that launching a KVM will lock down <ram allocation> + 1GB for safety sake. As a matter of interest, did you have to make any tweaks to the Windows 10 VM to get it to boot @naisanza (or did you use the ones I mentioned)? 

You shouldn't need to install any video drivers as Windows should pick up the standard VGA card supplied by QEMU/KVM.

**Comment by naisanza** [comment]
@rmustacc I see. Is there a way to change the resolution (in Windows and Linux)? They seem to be locked to the resolution they're in.

![windows-resolution](https://cloud.githubusercontent.com/assets/1614425/8246903/c5fb0c4e-1614-11e5-84ef-5b36488c68a8.png)

![linux-resolution](https://cloud.githubusercontent.com/assets/1614425/8246902/c5f98d92-1614-11e5-9ced-1af27d1b1c7b.png)

@davefinster My best guess (I don't have a vanilla SDC running anymore) is that SDC _weren't_ using any KVM images, and they were all smartos images. So in that case the memory isn't locked down, and can you can provision more than 100% of the available memory that SmartOS has? Or, it's just that all the running VMs, collectively, just didn't use more than 100% of the memory allocated to SmartOS?

@davefinster I didn't need to make any tweaks to the Windows 10 VM. I actually installed it with more than the minimum required 2048 MB of ram that Microsoft posted for installing Windows 10. I decreased the memory used after it had been installed and running to 1024 MB. I wonder if it would have still installed if it had initially been set to 1024MB.

**Comment by rmustacc** [comment]
If you weren't using KVM images with SDC then it's an entirely different ball game. Memory isn't locked down when zones (containters) are being used.

Regarding the video drivers, see options in the vmadm manual page for the vga property. I'm not sure which will give you a higher resolution. It's certainly not something we focus on or put much energy into.

**Comment by davefinster** [comment]
@naisanza Ahh I just noticed the build number on your Windows 10 image - that build number is the last one before the issues started cropping up in KVM. The tweaks I mentioned are required for newer versions. And yes, native OS zones have a 'maximum_physical_memory' property whereas KVMs have 'ram' (they also have 'maximum_physical_memory', but thats ram + 1GB). With OS zones you can overcommit.

**Comment by naisanza** [comment]
@rmustacc Thanks! I'll take a look at the man page

@davefinster ahh gotcha. I figured somewhere you were able to overcommit, but didn't know that was only for OS zones. I'll do some more searching, but is there an image that has, say, a linux distro that runs completely as an OS zone instead of a KVM? Is that possible?

**Comment by davefinster** [comment]
They are called LX zones and you should find images inside imgadm. Keep in mind that an OS zone can only use the SmartOS kernel and nothing else, so these zones emulate the Linux specific syscalls that wouldn't normally exist. More detail here https://wiki.smartos.org/display/DOC/LX+Branded+Zones

**Comment by naisanza** [comment]
@davefinster Thank you! and thank you everyone that's helped me on this question
