### ISSUE TITLE
allow filters for imgadm avail

### ISSUE THREAD

**Issue by rzezeski** [joyent/smartos-live#460]
It would be convenient if `imgadm avail` allowed filters.

1. It's more consistent with `list`.

2. Better than having to specify a custom field list and grep.

Until recently I've never really needed this but now that you cannot
distinguish lx images from kvm images in the default output it would
be very handy. E.g.:

```
# imgadm avail type=lx-dataset
```

Right now you have to do the slightly more cumbersome:

```
# imgadm avail -o uuid,name,version,os,type,published | grep lx-dataset
```

**Comment by bahamas10** [comment]
thanks! I agree this would be an awesome feature to have.

mirrored issue here https://smartos.org/bugview/OS-4712

webrev: http://us-east.manta.joyent.com/bahamas10/public/webrev/OS-4712/index.html

```
# ./sbin/imgadm avail type=lx-dataset name=~lx-ubuntu
UUID                                  NAME             VERSION   OS     PUBLISHED
818cc79e-ceb3-11e4-99ee-7bc8c674e754  lx-ubuntu-14.04  20150320  other  2015-03-20T03:45:09Z
430da066-e3a7-11e4-9657-332a2dbdf565  lx-ubuntu-14.04  20150415  other  2015-04-15T19:40:25Z
a21a64a0-0809-11e5-a64f-ff80e8e8086f  lx-ubuntu-14.04  20150601  other  2015-06-01T02:55:17Z
```

```
# ./sbin/imgadm avail os=linux version=20150724
UUID                                  NAME          VERSION   OS     PUBLISHED
380539c4-3198-11e5-82c8-bf9eeee6a395  debian-7      20150724  linux  2015-07-24T00:09:14Z
ab3db4c0-31ac-11e5-8856-43e56a8e4285  centos-6      20150724  linux  2015-07-24T02:35:38Z
ead4ff68-320a-11e5-bd54-3749d04712df  ubuntu-14.04  20150724  linux  2015-07-24T13:50:17Z
```

**Comment by rzezeski** [comment]
@bahamas10 The webrev for OS-4712 looks good.

**Comment by bahamas10** [comment]
@rzezeski updated in https://github.com/joyent/smartos-live/commit/01e23ba911ffb3e57c4538fa97ec55424583d244
