### ISSUE TITLE
ship vioif

### ISSUE THREAD

**Issue by nshalman** [joyent/smartos-live#463]
Now that 3644/4945 has landed upstream and been merged, we should ship vioif.

I'll open the PRs against both joyent/smartos-live and joyent/illumos-joyent using this issue ID.

**Comment by nshalman** [comment]
Looks like Jerry is taking care of this. I'll close this out when I confirm it's all working.

**Comment by nshalman** [comment]
@jjelinek do we not also need an entry in name_to_major like I have in:
https://github.com/nshalman/smartos-live/commit/068a2d754ce51442cf6a0736833e9995b8ecbc51

**Comment by jjelinek** [comment]
Yes, thanks for noticing and sorry I missed that. I'll add it now.

**Comment by nshalman** [comment]
@jjelinek thanks for taking care of all of this. One less feature I need to maintain in downstream branches.

**Comment by nshalman** [comment]
Closed by
https://github.com/joyent/illumos-joyent/commit/7be989b3b3d0affc5705ea8b81d4b84ec65d8246
https://github.com/joyent/smartos-live/commit/baabce45af9f329c8547a16d9fc9f68c355e0db2
https://github.com/joyent/smartos-live/commit/54205ce0b7648680e67af00d48add32badad8cb2
