### ISSUE TITLE
allow admin_nic to have a tagged vlan

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#465]
admin_nic and external_nic should ideally be treated the same.

Currently external_nic can take a vlan and it will create a vnic over whatever interface _nic points to with the vlan set.
admin_nic should be treated the same way resulting in a vnic with an optional vlan set.

**Comment by konobi** [comment]
We're very picky about the admin_nic being totally separate. If you need to have the admin_nic on a vlan, I suggest that you put the switch port into access mode for the vlan id in question.

**Comment by sjorge** [comment]
Fair enough, I will close this and stick my current (hacky) setup.

For anyone looking through the archive.
setup admin_nic completely static, have a custom smf scrip that discards the config and setup a vnic and configure the address on there. 'IT MOSTLY WORKS TM'

**Comment by sjorge** [comment]
FYI, I tried it again the 'correct' way.
trunk0 untagged -> vlan 30
trunk0 tagged -> vlan 10, vlan 20, vlan 40

It resulted in some weird in.ndpd behavior, currently back to my hack that does:
```
ipadm delete-if ${NIC}
 
## create vnic and set addresses
dladm create-vnic -t -l ${NIC} -v ${CONFIG_admin_vnic_vlan} -m ${CONFIG_admin_vnic_mac} e1000g0
ipadm create-addr -t -T static -a ${CONFIG_admin_ip}/24 e1000g0/v4s
ipadm create-addr -t -T addrconf e1000g0/v6a
ipadm create-addr -t -T static -a ${CONFIG_admin_ip6}/${CONFIG_admin_netmask6} e1000g0/v6s
sleep 2
route add default ${CONFIG_admin_gateway}
route add -inet6 default ${CONFIG_admin_gateway6}
```
