### ISSUE TITLE
lx brand: /dev/log: Function not implemented

### ISSUE THREAD

**Issue by krzaczek** [joyent/smartos-live#466]
Hi,

I'm having problem with rsyslogd and the ability to log to sysylog through /dev/log. It seems it's not working properly.

```
Jul 31 16:31:22 localhost rsyslogd: [origin software="rsyslogd" swVersion="7.4.4" x-pid="30075" x-info="http://www.rsyslog.com"] start
Jul 31 16:31:22 localhost rsyslogd: cannot create '/dev/log': Function not implemented
Jul 31 16:31:22 localhost rsyslogd: imuxsock does not run because we could not aquire any socket

Jul 31 16:31:22 localhost rsyslogd-3000: activation of module imuxsock failed
```

SmartOS SunOS salak 5.11 joyent_20150723T072528Z i86pc i386 i86pc

Checked both lx-debian lx-ubuntu
a21a64a0-0809-11e5-a64f-ff80e8e8086f  lx-ubuntu-14.04  20150601  other    2015-06-01T02:55:17Z
a781a350-07f4-11e5-9372-5f2886027fbc  lx-debian-7      20150601  other    2015-06-01T00:25:06Z

It looks like no program running locally is able to log to syslog.

**Comment by lloydde** [comment]
Looks like this could relate to https://smartos.org/bugview/OS-3189

**Comment by lloydde** [comment]
@pfmooney corrected me, we have special handling in LX for /dev/log. He has isolated the issue, and it's being tracked in https://smartos.org/bugview/OS-4586 .

Thank you @krzaczek for reporting this! It sounds like we'll have a reviewed fix in the next week.

**Comment by pfmooney** [comment]
This should be fixed in joyent/illumos-joyent@2a4baf9fe8cd0e7d7ba626c12c42f3afedc59e1b

Thanks

**Comment by krzaczek** [comment]
Perfect :D

pawel (at) mobile

**Comment by krzaczek** [comment]
I can confirm it works on 
joyent_20150806T063417Z

**Comment by lloydde** [comment]
Thanks @kevinykchan for verifying resolved!
