### ISSUE TITLE
fwadm does not allow for rules containing IPv6 IP's

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#468]

**Comment by scarcry** [comment]
Any updates on this?
I'd love to use fwadm(1m) on all my zones but I can't because I'm running services on IPv6

**Comment by melloc** [comment]
@scarcry I've mostly finished this up, but I'm still testing some things out with FWAPI. If you're interested, I can upload a platform image if you want to play around with it.

**Comment by scarcry** [comment]
@melloc I'm definitely interested in testing this.. I'm just now learning fwadm(1m) and want to get my head around it but would be great if could firewall all my zones using it instead of using ipfilter locally.
does your your platform image also use openssh like the official joyent images?

**Comment by melloc** [comment]
@sjorge @scarcry I've uploaded some builds here:

http://us-east.manta.joyent.com/cody.mello/public/builds/FWAPI-225/platform-20160217T071244Z.tgz
http://us-east.manta.joyent.com/cody.mello/public/builds/FWAPI-225/platform-20160217T071244Z.usb.bz2
http://us-east.manta.joyent.com/cody.mello/public/builds/FWAPI-225/smartos-20160217T071244Z.vmwarevm.tar.bz2

You can see some examples in `fwrule(5)` and in the [FWAPI-225 description](https://smartos.org/bugview/FWAPI-225).

**Comment by melloc** [comment]
@scarcry Sorry, I realized that I forgot to answer the question at the end of your comment: Yes, it includes openssh just like the official images. This build should be identical to the one released Thursday minus maybe any kernel bits that made it in several days before the release.

**Comment by melloc** [comment]
This is resolved in FWAPI-225 by 63f75cc.
