### ISSUE TITLE
ZFS Delegated Permissions for receiving streams are not working in recentish builds

### ISSUE THREAD

**Issue by natefoo** [joyent/smartos-live#469]
I am attempting to use `zfs allow` to delegate non-root users as `zfs receive` targets for a backup system. Under 20141212T011737Z this works as expected:

``` console
[root@20141212T011737Z ~]# zfs create zones/test
[root@20141212T011737Z ~]# zfs allow -u upnp create,hold,mount,mountpoint,receive,send,snapshot zones/test
[root@20141212T011737Z ~]# chown upnp:upnp /zones/test
[root@20141212T011737Z ~]# su upnp -c /bin/bash
[upnp@20141212T011737Z ~]$ zfs create zones/test/foo
[upnp@20141212T011737Z ~]$ zfs create zones/test/recv
[upnp@20141212T011737Z ~]$ cd /zones/test/foo
[upnp@20141212T011737Z /zones/test/foo]$ echo 0 >foo
[upnp@20141212T011737Z /zones/test/foo]$ zfs snapshot zones/test/foo@0
[upnp@20141212T011737Z /zones/test/foo]$ zfs send -v zones/test/foo@0 | zfs recv -ve zones/test/recv
send from @ to zones/test/foo@0 estimated size is 10K
total estimated size is 10K                                                                         
TIME        SENT   SNAPSHOT                                                                   
receiving full stream of zones/test/foo@0 into zones/test/recv/foo@0                
received 43.0KB stream in 1 seconds (43.0KB/sec)
```

But on 20150528T153328Z, the final step fails:

``` console
[upnp@20150528T153328Z /zones/test/foo]$ zfs send -v zones/test/foo@0 | zfs recv -ve zones/test/recv
send from @ to zones/test/foo@0 estimated size is 10K
total estimated size is 10K
TIME        SENT   SNAPSHOT
receiving full stream of zones/test/foo@0 into zones/test/recv/foo@0
cannot receive new filesystem stream: permission denied
```

Thinking that additional privileges may be required in newer versions, I tried giving the user all privileges listed under the `zfs allow` section of `zfs(1m)` to test, but that made no difference.

These examples are done in the GZ just to rule out zones as a culprit, but the problem was originally observed in a base64 image running on 20150528T153328Z. It is still occurring as of 20150806T063417Z.

**Comment by rmustacc** [comment]
@jjelinek can you take a look at this? This seems to be due to the fact that we introduced the PRIV_SYS_FS_IMPORT privilege.

**Comment by natefoo** [comment]
I can confirm that the issue identified by @rmustacc is the problem. If I grant `sys_fs_import` to the user, it is able to `zfs receive`.

**Comment by gwr** [comment]
Is this still a bug?  I might have just run into it...

**Comment by bahamat** [comment]
This actually isn't a bug. This was implemented for [OS-3757](https://smartos.org/bugview/OS-3757). In order to grant permission to `zfs recv` in a zone you need to add the `sys_fs_import` privilege in the vm json.

**Comment by natefoo** [comment]
@bahamat if nothing else, it'd probably be good to document this on `zfs(1m)` because I think it's pretty unlikely to be found on `privileges(5)` and it's the only such ZFS delegated admin privilege that additionally requires a system privilege to function. Beyond that, there's more that could be done to prevent people from falling in to this trap, such as not allowing the ZFS privilege to be assigned if the system privilege is not enabled (or at least produce a warning message).
