### ISSUE TITLE
vmamd dies from EADDRINSUE when multiple VMs define same vnc_port

### ISSUE THREAD

**Issue by xen0l** [joyent/smartos-live#481]
I have a SmartOS host, which I am using for building custom VM images in an automated fashion. What I didn't realize was that some hosts had the same vnc_port defined. When I booted the first VM, everything was OK. However, booting the second VM caused EADDRINUSE as vmadmd tries to bind to the port and dies as the port is being used. SMF tries to bring it online, but vmadm dies until it is moved into the maintenance state. Once, vmadmd is down, vmadm is not working.

From log file: 

<pre>
{
  "name": "vmadmd",
  "hostname": "smartos1",
  "pid": 82352,
  "level": 30,
  "msg": "spawning vnc listener for b0a59672-4e93-11e5-935c-c72ca5fd2374 on 172.18.0.101",
  "time": "2015-08-30T08:15:28.153Z",
  "v": 0
}
Uncaught Error: listen EADDRINUSE

FROM
Server.EventEmitter.emit (events.js:72:15)
net.js:1049:12
process._tickCallback (node.js:415:13)
[ Aug 30 08:15:28 Stopping because all processes in service exited. ]
[ Aug 30 08:15:28 Executing stop method (:kill). ]
</pre>

There should be a check possibly in vmadm, which won't allow this situation to happen. It could possibly mimic the logic, which vmadm uses to avoid IP conflicts.

**Comment by bahamas10** [comment]
Fixed via #740
