### ISSUE TITLE
kernel data corruption induced by "mdb -kw"

### ISSUE THREAD

**Issue by krzaczek** [joyent/smartos-live#494]
After upgrading SmartOS to the latest release 20151001T070028Z and 20151015T063628Z my servers started to randomly reboot with this message

`
2015-10-18T19:53:37.201626+02:00 smartos3 savecore: [ID 570001 auth.error] reboot after panic: BAD TRAP: type=e (#pf Page fault) rp=ffffff007bef8a30 addr=400001c8 occurred in module "unix" due to an illegal access to a user address
`

Core dumps
- smartos3.z [vmdump.0](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos3.z/vmdump.0) [vmdump.1](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos3.z/vmdump.1) [vmdump.5](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos3.z/vmdump.5)
- smartos5.z [vmdump.2](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos5.z/vmdump.2) [vmdump.3](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos5.z/vmdump.3)
- smartos7.z [vmdump.5](https://s3.eu-central-1.amazonaws.com/freshmind.other/smartos/smartos7.z/vmdump.5)

**Comment by rmustacc** [comment]
Thank you for reporting this and sorry about the trouble that you're having with the system. I grabbed this first one and it looks like the stack was:

```
ffffff007b650b50 mutex_enter+0xb()
ffffff007b650b80 kmem_cache_reap_now+0x18(40000000)
ffffff007b650bb0 arc_kmem_reap_now+0x53()
ffffff007b650c20 arc_reclaim_thread+0x21a()
ffffff007b650c30 thread_start+8()
```

Do all of your dumps have a similar stack trace? You can get the stack trace by running savecore -vf on a `vmdump.<num>` file and then running `mdb -e '$C' <num>` which will print a stack back trace.

In addition, do you recall what release you were on before you upgraded?

**Comment by krzaczek** [comment]
Upgraded from 20141225T170427Z

**Comment by krzaczek** [comment]
`
smartos5.z
> $C
ffffff007b965b50 mutex_enter+0xb()
ffffff007b965b80 kmem_cache_reap_now+0x18(40000000)
ffffff007b965bb0 arc_kmem_reap_now+0x53()
ffffff007b965c20 arc_reclaim_thread+0x21a()
ffffff007b965c30 thread_start+8()
`

`
smartos7.z
> $C
ffffff001f16ab50 mutex_enter+0xb()
ffffff001f16ab80 kmem_cache_reap_now+0x18(40000000)
ffffff001f16abb0 arc_kmem_reap_now+0x53()
ffffff001f16ac20 arc_reclaim_thread+0x21a()
ffffff001f16ac30 thread_start+8()
`

It look's like the stack trace is identical on all servers. @rmustacc  If You need I can upload vmdump from all servers.

**Comment by krzaczek** [comment]
It look's like it has something to do with RAM and ARC. Ram usage keeps raising and as soon it reaches almost 100% server reboots. At the same time ARC is rising too. See screenshots

![ram](https://www.dropbox.com/s/9ke1g87cqv4lzpa/Zrzut%20ekranu%202015-10-20%2016.44.54.png?dl=1)

![arc](https://www.dropbox.com/s/itrvebxx0i9wta9/Zrzut%20ekranu%202015-10-20%2016.44.49.png?dl=1)

**Comment by krzaczek** [comment]
I have limited the amount arc that can be used to 4GB ... will see who it behaves in the next 24h

```
---------------------------------------------
[root@smartos3 ~]# /opt/custom/arc_summary.pl 
System Memory:
         Physical RAM:  65480 MB
         Free Memory :  52499 MB
         LotsFree:      1023 MB

ZFS Tunables (/etc/system):
         set zfs:zfs_arc_max = 4294967296
         set zfs:zfs_arc_min = 2147483648

ARC Size:
         Current Size:             1902 MB (arcsize)
         Target Size (Adaptive):   4096 MB (c)
         Min Size (Hard Limit):    2048 MB (zfs_arc_min)
         Max Size (Hard Limit):    4096 MB (zfs_arc_max)
```

**Comment by rmustacc** [comment]
If it's possible, on a server that you've just booted up and already seen this, can you run the following two commands in mdb -k:

```
zio_buf_cache,8000/Kna ! grep 000000
zio_data_buf_cache,8000/Kna ! grep 000000
```

This will help us bifurcate the problem.

**Comment by krzaczek** [comment]
```
[root@smartos3 ~]# w
09:35:39    up 1 min(s),  1 user,  load average: 0,80, 0,18, 0,06
User     tty      login@         idle    JCPU    PCPU what
root     pts/2    09:35:34          0       0       0 w
[root@smartos3 ~]# uname -a
SunOS smartos3.z 5.11 joyent_20151001T070028Z i86pc i386 i86pc
[root@smartos3 ~]# mdb -k
Loading modules: [ unix genunix specfs dtrace mac cpu.generic uppc apix scsi_vhci ufs ip hook neti sockfs arp usba uhci qlc fctl stmf_sbd stmf zfs lofs idm mpt sata mpt_sas pmcs crypto random cpc logindmux ptm kvm sppp nsmb smbsrv nfs sd mr_sas ]
> zio_buf_cache,8000/Kna ! grep 000000
> zio_data_buf_cache,8000/Kna ! grep 000000
> 
```

**Comment by bcantrill** [comment]
In the dump that you uploaded, we are seeing corruption in the middle of the `zio_buf_cache` array -- which is unexpected given that it isn't written to after system initialization. What makes it very odd is that you seem to have seen multiple dumps (on multiple machines) with the same corruption.  We were hoping that the corruption was happening before ARC-induced kmem reclaim occurred, but your output above indicates that it's not that simple.  I know that this is inconvenient, but could you make available every dump from every system that has seen this?  It is very important that we ascertain any differences in the corruption.  Also, would it potentially be possible to run one of these machines with `kmem_flags` set to `0xf`?  If so, [Max's article on kmem debugging](http://www.joyent.com/blog/kernel-memory-allocator-0xdeadbeef-checking) describes how to do this on SmartOS; any dump with `kmem_flags` set will be much more useful in debugging this problem -- with our apologies for the issue!

**Comment by krzaczek** [comment]
I will upload all the dump do s3 and let You know when they are available

**Comment by krzaczek** [comment]
@bcantrill 0xf or 0x1f ?

**Comment by krzaczek** [comment]
I also have a server running smartso5.z that returns some results for zio_buf_cache,8000/Kna ! grep 000000

It's benn up for 1 day
```
[root@smartos5 /var/crash/volatile]# uname -a
SunOS smartos5.z 5.11 joyent_20141225T170427Z i86pc i386 i86pc
[root@smartos5 /var/crash/volatile]# w
14:06:05    up 1 day(s), 21:57,  1 user,  load average: 1,30, 1,41, 1,48
User     tty      login@         idle    JCPU    PCPU what
root     pts/12   13:59:20          0       1       0 w
[root@smartos5 /var/crash/volatile]# mdb -k
Loading modules: [ unix genunix specfs dtrace mac cpu.generic uppc apix scsi_vhci ufs ip hook neti sockfs arp usba stmf_sbd stmf zfs lofs idm sata crypto random cpc logindmux ptm kvm sppp nsmb smbsrv nfs mr_sas sd ]
> zio_buf_cache,8000/Kna ! grep 000000
zio_buf_cache+0x3920:           40000000        
zio_buf_cache+0x3950:           80000000        
zio_buf_cache+0x39b0:           80000000        
> zio_data_buf_cache,8000/Kna ! grep 000000
> 
```

**Comment by bcantrill** [comment]
Yow -- that's the same corruption pattern seen in the dump; very, very strange!  At this point, would definitely want a machine running with `kmem_flags` set.  In terms of `0xf` vs. `0x1f` for `kmem_flags`, it doesn't matter; `0xf` is fine.

**Comment by krzaczek** [comment]
I have rebooted one server woth kmem_flags. If it fails .. I'll let You know

**Comment by krzaczek** [comment]
This is without `kmem_flags`

[smartos5.z](https://s3.amazonaws.com/freshmind.other/smartos/smartos5.z/vmdump.2)
[smartos7.z](https://s3.amazonaws.com/freshmind.other/smartos/smartos7.z/vmdump.5)

**Comment by bcantrill** [comment]
So we now have dumps from three different nodes (`smartos3.z`, `smartos5.z` and `smartos7.z`) running (interestingly!) three different platforms (`joyent_20151015T063628Z`, `joyent_20151001T070028Z` and `joyent_20141225T170427Z`, respectively) -- all of which exhibit the same kind of corruption in the `zio_buf_cache` (at offset `0x38e0`, `0x38e0` and `0x3920`, respectively).  That these are three different nodes eliminates all kinds of hypotheses -- as does the fact that this was seen on the older platform: whatever this is isn't a recent regression.  More investigation clearly required here -- and it seems that there might be more dumps (perhaps two more from `smartos5.z` and four more from `smartos7.z`?).  If so, it would be helpful to have these additional dumps as well...

**Comment by krzaczek** [comment]
I may have dumps from smartos5.z ... smartos7.z has a small hard drive so I had to remove them ... but I will post any new dumps before deleting them.

**Comment by krzaczek** [comment]
I have 2 more dumps from smartos3.z .... but vmdump.1 is a rally old crash from 06.2014 ... so it's probably not related.

```
[root@smartos5 /var/crash/volatile]# mdb -e '$C' 2
mdb: warning: dump is from SunOS 5.11 joyent_20151001T070028Z; dcmds and macros may not match kernel implementation
ffffff007b965b50 mutex_enter+0xb()
ffffff007b965b80 kmem_cache_reap_now+0x18(40000000)
ffffff007b965bb0 arc_kmem_reap_now+0x53()
ffffff007b965c20 arc_reclaim_thread+0x21a()
ffffff007b965c30 thread_start+8()
```

```
mdb: warning: dump is from SunOS 5.11 joyent_20131009T194502Z; dcmds and macros may not match kernel implementation
ffffff007d045aa0 cap_kstat_update+0x23(ffffff128cad2110, 0)
ffffff007d045c80 read_kstat_data+0xc3(ffffff007d045ea8, f9bef0, 202001)
ffffff007d045cc0 kstat_ioctl+0x83(200000000, 4b02, f9bef0, 202001, 
ffffff1161f9c6a8, ffffff007d045ea8)
ffffff007d045d00 cdev_ioctl+0x39(200000000, 4b02, f9bef0, 202001, 
ffffff1161f9c6a8, ffffff007d045ea8)
ffffff007d045d50 spec_ioctl+0x60(ffffff11566f0080, 4b02, f9bef0, 202001, 
ffffff1161f9c6a8, ffffff007d045ea8, 0)
ffffff007d045de0 fop_ioctl+0x55(ffffff11566f0080, 4b02, f9bef0, 202001, 
ffffff1161f9c6a8, ffffff007d045ea8, 0)
ffffff007d045f00 ioctl+0x9b(3b, 4b02, f9bef0)
ffffff007d045f10 sys_syscall+0x17a()
```

**Comment by krzaczek** [comment]
I'll upload vmdump.2 in the evening (Poland time) :)

**Comment by bcantrill** [comment]
Yes, `vmdump.1` is a dup of OS-2596, fixed almost exactly two years ago. ;)  Too bad about the other dumps from `smartos7.z`; those were of particular interest because they are on the older platform. Looking forward to the other dump from `smartos3.z`, though I don't honestly expect it to contain many surprises; it likely has the same mysterious corruption at approximately the same location.  Still, it would be good to verify that, so thanks in advance for uploading it.  In the meantime, we'll hope that one of the machines with `kmem_flags` hits an easier-to-debug manifestation of this -- and at the same time, I'll see if this distinctive pattern is found elsewhere in the system. Thank you again for your help in debugging this!

**Comment by bcantrill** [comment]
Somehow in all of the updates, I missed your earlier update about the script that uses `mdb -kw` to dynamically modify the ARC variables!  That is absolutely the source of the corruption here; root cause to come...

**Comment by bcantrill** [comment]
Is the script mentioned above running multiple times? Are there other scripts that are executing `mdb -kw`?  When is the script being run?  On the one hand, I don't see off-hand how the quoted elements can be inducing the problem as seen -- but on the other, there are way too many coincidences to discount (namely, the values being written match the corruption, and that the destination addresses for the writes are close to that of the corrupted location).  Could you provide all of `custom-boot.sh`?

**Comment by krzaczek** [comment]
So the script is run one time at boot by a custom smf. Example from smartos7.z

/opt/custom/smf/custom-boot.xml
```xml
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='export'>
  <service name='site/custom-boot' type='service' version='0'>
    <create_default_instance enabled='true'/>
    <single_instance/>
    <dependency name='network' grouping='require_all' restart_on='error' type='service'>
      <service_fmri value='svc:/milestone/network:default'/>
    </dependency>
    <dependency name='filesystem' grouping='require_all' restart_on='error' type='service'>
      <service_fmri value='svc:/system/filesystem/local'/>
    </dependency>
    <exec_method name='start' type='method' exec='/opt/custom/bin/custom-boot.sh' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='staff'/>
        <method_environment>
          <envvar name='PATH' value='/usr/bin:/usr/sbin:/bin'/>
        </method_environment>
      </method_context>
    </exec_method>
    <exec_method name='restart' type='method' exec=':kill' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='staff'/>
      </method_context>
    </exec_method>
    <exec_method name='stop' type='method' exec=':kill' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='staff'/>
      </method_context>
    </exec_method>
    <property_group name='startd' type='framework'>
      <propval name='duration' type='astring' value='transient'/>
      <propval name='ignore_error' type='astring' value='core,signal'/>
    </property_group>
    <property_group name='application' type='application'/>
    <stability value='Evolving'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>custom boot</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
```

/opt/custom/bin/custom_boot.sh
```
#!/usr/bin/sh

#ZFS ARC
ARCSTAT_P=`echo "arc_stats::print -a arcstat_p.value.ui64" | mdb -kw | cut -d ' ' -f 1`
ARCSTAT_C_MIN=`echo "arc_stats::print -a arcstat_c_min.value.ui64" | mdb -kw | cut -d ' ' -f 1`
ARCSTAT_C_MAX=`echo "arc_stats::print -a arcstat_c_max.value.ui64" | mdb -kw | cut -d ' ' -f 1`
echo "${ARCSTAT_P}/Z 0x40000000" | mdb -kw
echo "${ARCSTAT_C_MIN}/Z 0x80000000" | mdb -kw
echo "${ARCSTAT_C_MAX}/Z 0x80000000" | mdb -kw
```

It is supposed to be run only one time .. but I may have run it multiple times in a past few days .. when the problem started to occur, and I wanted to modify the arc

**Comment by krzaczek** [comment]
Added some more dumps in [one](494#issue-112033229) place at top of the page

**Comment by krzaczek** [comment]
Just to keep You up to date, both `smartso3.z` and `smartos7.z` (running with `kmem_flags = 0xf`) are up and running without any corruption in `zio_buf_cache` for over 24h now

**Comment by bcantrill** [comment]
At this point, it seems very likely that the corruption was induced by `mdb -kw` activity, though the specific mechanics are still unclear.  To facilitate understanding this, I have added logging to the kernel on every write to `/dev/kmem` in OS-4869; recommend running this fix once it's available and then running the new `::kmemlog` debugger command to determine the source of this corruption.

**Comment by krzaczek** [comment]
I'll upgrade as soon as a new version is available

**Comment by bcantrill** [comment]
Any update on this? Did you get the opportunity to upgrade and run the `::kmemlog` mdb dcmd?

**Comment by krzaczek** [comment]
Yes I did .. but could not make any server to crash .. so I think at the moment we can close this issue. 
If it crashes again I'll open a new ticket and reference this one.

**Comment by matthiasg** [comment]
@krzaczek may i ask how you changed the `zfs_arc_max` parameter ? /etc/system is getting reset on boot is it not ?

**Comment by krzaczek** [comment]
@matthiasg see https://github.com/joyent/smartos-live/issues/494#issuecomment-149953361

**Comment by matthiasg** [comment]
@krzaczek thanks. interesting. i was under the impression that changing zfs_arc_max after boot (during service startup) would be too late. i was looking into http://blog.shalman.org/overriding-driver-config-files-on-smartos/. i will try that though

**Comment by krzaczek** [comment]
@matthiasg well changing /etc/system is to late .. but You can modify without reboot ... see this http://wiki.pressy.net/ZFS

**Comment by matthiasg** [comment]
@krzaczek i meant changing before boot using grub replacement as described in the article linked not changing the /etc/system after boot. solaris seemed to not support updating zfs_arc_max at runtime at all, but that might be due to it not being able to lower once over the max limit.

**Comment by krzaczek** [comment]
Well sure ... but this custom SMF runs just after boot .. so there is a good change it's not over the max limit yet :)

**Comment by krzaczek** [comment]
@matthiasg check this out .. http://dtrace.org/blogs/wesolows/2013/12/28/anonymous-tracing-on-smartos/ - this may be interesting for You ... how to boot with a modified /etc/system for smartos

**Comment by matthiasg** [comment]
@krzaczek yup. i was referring to that article (its linked in the other one i posted) .. but its more involved than just adding an smf service like you did and i like it a lot more.

**Comment by matthiasg** [comment]
@krzaczek are you still limiting arc using a bootup script ? is it stable now or do the symptoms above still appear ?

**Comment by krzaczek** [comment]
@matthiasg yes i'm still using this method and it's been working since then without any problems so far. I'm running two versions of SmartOS on around 16 servers.

`20181011T004530Z`
`20171221T020409Z`
