### ISSUE TITLE
possible error in identity-node

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#502]
https://github.com/joyent/smartos-live/blob/master/overlay/generic/lib/svc/method/identity-node#L116

Not sure shcat is a command, man or just trying to run it on a compute nodes does nothing.

**Comment by rmustacc** [comment]
Certainly looks suspicious, is it generating an error or is the identity-node service not working correctly?

**Comment by jclulow** [comment]
So, `shcat` comes from [/lib/svc/share/net_include.sh][1] on the system, which is shipped from illumos.

[1]: https://github.com/joyent/illumos-joyent/blob/master/usr/src/cmd/svc/shell/net_include.sh#L37-L48

**Comment by sjorge** [comment]
Learned something new today :) thanks @jclulow will close it, as it is not causing errors.

@rmustacc nope but was looking at expanding some of the ip6 support (e.g. update /etc/hosts with the ip6 addres for example) and ran into this... trying to understand what does what and couldn't figure out this shcat :)
