### ISSUE TITLE
svccfg cleanup removes SMF services that are needed to boot a zone

### ISSUE THREAD

**Issue by stevenwilliamson** [joyent/smartos-live#505]
The commit for this Illumos bug https://www.illumos.org/issues/1565 has the knock on affect that `svccfg cleanup` (undocumented in the man page) will remove SMF services that are required for a zone to boot.

It seems svccfg cleanup always used to stop at the first error which has previously been an error about duplicate definitions:

```
+ /usr/sbin/svccfg cleanup
svccfg: Multiple definitions for property value_F5SGK5RPMNXW443PNRSQ----_description_C in property group tm_proppat_nt_ttymon_device.
```

Since the fix however svccfg cleanup no longer exits at this point and carries on, resulting in among others `system/boot-archive` been removed from the SMF repo. As core SMF services list `system/boot-archive` as a dependency the zone will no longer start.

```
+ /usr/sbin/svccfg cleanup
svccfg: Multiple definitions for property value_F5SGK5RPMNXW443PNRSQ----_description_C in property group tm_proppat_nt_ttymon_device.
Delete service svc:/network/ldap/client as there are no supporting manifests
Delete service svc:/network/nfs/mapid as there are no supporting manifests
Delete service svc:/network/nfs/status as there are no supporting manifests
Delete service svc:/network/nis/client as there are no supporting manifests
Delete service svc:/network/nfs/client as there are no supporting manifests
Delete service svc:/network/nfs/nlockmgr as there are no supporting manifests
Delete service svc:/system/boot-archive as there are no supporting manifests
Delete service svc:/system/sac as there are no supporting manifests
Delete service svc:/system/sysidtool as there are no supporting manifests
```

This bug at first seemed only to affect our custom images. Though our custom images really boil down to taking the base64 image, installing ruby, puppet, and adding an SMF manifest for puppet. Followed by sm-prepare-image script.

When provisioning our image after the svccfg cleanup is run, and the system/boot-archive service is removed. The zone then reboots after completing the initial provision and fails to come up due to the missing service:

````
[root@broken-dev ~]# svcs -xv
svc:/system/filesystem/usr:default (read/write root file systems mounts)
 State: offline since Thu Nov  5 13:10:39 2015
Reason: Dependency svc:/system/boot-archive is absent.
   See: http://illumos.org/msg/SMF-8000-E2
Impact: 37 dependent services are not running:
        svc:/network/ipsec/ipsecalgs:default
        svc:/milestone/network:default
        svc:/network/initial:default
        svc:/network/service:default
        svc:/network/dns/client:default
        svc:/milestone/single-user:default
        svc:/milestone/sysconfig:default
        svc:/milestone/multi-user:default
-----snipped for clarity------
```

Digging further the standard Joyent images are affected, it just depends on the code path taken in the `/lib/svc/method/manifest-import` script.

Any code path that ends up setting the activity variable = true, will trigger this problem. For our images activity is been set to true due to svccfg importing a manifest: https://github.com/joyent/smartos-live/blob/master/overlay/generic/lib/svc/method/manifest-import#L247


When activity = true svccfg cleanup is called at the end of the script. If it is false, cleanup_needwork function is called instead, returns 0, an no cleanup is run.


Of course aside from the manifest-import trigger, if a user just issues svccfg cleanup, the same problem results.

**Comment by jperkin** [comment]
A fix for this:

```diff
--- /usr/lib/brand/joyent/manifests	Wed Nov  4 22:10:22 2015
+++ manifests	Fri Nov  6 10:46:53 2015
@@ -76,7 +76,6 @@
 # network/nfs/client.xml
 # network/nfs/nlockmgr.xml
 # system/boot-archive-update.xml
-# system/boot-archive.xml
 # system/boot-config.xml
 # system/fmd.xml
 # system/sac.xml
@@ -138,6 +137,7 @@
 network/vrrp.xml		disabled
 system/auditd.xml		disabled
 system/auditset.xml		disabled
+system/boot-archive.xml		enabled
 system/consadm.xml		disabled
 system/console-login.xml	disabled
 system/coreadm.xml		enabled
```

Loopback mounting the fixed file over the top, then restarting the `svc:/system/zones:default` service, results in a cleanup operation on a freshly installed zone working correctly:

```console
# svccfg cleanup
svccfg: Multiple definitions for property value_F5SGK5RPMNXW443PNRSQ----_description_C in property group tm_proppat_nt_ttymon_device.
Delete service svc:/network/ldap/client as there are no supporting manifests
Delete service svc:/network/nfs/mapid as there are no supporting manifests
Delete service svc:/network/nfs/status as there are no supporting manifests
Delete service svc:/network/nis/client as there are no supporting manifests
Delete service svc:/network/nfs/client as there are no supporting manifests
Delete service svc:/network/nfs/nlockmgr as there are no supporting manifests
Delete service svc:/system/sac as there are no supporting manifests
Delete service svc:/system/sysidtool as there are no supporting manifests
# reboot
# svcs -xv
#
```

Interestingly the `joyent-minimal` brand already enables `boot-archive`, so that doesn't need fixing.

It may be worth reviewing all of the other services that are being deleted to see if we should enable them too at the same time as fixing `boot-archive`.  If they shouldn't be enabled, then we should remove them from the base image repository.

**Comment by jperkin** [comment]
Sorry, bad choice of wording in the last paragraph, 'enabled' should instead read 'imported'.  Whether the services are enabled or disabled is somewhat irrelevant, but the brand manifest and the base image `repository.db` should be in sync as to what is imported.

**Comment by nshalman** [comment]
@jperkin Is joyent/imagetools#2 relevant for this?

**Comment by joshwilsdon** [comment]
Is there a reason not to remove the dependency on boot-archive here instead of adding it to the brand's manifest list? As far as I'm aware there's no value to having this service in a zone and quite possibly no reason to have it in the GZ either on SmartOS.

**Comment by stevenwilliamson** [comment]
boot-archive does nothing in a zone, and isn't needed on SmartOS GZ since it is read only.
Removing the dependency on system/boot-archive from system/filesystem/usr would be ideal, and iv'e tested a zone boots fine with this dep removed.

However im not sure how you would manage this transition, how would you ensure any already provisioned zones have the SMF repository updated to remove this dependency ?

Just importing boot-archive while not the most efficient solves the problem and pretty safely.

Unless im missing an obvious way to ensure system/filesystem/usr gets updated in already provisioned zones. This would have to happen early for new zones too in the initial provision before the first reboot.

**Comment by gsadams** [comment]
Thank you for finally debugging this! I've been hitting my head against this for a couple weeks, now. It seems to hit me in any zone in which I `svccfg import` a new SMF manifest. That zone will then be dead as soon as it (or its host) tries to reboot. I've had to reprovision some of my zones a lot.

The workaround of patching `/usr/lib/brand/joyent/manifests` appears to fix the problem completely for me. Any chance of this file being fixed in an upcoming platform release?

**Comment by jclulow** [comment]
@gsadams I just had this happen to me on my machine.  I'll be taking a look at it tomorrow.  Apologies for the failure, and we should have it fixed soon.

**Comment by jclulow** [comment]
This issue is now reflected in [OS-4920](https://smartos.org/bugview/OS-4920).

**Comment by gsadams** [comment]
Excellent. I'll look forward to it, and keep the lofs-patch fix in place my my hosts until then. Thanks!

**Comment by jclulow** [comment]
The fix ([OS-4920](https://smartos.org/bugview/OS-4920)) should now be available in SmartOS build `20151126T062747Z`.

**Comment by matthiasg** [comment]
@jperkin what exactly does 'Loopback mounting the fixed file' mean ?

**Comment by matthiasg** [comment]
@gsadams how did you patch that file in the read-only filesystem ?

**Comment by jclulow** [comment]
@matthiasg The loopback virtual filesystem, [lofs(7FS)](https://illumos.org/man/7FS/lofs), allows you to mount one file (or directory tree) on top of another.  You can, in the global zone, put the new file somewhere writeable -- then, `lofs` mount the file over the top of the read-only original.

For example, something like:

```
# vi /var/tmp/replacement_file
# mount -F lofs /var/tmp/replacement_file /usr/share/lib/whatever/original/file
```

**Comment by matthiasg** [comment]
@jclulow thanks. I have only recently started playing with lofs (trying to mount an encrypted virtual drive in a zone) but haven't looked at all possibilities yet.

**Comment by matthiasg** [comment]
@jclulow i did this and the file content does indeed look correct. sadly the global zone vmadm create process does not seem to be affected. it still has the same issue
