### ISSUE TITLE
Patched ELF binary runs on Linux, immediately crashes on lx-zone

### ISSUE THREAD

**Issue by vizanto** [joyent/smartos-live#515]
Tried running `java` on a lx-branded NixOS zone today, instead got `Segmentation Fault`.

The Nix package manager patches the RPATH to point directly to all dependencies. This allows for example to have multiple glibc installed without conflicts.

### Discussion on #smartos resulted in this:
dtrace and stuff:
https://gist.github.com/vizanto/b03afde562f650391169

### OpenJDK binary from NixOS

Can be downloaded here:   http://vizanto.com/java

### Related chatlog bits:

>
vizanto:		maybe this is related? https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/8.nix#L201-L202	
vizanto:		( https://nixos.org/patchelf.html )	
rmustacc:		No, setting an rpath is not related.
rmustacc:		Or at least, not unless their patching mechansim is really crazy.
rmustacc:		That just creates entries in the .dynamic section of a binary, it doesn't change the PT_LOAD  / PT_INTERP pieces.
rmustacc:		Likely we're traditionally a bit stricter in the ordering here, where as Linux is looser. It wouldn't be the first time something of this nature has come up in lx.

`...`
>
_mjg:		quick look suggests they just look or PT_INTERP first
_mjg:		and only then start processing other headers
_mjg:		rendering the relative ordering of LOAD and PT_INTERP irrelevant
_mjg:		scratch, there be dragons
vizanto:		https://gist.github.com/vizanto:/622616b739e8e9fb1538
rmustacc:		So it rewrote the program header order, huh.
vizanto:		this did: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/oraclejdk/jdk-linux-base.nix#L144-L149

**Comment by vizanto** [comment]
Fix will be useful for nix built docker images.
( https://github.com/NixOS/nixpkgs/pull/11156 )

**Comment by bcantrill** [comment]
This has been fixed as OS-5015 -- thank you for reporting it!

**Comment by vizanto** [comment]
Indeed works in SmartOS 20151210T194528Z,  thanks!
