### ISSUE TITLE
[BUG] tail and /system/boot/etc/ do not mix well

### ISSUE THREAD

**Issue by failedrequest** [joyent/smartos-live#524]
When using the custom file override on joyent_20151126T062747Z . You can not use the tail command for files mounted out of bootfs.

 For example in this grub config we load a ixgbe.conf off the usb stick and drop into the bootfs
<pre>
title Live 64-bit (text)  
   kernel /platform/i86pc/kernel/amd64/unix -B console=text,smartos=true
   module /platform/i86pc/amd64/boot_archive type=rootfs name=ramdisk
   module /ixgbe.conf type=file name=kernel/drv/ixgbe.conf
</pre> 

This is from http://blog.shalman.org/overriding-driver-config-files-on-smartos/ 

You can not use the tail command on the file. It results in a kernel panic.

In my case I am using iPXE to boot my servers and I wanted to have a custom /etc/system. I setup the following config in my iPXE menu.

<pre>
kernel http://192.168.1.240:8080/smartos/current/platform/i86pc/kernel/amd64/unix ${boot_args}
initrd http://192.168.1.240:8080/smartos/current/platform/i86pc/amd64/boot_archive type=rootfs name=ramdisk
module http://192.168.1.240:8080/smartos/system-custom type=file name=etc/system
</pre>

This creates a correct entry in /system/boot/etc/system 
<pre>
[root@rangefinder ~]# ls -al /system/boot/etc/system 
-r-xr-xr-x   1 root     root        4698 Dec  2 21:15 /system/boot/etc/system
</pre>

However if I want to take a look at my changes I did the following and p00f the box panics. 
I can reproduce this with out issue.

<pre>
[root@rangefinder /system/boot/etc]# tail -n 4 system 

panic[cpu2]/thread=ffffff04ea0f8b00: remap bits changed: old_pte=0x80000003c88c5001, pte=0x80000003c88c5005

ffffff002292b7f0 unix:hati_pte_map+38f ()
ffffff002292b880 unix:hati_load_common+139 ()
ffffff002292b900 unix:hat_memload+75 ()
ffffff002292b940 unix:hat_memload_region+25 ()
ffffff002292ba60 genunix:segvn_faultpage+462 ()
ffffff002292bc30 genunix:segvn_fault+8e6 ()
ffffff002292bd60 genunix:as_fault+37a ()
ffffff002292bdf0 unix:pagefault+96 ()
ffffff002292bf00 unix:trap+30c ()
ffffff002292bf10 unix:cmntrap+e6 ()

syncing file systems... done
dumping to /dev/zvol/dsk/zones/dump, offset 65536, content: kernel
</pre>

It should be noted cat and vi work it looks like an bug in the bootfs code but I am not familiar with it to say what.

**Comment by rmustacc** [comment]
Thanks for reporting this. Resolved in https://github.com/joyent/illumos-joyent/commit/4835b08dae80825afdd06b0ac9db9d458c935dee.
