### ISSUE TITLE
imgadm should include "type" column to differentiate LX and Linux KVM images.

### ISSUE THREAD

**Issue by nshalman** [joyent/smartos-live#532]
People are regularly trying to use LX datasets for VMs and zvols for LX zones.
The two are hard to tell apart with the current output of e.g. "imgadm avail"

The default columns should be adjusted to prevent this confusion.

**Comment by nshalman** [comment]
In theory changing the default columns could break badly written scripts that aren't using e.g. "imgadm avail -Ho uuid,name,version" syntax.

On the other hand, I think it's better to break scripts that depend on the default output than to have people wonder why SmartOS doesn't work correctly.

**Comment by konobi** [comment]
Maybe it'd be better to change "linux" to "linux-lx" and "linux" ?

**Comment by nshalman** [comment]
It was that way for a while, but then it changed. I don't know why. I just want people to not be confused.

**Comment by trentm** [comment]
I'm inclined to change the default columns to include the 'type'. Scripts need to use -Ho or -j for processing.

**Comment by nshalman** [comment]
Works for me.

**Comment by trentm** [comment]
With coming change this'll look like this:

```
[root@headnode (coal) ~]# imgadm list os=linux
UUID                                  NAME          VERSION       OS     TYPE        PUB
ffe82a0a-83d2-11e5-b5ac-f3e14f42f12d  ubuntu-15.04  20151105      linux  lx-dataset  2015-11-05
8a1dbc62-b885-11e5-b0de-1777d1a6eb10  centos-6      20160111      linux  zvol        2016-01-11
```

**Comment by trentm** [comment]
Before the change:

```
[root@headnode (coal) ~]# imgadm list os=linux
UUID                                  NAME          VERSION       OS     PUBLISHED
ffe82a0a-83d2-11e5-b5ac-f3e14f42f12d  ubuntu-15.04  20151105      linux  2015-11-05T15:36:36Z
8a1dbc62-b885-11e5-b0de-1777d1a6eb10  centos-6      20160111      linux  2016-01-11T17:05:39Z
```

IOW, to accomodate trying to get closer to 80-columns I've changed the "PUBLISHED" column to a shorter PUB that just gives the date.

**Comment by nshalman** [comment]
:+1:

**Comment by trentm** [comment]
Added OS ticket for this: https://smartos.org/bugview/OS-5088

**Comment by trentm** [comment]
commit 7990d32
imgadm version 3.6.0

**Comment by nshalman** [comment]
Thank you @trentm!
