### ISSUE TITLE
Asterisk PBX fails to connect to console socket on LX (platform 20160107T182847Z, SDC)

### ISSUE THREAD

**Issue by sigxcpu76** [joyent/smartos-live#540]
I have an issue on connecting to the Asterisk console when running on LX. It simply throws a warning and hangs.

Short version

Forcibly undefining ```SO_PASSCRED``` at compile time fixes the issue. The #undef is done before this line here: https://github.com/asterisk/asterisk/blob/1.8/main/asterisk.c#L1406

# How to reproduce:

- distribution Asterisk
  - create an LX container
  - ```apt-get -y install asterisk```
  - ```asterisk -r```
- compiled Asterisk
  - create an LX container (I use ```ubuntu-14.04```)
  - download latest Asterisk source code (I use 1.8 from http://downloads.asterisk.org/pub/telephony/certified-asterisk/certified-asterisk-1.8.28-current.tar.gz)
  - apt-get build-dep asterisk (to retrieve prereqs)
  - tar xzvf / ./configure / make && make install && make samples
  - start Asterisk with ```asterisk -vvvvvv``` and Ctrl-Z it
  - connect to the console with ```asterisk -r```

# Failures on LX 

- LX, client attempts to connect (segfault and core in gist): https://gist.github.com/sigxcpu76/221c7f312e54dfe3d019

- LX, client attempts to connect, no strace:

```
# asterisk -r
[Jan 12 20:32:45] WARNING[13313]: asterisk.c:1412 listener: Unable to turn on socket credentials passing
Asterisk 1.8.32.3, Copyright (C) 1999 - 2013 Digium, Inc. and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
```

# LX failure server side strace

I couldn't manage to pull a strace server side in LX.

# Working on Ubuntu native (KVM)

- client side: https://gist.github.com/sigxcpu76/b04e48d20ed868608595
- server side: https://gist.github.com/sigxcpu76/7240494345f6360e3a85

**Comment by pfmooney** [comment]
This should be fixed in joyent/illumos-joyent@42ce707864693a4173f27ec86ed55c9df456855a
