### ISSUE TITLE
installer should ignore all USB drives for zpool creation

### ISSUE THREAD

**Issue by CyBeRoni** [joyent/smartos-live#552]
The installer currently ignores only drives set as 'removable', which not all hardware does correctly for USB drives. For instance on my machine:

```
[root@juliet ~]# diskinfo 
TYPE    DISK                    VID      PID              SIZE          RMV SSD
USB     c0t0d0                  SanDisk  Cruzer Fit         14.91 GiB   no  no 
UNKNOWN c1t0d0                  WDC      WD1003FBYZ-010FB0  931.51 GiB   no  no 
UNKNOWN c1t1d0                  WDC      WD1003FBYZ-010FB0  931.51 GiB   no  no 
```

I'm not sure if this is due to the USB drive or my server firmware but apparently it's more common. Probably people wanting to add USB devices to their zones pool should be creating it manually.

**Comment by jclulow** [comment]
I believe this issue was fixed as part of the change for joyent/smartos-live#506.
