### ISSUE TITLE
mdata-get can't retreive nics.*.ips property

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#575]
```bash
[root@test ~]# mdata-get sdc:nics.0.ips
Error getting metadata for key 'sdc:nics.0.ips':
[root@test ~]# mdata-get sdc:nics.0.ips.0
No metadata for 'sdc:nics.0.ips.0'
```
```bash
[root@test ~]# mdata-get sdc:nics.0.ip
dhcp
```

```bash
[root@test ~]# mdata-get sdc:nics | json
[
  {
    "interface": "net0",
    "mac": "00:22:06:10:00:01",
    "vlan_id": 10,
    "nic_tag": "trunk",
    "gateway": "172.16.10.1",
    "gateways": [
      "172.16.10.1"
    ],
    "ip": "dhcp",
    "ips": [
      "dhcp",
      "addrconf"
    ],
    "primary": true
  }
]
```

It would be handy to be able to retrieve just the ips property.

**Comment by bahamat** [comment]
Here's the [metadata data dictionary](http://eng.joyent.com/mdata/datadict.html). Only `sdc:uuid`, `sdc:server_uuid` and `sdc:datacenter_name` are supported.

Other objects are accessible, but are not considered a stable interface at this time. There's no guarantee they will always be available.

The right place to get this info would seem to be `sysinfo`, but it's not currently supported there either. I've filed [OS-5216](https://smartos.org/bugview/OS-5216) for adding multiple addresses and ipv6 support to sysinfo. There's one caveat here, sysinfo looks at the *actual* interfaces and returns the assigned address, not just `dhcp` or `addrconf`, so this might not be quite you're looking for.

**Comment by sjorge** [comment]
I knew about sysinfo but as you said it doesn't show if an interface is dhcp or addrconf. I'm actually already using that to get other data. As it is not one of the supported properties I will close this issue.

**Comment by rmustacc** [comment]
Inside a zone, sysinfo wouldn't be the right place to get this. Instead, we should longer term, consider how to make this information stable inside of a zone via mdata.

**Comment by sjorge** [comment]
Personally I like the mdata + sdc prefix. 
Perhaps add a flag so that list will display them if it is specified. Obviously mdata-put should not work on those.

**Comment by jclulow** [comment]
Note that `sdc:nics` is now a committed and documented interface, as described in [the metadata dictionary](https://github.com/joyent/smartos-live/issues/575).

**Comment by melloc** [comment]
It's also worth pointing out that queries of the form `sdc:nics.0.ips.0` aren't planned to be supported. Instead, you should manipulate the JSON payload, either with the [json(1)](https://smartos.org/man/1/json) command, or something else.
