### ISSUE TITLE
Unable to specify more than 10 IP addresses in config

### ISSUE THREAD

**Issue by anilj** [joyent/smartos-live#576]
I tried to specify about 16+ IP address in the “ips” attribute of the config (joyent_20160204T173339Z) but apparently things seem to get truncated.
`
      "nics": [
        {
          "nic_tag": "external",
          "ip": "102.29.163.170",
          "netmask": "255.255.255.192",
          "gateway": "102.29.163.129",
          "ips": ["102.29.163.170/26", "2001:392:2:60e::14/64", "2001:392:2:60e::1000/64", "2001:392:2:60e::1001/64", "2001:392:2:60e::1002/64", "2001:392:2:60e::1003/64", "2001:392:2:60e::1004/64", "2001:392:2:60e::1005/64", "2001:392:2:60e::1006/64", "2001:392:2:60e::1007/64", "2001:392:2:60e::1008/64", "2001:392:2:60e::1009/64"],
          "primary": true
        }
      ]
`

This ends up creating:
`# ifconfig -a
...
net0:1: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::14/64
net0:2: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1000/64
net0:3: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1001/64
net0:4: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1002/64
net0:5: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1003/64
net0:6: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1004/64
net0:7: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1005/64
net0:8: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1006/64
net0:9: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1007/64
net0:10: flags=40002000841<UP,RUNNING,MULTICAST,IPv6,L3PROTECT> mtu 1500 index 2
        inet6 2001:392:2:60e::1008/6
#`

Also note the “1008/6” in the last one. Definitely looks like truncation here, we see the same thing in /etc/hostname.net0 file.

**Comment by melloc** [comment]
@anilj Sorry I didn't follow up on the mailing list, but I've found the problem, and have been testing a fix. The issue is that both `zonecfg` and `dladm` restrict input length to 256 characters. I've been playing around with bumping these values to make sure it's safe to do so. I'm thinking about setting a limit to 20 IPs per interface. Does that sound like a reasonable number?

**Comment by anilj** [comment]
Why have a limit at all, when the kernel itself doesn't impose this limitation?
We just recently started using IPv6 and one of my clients wanted 16 IP addresses, but given the large free IPv6 address space, I am willing to give out even more to clients, if they ask.

I thought about creating net0, net1, net2 etc., and adding these IPv6 addresses to those but right now I think an IPv4 address (which I am short on) is needed for each of the interfaces that will have IPv6 (static configuration)?

I can imagine an email server needing multiple IP addresses, for outgoing mail; perhaps one IP for customer (dedicated sending IP).

All that said, I am fine with 20 though! This one particular client is already happy with giving them 10 instead of the original 16 IP request. I also doubt I will have other clients requesting this, at least for now.

**Comment by melloc** [comment]
> Why have a limit at all, when the kernel itself doesn't impose this limitation?

The kernel doesn't have a limit on the number of addresses that can be on an interface, but a bunch of other systems and tools end up imposing various limits that create a practical limit. (For example, mac, which provides IP spoofing protection, currently only associates up to 32 IP addresses and subnets with an interface.) These limits can always be raised, but I suspect that 20 should be good enough for now.

I've fixed this issue in joyent/illumos-joyent@868d62f and enforced the limits in a3bb43f, so you should be all set in the next release.
