### ISSUE TITLE
lx branded zones and inet6 weirdness (only CentOS)

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#586]
Images Used:
 - 5917ca96-c888-11e5-8da0-e785a1ad1185
 - b3d02644-d6b2-11e5-bf13-8b034aec4749

I'm using dual stack inet + inet6 at home, using SLAAC (addrconf) for the inet6 configuration.

The following works:
Ubuntu: **dhcp,addrconf** || static4,addrconf + ip_spoofing || dhcp,static6 + ip_spoofing
CentOS: dhcp,addrconf + ip_spoofing || static4,addrconf + ip_spoofing || dhcp,static6 + ip_spoofing

The following does **not** work:
CentOS: dhcp,addrconf

For some reason CentOS needs ip_spoofing set for dhcp,addrconf but Ubuntu does not!?!?

Weirdness all around. 

@melloc ping.

**Comment by melloc** [comment]
@sjorge Is this no longer an issue?

**Comment by sjorge** [comment]
I was going over old issues, I couldn't reproduce this.

It seems ip_spoofing is always needed for the dhcp/addrconf combo.
