### ISSUE TITLE
incorrect man page for dladm

### ISSUE THREAD

**Issue by brian-ewell** [joyent/smartos-live#587]
The man page for dladm describes incorrect parameters for the create-iptun sub-command, under instance base-64-lts 15.4.1, as well as the gz.

Specifically it describes using "-s" and "-d" for "source" and "destination" addresses respectively, whereas the dladm binary is expecting "-a local=&lt;local address&gt;,remote=&lt;remote address&gt;".  

I have not checked any of the other sub-commands under dladm.

**Comment by rmustacc** [comment]
Thanks for filing this. I've filed https://www.illumos.org/issues/6825 with illumos upstream and sent out a fix to [illumos-developer](https://www.listbox.com/member/archive/182179/2016/03/sort/time_rev/page/1/entry/0:373/20160327124653:7FF707EC-F43B-11E5-9504-A80911B29332/). This should make it in there and into a release shortly.

With those open, would it be alright if I closed this?

**Comment by brian-ewell** [comment]
Fine with me!  I just figured someone should know, and didn't want to get lost in the IRC logs.  Thanks!

**Comment by rmustacc** [comment]
Just to let you know this landed in illumos/illumos-gate@b02c665. It should be merged and in the next SmartOS release.
