### ISSUE TITLE
KVM shutdown while rsyncing files

### ISSUE THREAD

**Issue by discostur** [joyent/smartos-live#597]
Hello,

i'm running a KVM Guest on SmartOS (build: 20160219T141818Z) and i try to sync some files via rsync, then suddenly the KVM is shut down by the SmartOS host.

In the /zones/UUID/root/tmp/vm.log i'm getting the following error just before the KVM is stopped:

###
Failed to allocate memory: Resource temporarily unavailable
###

The Core-Dump under /zones/UUID/cores shows me the following:

```
-----------------  lwp# 85 / thread# 85  --------------------
 ffffdf7fff29f0ea _lwp_kill () + a
 ffffdf7fff2338f0 raise (6) + 20
 ffffdf7fff20db78 abort () + 98
 000000000054b172 qemu_oom_check (0) + 49
 000000000054b1ab qemu_memalign (200, 7e0000) + 33
 0000000000508a5d qemu_blockalign (f9dc70, 7e0000) + 4f
 000000000050c485 handle_aiocb_rw (9c51b5570) + c2
 000000000050c770 aio_thread (0) + 166
 ffffdf7fff297b5a _thrp_setup (ffffdf7fff079240) + 8a
 ffffdf7fff297e70 _lwp_start ()
```

The rsync command syncs about 37.000 files with a size of 3.5GB.

The strange thing is: If i lower the RAM of the KVM to for example 24GB the rsync runs without a problem. If i set the RAM to 32GB or 40GB then the KVM is shut down. The Host is a 256GB Machine with more than enough free memory (about 30GB free, ARC is about 97GB).

Also when i throttle the rsync to about 2MB / sec it runs without a problem.

I'm able to reproduce this error on another host system with SmartOS 20160303T144736Z (KVM with 32GB -> shutdown, 24GB runs without a problem).

@rmustacc from Joyent  had an idea what might be happening and how to solve it:

> So based on this thread I think I have an idea of what's happening and
>an idea of how to solve it.

>Originally we didn't have preadv / pwritev in illumos and then when we
>initially added it, the amount of IOVECS we used was variable and QEMU
>didn't really respect IOVEC_MAX. Now, this matters because what QEMU
>appears to be doing here is saying because it has an I/O vector that it
>can't send, it's going to go ahead and try to basically allocate a large
>amount of memory to make it all one contiguous amount that it can send.

>So, in this case I think what we can do is actually release the preadv /
>pwritev restrictions that came into place originally. This has the
>advantage that it should reduce the burden of memory allocation on qemu
>and thus speed up a bit of the I/O processing.

Greets
Kilian

**Comment by rmustacc** [comment]
I've uploaded the following to Manta, though I haven't had a chance to run it myself:

[QEMU Binary](https://us-east.manta.joyent.com/rmustacc/public/preview/qemu-preadv/qemu-system-x86_64)
[Raw Platform](https://us-east.manta.joyent.com/rmustacc/public/preview/qemu-preadv/platform-20160407T175227Z.tgz)
[ISO Image](https://us-east.manta.joyent.com/rmustacc/public/preview/qemu-preadv/platform-20160407T175227Z.iso)
[USB Image](https://us-east.manta.joyent.com/rmustacc/public/preview/qemu-preadv/platform-20160407T175227Z.usb.bz2)

Please give this a shot, thanks!

**Comment by discostur** [comment]
Hi Robert,

i just changed the QEMU Binary with the one you uploaded to manta and did a test-run with it:

ll /smartdc/bin/qemu-system-x86_64*
-r-xr-xr-x   1 root     bin      7619600 Apr  8 16:24 /smartdc/bin/qemu-system-x86_64*
-r-xr-xr-x   1 root     bin      7622568 Mär 21 14:23 /smartdc/bin/qemu-system-x86_64_old*

With the new binary we were NOT able to reproduce the error again. Changeing the binary back to the old one we ran into the same error again ...

Seems that you were right and your fix is working very smooth on our system ;)

**Comment by rmustacc** [comment]
Thanks for your assistance. I've put this back in https://github.com/joyent/illumos-kvm-cmd/commit/1291c76246137e08745f11cc56ca7ee1f38f662c.

**Comment by rmustacc** [comment]
This should be in the next release. I'm going to close this for now, but if there are other follow ups, feel free to open this back up again.
