### ISSUE TITLE
Can't start KVM brand in a HP gen8

### ISSUE THREAD

**Issue by riggy2013** [joyent/smartos-live#602]
I got quite similar issue as 

https://github.com/joyent/smartos-live/issues/456

my system is smartos run on a HP gen8 (E3-1220L_v2, 16G) i am trying to create a windows 10 vm on it.

here is my win10_inst.json:

```
{
    "alias": "win10",
    "brand": "kvm",
    "vcpus": 2,
    "autoboot": false,
    "ram": 2048,
    "resolvers": ["8.8.8.8", "8.8.4.4"],
    "disks": [
    {
        "boot": true,
        "model": "virtio",
        "size": 40960
    }
    ],
    "nics": [
    {
        "nic_tag": "admin",
        "model": "virtio",
        "ip": "dhcp",
        "primary": 1
    }
    ]
}
```

After starting VM, there is nothing in VNC session. When I tried to stop VM, it prints error msg like:

`genunix: [ID 722105 kern.warning] WARNING: ip_Interface_cleanup: cannot open /devices/pseudo/udp6@0:udp6: error 13.`

My start command is:

`vmadm start <UUID> order=cd,once=d cdrom=/virtio-win-0.1-102.iso,ide cdrom=/Win10_1511_1_EnglishInternational_x64.iso,ide`

smartos version is joyent_20160414T0117432.

contents of vm.startvm.log:

```
+ [[ -x /startvm.zone ]]
+ exec /smartdc/bin/qemu-exec /smartdc/bin/qemu-system-x86_64 -m 2048 -name 58af22db-198f-6d4d-c573-e3f6c0711e65 -uuid 58af22db-198f-6d4d-c573-e3f6c0711e65 -cpu qemu64 -smp 2 -drive file=/dev/zvol/rdsk/zones/58af22db-198f-6d4d-c573-e3f6c0711e65-disk0,if=virtio,index=0,media=disk,boot=on -drive file=/virtio-win-0.1.102.iso,if=ide,index=1,media=cdrom -drive file=/Win10_1511_1_EnglishInternational_x64.iso,if=ide,index=2,media=cdrom -boot order=cd,once=d -device virtio-net-pci,mac=f2:71:e1:7b:0f:d9,tx=timer,x-txtimer=200000,x-txburst=128,vlan=0 -net vnic,name=net0,vlan=0,ifname=net0 -smbios 'type=1,manufacturer=Joyent,product=SmartDC HVM,version=7.20160414T011743Z,serial=58af22db-198f-6d4d-c573-e3f6c0711e65,uuid=58af22db-198f-6d4d-c573-e3f6c0711e65,sku=001,family=Virtual Machine' -pidfile /tmp/vm.pid -vga std -chardev socket,id=qmp,path=/tmp/vm.qmp,server,nowait -qmp chardev:qmp -chardev socket,id=serial0,path=/tmp/vm.console,server,nowait -serial chardev:serial0 -chardev socket,id=serial1,path=/tmp/vm.ttyb,server,nowait -serial chardev:serial1 -vnc unix:/tmp/vm.vnc -parallel none -usb -usbdevice tablet -k en-us
/tmp/vm.log.8: No such file or directory
/tmp/vm.log.7: No such file or directory
/tmp/vm.log.6: No such file or directory
/tmp/vm.log.5: No such file or directory
/tmp/vm.log.4: No such file or directory
/tmp/vm.log.3: No such file or directory
/tmp/vm.log.2: No such file or directory
/tmp/vm.log.1: No such file or directory
/tmp/vm.log.0: No such file or directory
/tmp/vm.log: No such file or directory
```

any help? thanks in advance!

**Comment by riggy2013** [comment]
I changed title to "can't start KVM" as I tried w/ an official debian image w/ same kind of error.

The debian image is imported from joyent w/ uuid 2f56d126-20d0-11e5-9e5b-5f3ef6688aba.

Here is my debian.json:

```
{
  "brand": "kvm",
  "alias": "debian",
  "hostname": "debian",
  "resolvers": [
    "8.8.8.8",
    "8.8.4.4"
  ],
  "ram": "2048",
  "vcpus": "1",
  "nics": [
    {
      "nic_tag": "admin",
      "ip": "dhcp",
      "model": "virtio",
      "primary": true
    }
  ],
  "disks": [
    {
      "image_uuid": "2f56d126-20d0-11e5-9e5b-5f3ef6688aba",
      "boot": true,
      "model": "virtio"
    }
  ]
}
```

I changed IP to static but the issue is still same. VNC viewer is blank, the error in vm.startvm.log is same.

On the same system, i can create a joyent brand base-64-lts and a lx brand ubuntu 14.04.

**Comment by riggy2013** [comment]
Please ignore the issue.

It turns out the issue is in VNCViewer for OSX. I changed to OSX built-in screen sharing or TigerVNC, both are good.

Sorry for bothering.

**Comment by mike-pt** [comment]
For windows 10 were you able to move past the install boot logo?

**Comment by riggy2013** [comment]
Hi, Mike,

I have just passed this one yesterday evening. There is a hidden tips in
issue #456 <https://github.com/joyent/smartos-live/issues/456>.

As an aside, on default settings Windows 10 will panic as you enter the
> installer on the latest build. This is completely unsupported by SmartOS
> officially (going by vmadm) but if you run 'vmadm update cpu_type=core2duo'
> or 'vmadm update cpu_type=Nehalem' and start your zone, you should be able
> to get into the installer, once you work out this issue.


good luck!

Thanks,

David

**Comment by mike-pt** [comment]
In my case that was not helping, but it seems it was this specific build of
windows (I was using the media creation tool on my physical win10 box),
however using the latest insider build works just fine.

Thanks

**Comment by riggy2013** [comment]
I used win10 iso downloaded from microsoft website.
