### ISSUE TITLE
IPv4 address or "dhcp" in nics.*.ips is silently mandatory

### ISSUE THREAD

**Issue by lparkes** [joyent/smartos-live#604]
I recently found that if a KVM guest NIC doesn't have "dhcp" in its ips attribute, then QEMU is never asked to provision that NIC to the guest. I assume an explicit IPv4 address will work fine, but I never tested that. 

While assigning an IPv4 address via DHCP is by the most common way of configuring a guest, it isn't the only way and I should have to put a dummy value of "dhcp" in the ips attribute just to get the NIC attached to the guest.

To reproduce this problem, just try adding a new NIC to a KVM guest and include `"ips": [ "addrconf" ]` in the NIC attributes. The necessary command line options for creating the NIC are not passed to QEMU and so the NIC simply never appears for the guest O/S.

To work around the problem use the attribute `"ips": [ "dhcp", "addrconf" ]`instead.

I was not able to find an error messages in any log files that might have explained what is going on which makes this harder to deal with than it should be.

**Comment by lparkes** [comment]
This might be a duplicate of OS-4945. The host in question is running an image of that sort of vintage.

**Comment by melloc** [comment]
Hi @lparkes ,

Are you running on a platform from before 20151224 but after 20150917? If so, then you're most likely running into OS-4945, and I recommend upgrading to a newer platform.

In addition to that, there is [OS-5312](https://smartos.org/bugview/OS-5312), which I haven't dug into too deeply yet, but it doesn't sound like you're trying to use IPv6 w/o IPv4.

**Comment by melloc** [comment]
(Well, maybe you are, since you said that you found this using `"ips": [ "addrconf" ]`, in which case that bug is relevant to you.)

**Comment by lparkes** [comment]
I don't need to run IPv6 without IPv4, although I am open minded enough to try sometimes. I can see that my copy of VM.js predates your fix for OS-4945, so I'm going to close this issue now.
