### ISSUE TITLE
can't ssh root remotely

### ISSUE THREAD

**Issue by riggy2013** [joyent/smartos-live#607]
I can't ssh root from my mac book.

I followed the instructions in

http://veereshkumarn.blogspot.com/2012/09/how-to-enable-ssh-root-login-in-solaris.html

but still fails. No idea why.

> How to enable SSH Root Login In Solaris 11
> 
> 
> Permit SSH Login for Root in Oracle Solaris 11
> 
> 
> 
> Open Terminal window and switch to root user.
> 
> 
> 1. Change the file /etc/ssh/sshd_config PermitRootLogin yes with PermitRootLogin no and save file.
> 
>     vi /etc/ssh/sshd_config  
> 
>   PermitRootLogin yes
> 
> 2. Comment out the “CONSOLE=/dev/console” line in /etc/default/login.
> 
>     vi /etc/default/login
> 
>   #CONSOLE=/dev/console
> 
> 3.Remove “;type=role” from the root entry in /etc/user_attr or use the below command.
> 
>  rolemod -K type=normal root
> 
> 4. Restart the Services.
> 
> #svcadm restart svc:/network/ssh:default

**Comment by rmustacc** [comment]
On 4/21/16 7:14 , riggy2013 wrote:
> I can't ssh root from my mac book.
> 
> I followed the instructions in
> 
> http://veereshkumarn.blogspot.com/2012/09/how-to-enable-ssh-root-login-in-solaris.html

There's a bunch of information that'll be useful here to help us
understand what's going on:

Is this the global zone or the non-global zone?

If a non-global zone, what image are you using?

Are there any errors in the authentication log?

Are you trying to use key-based auth or password based auth?

**Comment by riggy2013** [comment]
@rmustacc thanks for your prompt response.

I got solved the issue. I wrongly ssh to the iLO ip instead of global zone ip. how silly i am!
