### ISSUE TITLE
user-script output in triton.log would be a nice plus

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#617]
On native zones ```tail -f `svcs -L mdata:execute```` get you the output of the user script.
There is no way (that I know of) to get the output in LX zones. It would be nice that it ends up in triton.log

**Comment by chorrell** [comment]
Probably worth opening this as an issue over here:

https://github.com/joyent/sdc-vmtools-lx-brand

The relevant script that executes the user-script: https://github.com/joyent/sdc-vmtools-lx-brand/blob/master/src/lib/smartdc/mdata-execute
