### ISSUE TITLE
[lx branded] pseudo tty doesn't work for regular users?

### ISSUE THREAD

**Issue by derkuci** [joyent/smartos-live#618]
To reproduce the issue, 
1. Create an LX branded zone with the 20160422 smartos + 20160405 centos 7 dataset (ddd996ae-fb57-11e5-adfd-0f38d6e6002e)
2. as root of that branded zone, do "yum install -y screen"
3. as root of that branded zone, create a regular user "useradd -g users testuser"
4. as "testuser" run screen

<pre>
[testuser@9843185f-0b33-41a9-b17b-f5db7b23ed8b ~]$ screen
[screen is terminating]
</pre>

If I install necessary packages in that branded zone for gnome desktop and run a terminal as a regular user, I'll get "grantpt failed" error, can't create a child process, etc.  There are no issues with the superuser "root".

Both seem related to /dev/pts permission and/or pseudo tty?

**Comment by derkuci** [comment]
"screen" works as intended with LX centos-6 20160405 (kernel 2.6.32) and ubuntu-16.04 20160427 (kernel 4.3.0).  So it has to be centos-7 specific, or something incomplete with that dataset?

**Comment by jjelinek** [comment]
I opened OS-5412 to track this issue.

**Comment by derkuci** [comment]
Verified that the 20170119 release contained the fix.  Thanks.
