### ISSUE TITLE
[lx branded] X unable to start on Ubuntu16 due to missing /dev/tty7

### ISSUE THREAD

**Issue by quanah** [joyent/smartos-live#621]
The Ubuntu16 LX image is missing any tty's other than /dev/tty.  It is impossible to create tty0+ as well:

root@13af5671-c693-e2e7-f17a-f45d9421ac3b:~# mknod /dev/tty0 c 4 0
mknod: /dev/tty0: Operation not permitted

This causes X failures when attempting to start.  If we examine Xorg.0.log, we find:

[ 45530.635] (++) using VT number 7

[ 45530.641] (EE) xf86OpenConsole: Cannot open virtual console 7 (No such file or directory)

and then it core dumps

**Comment by rmustacc** [comment]
On 5/5/16 6:22 , Quanah Gibson-Mount wrote:
> The Ubuntu16 LX image is missing any tty's other than /dev/tty.  It is impossible to create tty0+ as well:
> 
> root@13af5671-c693-e2e7-f17a-f45d9421ac3b:~# mknod /dev/tty0 c 4 0
> mknod: /dev/tty0: Operation not permitted
> 
> This causes X failures when attempting to start.  If we examine Xorg.0.log, we find:
> 
> [ 45530.635] (++) using VT number 7
> 
> [ 45530.641] (EE) xf86OpenConsole: Cannot open virtual console 7 (No such file or directory)
> 
> and then it core dumps

So, X is in general going to have issues because there's no frame buffer
available. Have you tried using Xnest?

**Comment by quanah** [comment]
Yes.  Generally, I need to access the gnome desktop over VNC, which requires using lightdm at this point due to Ubuntu issues (i.e., tightvnc won't work).  I modified lightdm to start up Xnest rather than X, but it didn't change the fact things still barf about tty7.

In general, I think SmartOS simple isn't designed to handle what I need to do.

**Comment by quanah** [comment]
Will just close this. ;) My work fixed their VPN so I don't need gnome thank god.
