### ISSUE TITLE
Gigantic MemFree occasionally reported in /proc/meminfo [LX]

### ISSUE THREAD

**Issue by magnayn** [joyent/smartos-live#623]
Jenkins monitors nodes' free resources by reading /proc/meminfo

Occasionally this reports a gigantic value - e.g: 

> MemFree:   18446744073709099244 kB

This causes Jenkins to fail as that's bigger than can fit into a Long (!)

I suspect that isn't really the size of free memory..

**Comment by jjelinek** [comment]
I opened OS-5411 to track this.

**Comment by jjelinek** [comment]
Fixed in commit eb3642a
