### ISSUE TITLE
modload can't load ipmi module if without specifying the full path of ipmi

### ISSUE THREAD

**Issue by FrankYu** [joyent/smartos-live#629]
# uname -r
5.11

Steps: 

1.try to load ipmi module

#modload ipmi
can't load module: No such file or directory

2.try to load ipmi with full path

#modload /usr/kernel/drv/amd64/ipmi 

#modinfo |grep ipmi
227 fffffffff80ba000   2c90 273   1  ipmi (ipmi driver)

**Comment by rmustacc** [comment]
This matches how modload is described to work in [http://illumos.org/man/1m/modload](modload(1M)). Take a look at the manual page to get a better sense of how to invoke it to load the driver.  Note the following from the description:

```
 If  filename does not begin with a slash (/), then the path to
 load  filename is relative to the current directory unless the  -p
 option is specified
```

However, generally speaking, if you have an ipmi device that we detect, then there's no need to ever run modload yourself.
