### ISSUE TITLE
Upgrading lx_ubuntu in smartos

### ISSUE THREAD

**Issue by riggy2013** [joyent/smartos-live#630]
Hi,

How to upgrade my exist lx_ubuntu from 14.04 LTS to 16.04 LTS? just follow Ubuntu upgrade guide?

Sorry, is here the right place to ask support questions on smartos usage?

Thanks,

David

**Comment by chorrell** [comment]
You should be able to follow the Ubuntu guid but it's not something I would recommend. There are probably some systemd things that are not quite supported in lx-brand yet (depending on which SmartOS platform version you are on). If you upgrade, things could break in unexpected ways and you might not be able to roll back to 14.04.

I would recommend trying out the 16.04 image first. I would also strongly recommend taking a snapshot of your current instance if you do decide to do a 14.04 -> 16.04 upgrade.

**Comment by riggy2013** [comment]
@chorrell thanks for response.

it is quite annoying as I have already installed/configured some software packages in this lx_ubuntu 14.04LTS vm. Any better way for the upgrading? What's your recommendation?

Here is my smartos version:

- SmartOS Live Image v0.147+ build: 20160414T011743Z

**Comment by chorrell** [comment]
I don't have any other recommendations aside from my previous advice about trying out a 16.04 VM and taking advantage of snapshots.
