### ISSUE TITLE
Please package Apache Guacamole

### ISSUE THREAD

**Issue by allquixotic** [joyent/smartos-live#632]
Apache Guacamole is an Incubator project (formerly standalone but donated to ASF) licensed under the Apache License 2.0. Its "elevator pitch" is that it enables RDP, VNC, SSH, SFTP, etc. -- basically the most popular graphical and text-based remote desktop / remote administration / file transfer protocols -- to be presented in the web browser.

Guacamole has a JavaScript/HTML/CSS client that is easy to build and just gets downloaded by the user's web browser when they load Guacamole over HTTP(S), and a server side daemon, guacd, written in C.

Guacamole has its own custom wire protocol that is used for communicating between the web browser and the guacd server. The guacd server then translates messages from its native wire protocol into the protocol of the specific backend being used, whether it be SSH, RDP, etc.

The value of supporting Guacamole on SmartOS is that this is a very commonly desired system administration utility on the modern Internet, especially when every other network is so locked-down that you can't get outbound ports on the well-known SSH or RDP ports. Supporting it natively on SmartOS-branded zones avoids the need for administrators to set up an LX branded zone (Ubuntu, for instance, packages Guacamole), or compile it from source on SmartOS.

The build system is autotools and it has several FOSS library dependencies. The entire Guacamole ecosystem is based on FOSS with no proprietary bits.

**Comment by sjorge** [comment]
guacamole works pretty well actually for the clientless quick access.
I never got to compile on SmartOS with all the bells and whistles though (libwebp en pulse being the problem IIRC)

**Comment by allquixotic** [comment]
I see pkgsrc has libwebp-0.5 already, so that should not be an issue any longer.

**Comment by jperkin** [comment]
I've built a package for testing in a base-64 2016Q1 zone.  To install:

```
$ pkg_add https://us-east.manta.joyent.com/pkgsrc/public/tmp/freerdp-1.0.2nb13.tgz
$ pkg_add https://us-east.manta.joyent.com/pkgsrc/public/tmp/guacamole-server-0.9.9.tgz
```

Please let me know whether it works and if any changes are required, and I'll get this in properly for 2016Q2.  Thanks.

**Comment by jperkin** [comment]
Sorry, those URLs should be http:// not https://  I've also uploaded a newer guacamole-server package which enables more features and includes SMF.  Let me know if it works ok (it starts up at least for me).

**Comment by allquixotic** [comment]
Thank you very much, jperkin... I've got it installed and it's up and running, just going to download the client (it's meant to run on a Java application server like Tomcat) and see if the end-to-end connection works... stay tuned... thanks again.

**Comment by sjorge** [comment]
@jperkin seems to work great, perhaps add a note to the file displayed at install on where to grab the web client.

Which features did you enable? freerdp, ssh, telnet? with webp?

**Comment by jperkin** [comment]
I enabled everything except for telnet, mostly because libtelnet isn't in pkgsrc yet, but also because I figured nobody would still be using telnet?  I think the only reason to enable it would be to enable the ssh agent support, as that is disabled when libtelnet isn't available for some reason.

I don't use this app so if those are highly desirable then let me know and I'll take a look at packaging up libtelnet.

**Comment by sjorge** [comment]
Yeah I remembered a few libs not being available when I looked at this a while ago. (Now running it on a RPI2 (slow as hell) to work around that).

I was actually using telnet because a few of my dump network devices do telnet but not ssh. *cough tp-link*

**Comment by jperkin** [comment]
It turns out @mamash already committed a libtelnet package to pkgsrc trunk recently, so I've enabled that feature too.  This is now [committed upstream](http://mail-index.netbsd.org/pkgsrc-changes/2016/06/07/msg141855.html) and will be available in 2016Q2.
