### ISSUE TITLE
SSE4 / AVX not reported in cpuinfo of lx branded zone

### ISSUE THREAD

**Issue by matthiasg** [joyent/smartos-live#647]
I am running an **lx** branded zone on **20160512T071413Z** on an [Intel i7-4770][cpu]. Sadly the lx zone reports no **SSE4.1** support even though the CPU has it. I require SSE4.1 to run https://github.com/yandex/ClickHouse/.

I would assume its just not reported, but I would like to know whether this is supposed to work.

[cpu]: http://ark.intel.com/products/75122/Intel-Core-i7-4770-Processor-8M-Cache-up-to-3_90-GHz

```
root@4b467ba0-3b45-626f-b068-d1bff108ef21:~# cat /proc/cpuinfo

....

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(r) Core(tm) i7-4770 CPU @ 3.40GHz
stepping        : 3
cpu MHz         : 3399.897
cache size      : 0 KB
physical id     : 0
siblings        : 8
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm pni monitor ds_cpl est tm2 cx16 xtpr
```

**Comment by jjelinek** [comment]
It looks like we're simply missing some of the newer feature bits in our lx procfs. I filed OS-5472 for this.

Thanks for reporting it,
Jerry

**Comment by rmustacc** [comment]
On 6/17/16 7:27 , matthiasg wrote:
> I am running an **lx** branded zone on **20160512T071413Z** on an [Intel i7-4770][cpu]. Sadly the lx zone reports no **SSE4.1** support even though the CPU has it. I require SSE4.1 to run https://github.com/yandex/ClickHouse/.
> 
> I would assume its just not reported, but I would like to know whether this is supposed to work.

Yes, they work presuming the system supports it; however, it appears
that we're missing updates for /proc/cpuinfo flags for newer bits. You
can always confirm with /native/usr/bin/isainfo -x.

**Comment by matthiasg** [comment]
Thanks

**Comment by matthiasg** [comment]
@rmustacc  btw .. running `/native/usr/bin/isainfo -x` just returns `/dev/cpu/self/cpuid: No such file or directory`

**Comment by matthiasg** [comment]
I see OS-5472 shows as "Fixed: A fix for this issue is checked into the tree and tested.
(Resolution Date: 2016-07-26T00:27:22.000Z)". Thanks
