### ISSUE TITLE
smartos build with warnings for target packages.i386/*

### ISSUE THREAD

**Issue by elefant90** [joyent/smartos-live#650]
Hi,

I build smartos for a while now, but since 2 weeks, I see theses warnings after running gmake world:

make: Warning: Command failed for target `packages.i386/BRCMbnxe.mog'
Current working directory /root/smartos-live/projects/illumos/usr/src/pkg
make: Warning: Command failed for target `packages.i386/BRCMbnx.mog'
Current working directory /root/smartos-live/projects/illumos/usr/src/pkg
make: Warning: Command failed for target `packages.i386/SUNW0on.mog'
Current working directory /root/smartos-live/projects/illumos/usr/src/pkg
make: Warning: Command failed for target `packages.i386/SUNWacc.mog'
Current working directory /root/smartos-live/projects/illumos/usr/src/pkg
make: Warning: Command failed for target `packages.i386/SUNW1394h.mog'
Current working directory /root/smartos-live/projects/illumos/usr/src/pkg
make: Warning: Command failed for target `packages.i386/SUNWadixp.mog'
....

After these warnings, I can still run gmake iso & co, but my images don't work. SmartOS boots in maintenance mode.

I have also tested the build with the vanilla smartos-live, without my own adjustments, but the results are the same.

Since the only steps that I performed are:

cp sample.configure.smartos configure.smartos
./configure
gmake world

what am I missing?

**Comment by rmustacc** [comment]
Those errors are noise, which is unfortunate. I'd suggest logging in with the default platform password generated for your build and then taking a look at the service logs to get a better sense of what happened.

**Comment by elefant90** [comment]
It helped to know that the errors in the nightly log can be categorized as noise. I tried a vanilla smartos-live build again and it worked. Apparently  I checked the false platform in my first comment. With these info, I looked again in my overlay directory. It seems that I had old lib/svc/method/fs-root, lib/svc/method/mdata-fetch, lib/svc/method/net-physical and lib/svc/method/smartdc-init files, which rendered svc unusable and hence the maintenance mode. With the current version for this files I got a working build.

**Comment by rmustacc** [comment]
We should clean it up such that those don't occur. But basically if it's a build error with nightly, it will exit one and the contents of nightly.log will be quite helpful. If you got past that and the 0-illumos-stamp exists, then it's something else.
