### ISSUE TITLE
src MAC addresses for some non-IP incoming frames being corrupted

### ISSUE THREAD

**Issue by jgc234** [joyent/smartos-live#659]
I've got a perplexing problem that I can't work out.   Some ethernet frames are getting their src MAC addresses corrupted between the global zone and KVM guests..  The frame gets corrupted before it exits into the zone (so I don't believe it's KVM or the guest OS itself).  The corruption is a consistent pattern - the last two octets have been copied from the first two, and the middle two are messed up.   It seems to only happen with non-IP ethernet frames.

Here's a packet captured in the global zone..

```
ETHER:  ----- Ether Header -----
ETHER:  
ETHER:  Packet 2 arrived at 18:48:28.73244
ETHER:  Packet size = 101 bytes
ETHER:  Destination = 62:b3:ae:48:e4:ec, 
ETHER:  Source      = 0:24:14:9a:9a:20, 
ETHER:  VLAN ID     = 21
ETHER:  VLAN Priority = 0
ETHER:  Ethertype = 8863 (PPPoE Discovery)
ETHER:  
PPPoE:  ----- PPP Over Ethernet -----
PPPoE:  
PPPoE:  Version = 1
PPPoE:  Type = 1
PPPoE:  Code = 7 (Active Discovery Offer)
PPPoE:  Session Id = 0
PPPoE:  Length = 77 bytes
```
......

Here's the same packet captured in a debian KVM guest.  Note the Source MAC.

```
ETHER:  ----- Ether Header -----
ETHER:  
ETHER:  Packet 2 arrived at 18:48:27.51911
ETHER:  Packet size = 97 bytes
ETHER:  Destination = 62:b3:ae:48:e4:ec, 
ETHER:  Source      = 0:24:e4:ec:0:24, 
ETHER:  Ethertype = 8863 (PPPoE Discovery)
ETHER:  
PPPoE:  ----- PPP Over Ethernet -----
PPPoE:  
PPPoE:  Version = 1
PPPoE:  Type = 1
PPPoE:  Code = 7 (Active Discovery Offer)
PPPoE:  Session Id = 0
PPPoE:  Length = 77 bytes

```
A closer look at the src MACs:

ETHER:  Source      = 00:24:14:9a:9a:20 (captured in global) 
ETHER:  Source      = 00:24:e4:ec:00:24 (captured in guest)

It's no surprise that when the guest responds to this src mac, not much happens..

The other difference between the packets is the VLAN tag in the global (VLAN 21), and the ethertype, which isn't clearly shown here.

Here's another example..  A broadcast from from a VMware host on the same network (to check the MTU I assume)

```
ETHER:  ----- Ether Header -----
ETHER:  
ETHER:  Packet 10 arrived at 18:48:50.87851
ETHER:  Packet size = 9000 bytes
ETHER:  Destination = ff:ff:ff:ff:ff:ff, (broadcast)
ETHER:  Source      = **0:50:56:53:3b:20**, 
ETHER:  VLAN ID     = 21
ETHER:  VLAN Priority = 0
ETHER:  Ethertype = 8922 (Unknown)
ETHER:  

ETHER:  ----- Ether Header -----
ETHER:  
ETHER:  Packet 10 arrived at 18:48:49.66533
ETHER:  Packet size = 8996 bytes
ETHER:  Destination = ff:ff:ff:ff:ff:ff, (broadcast)
ETHER:  Source      = **0:50:ff:ff:0:50**, 
ETHER:  Ethertype = 8922 (Unknown)
ETHER:  
```

The MAC differences - with the same type of corruption. 
ETHER:  Source      = 00:50:56:53:3b:20 (captured in global)
ETHER:  Source      = 00:50:ff:ff:00:50 (captured in guest)

Digging with dtrace, the corruption seems to occur somewhere in mac_vlan_header_info.. or somewhere in dls_rx_promisc before calling dls_accept_promisc, possibly in DLS_PREPARE_PKT macro.. maybe an erroneous double-removal of the VLAN tag.  My brain hurts trying to understand what happens in this code between mac and dls.

```
              mac`mac_vlan_header_info+0xe4
              dls`dls_rx_promisc+0x63
              mac`mac_promisc_dispatch_one+0x81
              mac`mac_promisc_dispatch+0xb2
              mac`mac_rx_common+0x47
              mac`mac_rx+0xb6
              aggr`aggr_mac_rx+0x2d
              aggr`aggr_recv_path_cb+0x1bf
              aggr`aggr_recv_promisc_cb+0x23
              mac`mac_promisc_dispatch_one+0x81
              mac`mac_promisc_dispatch+0xb2
              mac`mac_rx_common+0x47
              mac`mac_rx+0xb6
              mac`mac_rx_ring+0x2b
              e1000g`e1000g_intr_work+0x21a
              e1000g`e1000g_intr_pciexpress+0xb3
              apix`apix_dispatch_by_vector+0x8c
              apix`apix_dispatch_lowlevel+0x25
              unix`switch_sp_and_call+0x13
```
As you can probably tell from this stack, the global network configuration is an aggr made of Intel e1000 physical NICs, and uses VLANs for vnics, like this:

```
aggr0_aggr=0:1b:21:6c:e:e3,68:5:ca:7:e0:ba,68:5:ca:7:e0:bb
aggr0_mtu=9000
aggr0_lacp_mode=active
trunk_nic=aggr0
```

```
  "Live Image": "20160818T234814Z",
  "System Type": "SunOS",
  "Boot Time": "1472714859",
  "SDC Version": "7.0",
  "Manufacturer": "HP",
  "Product": "ProLiant ML150 Gen9",
```

and the interface for the VM being checked above:

```
    {
      "interface": "net1",
      "mac": "62:b3:ae:48:e4:ec",
      "vlan_id": 21,
      "nic_tag": "trunk",
      "model": "virtio",
      "dhcp_server": true,
      "allow_dhcp_spoofing": true,
      "allow_ip_spoofing": true,
      "allow_mac_spoofing": true,
      "allow_restricted_traffic": true,
      "allow_unfiltered_promisc": false,
      "mtu": 1520
    },

```
I've tried a few different operating systems, and ethernet driver types.. 

Any thoughts or more debug information to collect?

**Comment by melloc** [comment]
nbjoerg in IRC was running into this same issue, also with PPPoE. I started looking into it, but didn't get too far, yet. I'll try setting up a similar situation locally and try to reproduce the problem so that I can debug it once I finish up some other issues.

**Comment by rmustacc** [comment]
@jgc234 can you confirm that this only seems to happen on frames that are coming into the guest? In other words frames transmitted from the guest aren't corrupted?

**Comment by jgc234** [comment]
@rmustacc - outbound frames appear fine.   Only inbound frames are stomped on.

rtr07 = debian on VMware, eth1 on VLAN 21
rtr08 = debian on SMartOS/KVM, eth1 on VLAN 21

I wrote a script to generate fake gratuitous ARP packets with random source MACs for easier testing.

```
(rtr08)[/home/jgc] root# ./packet.py --interface=eth1 --count=2
INFO:__main__:binding to interface eth1
INFO:__main__:sending 2 packets
INFO:__main__:ARP dmac=ff:ff:ff:ff:ff:ff, smac=00:00:49:6f:91:2e, dip=192.168.3.239, sip=192.168.3.239
INFO:__main__:ARP dmac=ff:ff:ff:ff:ff:ff, smac=00:00:49:a6:6e:11, dip=192.168.1.34, sip=192.168.1.34

(rtr07)[/home/jgc] root# tshark -i eth1 -n -f broadcast
Capturing on 'eth1'
  1   0.000000 00:00:49:6f:91:2e -> ff:ff:ff:ff:ff:ff ARP 60 Gratuitous ARP for 192.168.3.239 (Reply)
  2   0.000679 00:00:49:a6:6e:11 -> ff:ff:ff:ff:ff:ff ARP 60 Gratuitous ARP for 192.168.1.34 (Reply)

```
Other way around leads to corruption of MAC.  

```
(rtr07)[/home/jgc] root# ./packet.py --interface=eth1 --count=2
INFO:__main__:binding to interface eth1
INFO:__main__:sending 2 packets
INFO:__main__:ARP dmac=ff:ff:ff:ff:ff:ff, smac=00:00:49:9c:77:8a, dip=192.168.2.198, sip=192.168.2.198
INFO:__main__:ARP dmac=ff:ff:ff:ff:ff:ff, smac=00:00:49:c7:00:ff, dip=192.168.2.173, sip=192.168.2.173

(rtr08)[/home/jgc] root# tshark -i eth1 -n
Capturing on 'eth1'
  1   0.000000 00:00:ff:ff:00:00 -> ff:ff:ff:ff:ff:ff ARP 60 Gratuitous ARP for 192.168.2.198 (Reply)
  2   0.002799 00:00:ff:ff:00:00 -> ff:ff:ff:ff:ff:ff ARP 60 Gratuitous ARP for 192.168.2.173 (Reply)
```

**Comment by jgc234** [comment]
I can see the pattern now.. 4 bytes are copied 4 bytes right, starting at the last 2 bytes of the DST MAC.

```
DST MAC            SRC MAC 
00:01:02:03:04:05, 06:07:08:09:0A:0B
            ^^^^^^^^^^^^
                         vvvvvvvvvvv
00:01:02:03:04:05, 06:07:04:05:06:07 
```

**Comment by jgc234** [comment]
I reckon I've isolated the problem down to  vnd_mac_input() in uts/common/io/vnd/vnd.c. 

The code looks OK to me, except I'm unsure if the bcopy() linked here one that supports overlapping addresses?  (and this is always an overlap).   This is the only way I can see it getting corrupted in such a consistent way.

The code in vnd_mac_input() backs up to the start of the packet and strips the VLAN header out by moving the SRC and DST MACs forward by 4 bytes.

```
                ASSERT(mp->b_rptr >= DB_BASE(mp) + mhip->mhi_hdrsize);
                mp->b_rptr -= mhip->mhi_hdrsize;
                vid = VLAN_ID(mhip->mhi_tci);
                if (mhip->mhi_istagged && vid != VLAN_ID_NONE) {
                        bcopy(mp->b_rptr, mp->b_rptr + 4, 12);
                        mp->b_rptr += 4;
                }

```

The MAC addresses are OK on vnd_mac_input:entry, and broken on vnd_hook:entry, which is the next function boundary I can find.  All tagged packets going through here get corrupted, so I'm not sure why it appears OK to some upstream - do they re-create the header somewhere for other ethertypes.?

Could someone validate the bcopy() overlap support?

Jim..

**Comment by jgc234** [comment]
Here's the somewhat messy dtrace to find the point where the packet gets messed up.  The tracemems show the packet buffer.  There's 2 bytes at the start, then the dst_mac, src_mac, VLAN ethertype (0x8100) followed by the VLAN ID, then the next ethertype.  Most of the variables printed are for checking the logic in vnd_mac_input().

```
#!/usr/sbin/dtrace -s

dtrace:::BEGIN
{

}

fbt:dls:dls_rx_promisc:entry
{
        printf("\n---->\n");
        self->_dls_rx_promisc = 1;
        self->dsp = (dld_str_t*) arg0;
        self->mp = (mblk_t*) arg2;

}

fbt:dls:dls_rx_promisc:return
/self->_dls_rx_promisc == 1/
{
        printf("\n<----\n");
        self->_dls_rx_promisc = 0;
}

fbt:mac:mac_vlan_header_info:entry
/self->_dls_rx_promisc == 1/
{
        self->mip = (mac_impl_t*) arg0;
        self->mhip = (mac_header_info_t*) arg2;

}

fbt:mac:mac_vlan_header_info:return
/self->_dls_rx_promisc == 1/
{
        printf("\n");
        printf("    bindsap=0x%X\n", self->mhip->mhi_bindsap);
        printf("    VLAN=0x%X\n", self->mhip->mhi_tci);
        printf("    tagged=0x%X\n", self->mhip->mhi_istagged);
        printf("    return=%x\n", arg1); 
        printf("    pktsize=%d\n", self->mhip->mhi_pktsize);
        printf("    db_base=%p\n", self->mp->b_datap->db_base);
        printf("    wptr=%p\n", self->mp->b_wptr);
        printf("    rptr=%p\n", self->mp->b_rptr);
        printf("    pdiff=%d\n", self->mp->b_wptr - self->mp->b_rptr);
        printf("    hdrsize=%d\n", self->mhip->mhi_hdrsize);
        printf("    mod=%s\n", self->dsp->ds_dlp->dl_name);
        printf("    zone=0x%x\n", self->dsp->ds_dlp->dl_zid);   
}

fbt:mac::,
fbt:vnd::,
fbt:vnic::,
fbt:dls::
/self->_dls_rx_promisc == 1/
{
        printf("\ndb_base=%p, b_rptr=%p, offset=%d\n", self->mp->b_datap->db_base, self->mp->b_rptr, self->mp->b_rptr - self->mp->b_datap->db_base);
        tracemem(self->mp->b_datap->db_base, 64);
}


fbt:vnd:vnd_mac_input:entry
/self->_dls_rx_promisc == 1/
{
        self->_vnd_mac_input = 1;
        self->vnd_vsp = (vnd_str_t*) arg0;
        self->vnd_mp_chain = (mblk_t*) arg2;
        self->vnd_mhip = (mac_header_info_t*) arg3;
        self->check10 = self->vnd_mp_chain->b_datap->db_base[8]; 
        self->check11 = self->vnd_mp_chain->b_datap->db_base[9]; 
        self->check12 = self->vnd_mp_chain->b_datap->db_base[10]; 
        self->check13 = self->vnd_mp_chain->b_datap->db_base[11]; 
        self->check14 = self->vnd_mp_chain->b_datap->db_base[12]; 
        self->check15 = self->vnd_mp_chain->b_datap->db_base[13]; 

        printf("\n");
        printf("    b_next=%p\n", self->vnd_mp_chain->b_next);
        printf("    vpnd_hooked=%d\n", self->vnd_vsp->vns_nsd->vpnd_hooked);
        printf("    istagged=%d\n", self->vnd_mhip->mhi_istagged);
        printf("    VLAN=0x%X\n", self->vnd_mhip->mhi_tci);
        printf("    hdrsize=%d\n", self->vnd_mhip->mhi_hdrsize);
        printf("    db_base=%p\n", self->vnd_mp_chain->b_datap->db_base);
        printf("    b_rptr=%p\n", self->vnd_mp_chain->b_rptr);
        printf("    ptr_diff=%d\n", self->vnd_mp_chain->b_rptr - self->mp->b_rptr);
        printf("    b_rptr offset=%d\n", self->vnd_mp_chain->b_rptr - self->vnd_mp_chain->b_datap->db_base);
        printf("    b_rptr offset after header adjustment=%d\n", self->vnd_mp_chain->b_rptr - self->vnd_mp_chain->b_datap->db_base - self->vnd_mhip->mhi_hdrsize);
        stack();
}

fbt:vnd:vnd_mac_input:return
/self->_vnd_mac_input == 1/
{
        self->_vnd_mac_input = 0;
}

fbt:::,
vnd:::
/self->_vnd_mac_input == 1/
{
}

fbt:vnd:vnd_hook:entry
/self->_vnd_mac_input == 1/
{
        self->check20 = self->vnd_mp_chain->b_datap->db_base[12]; 
        self->check21 = self->vnd_mp_chain->b_datap->db_base[13]; 
        self->check22 = self->vnd_mp_chain->b_datap->db_base[14]; 
        self->check23 = self->vnd_mp_chain->b_datap->db_base[15]; 
        self->check24 = self->vnd_mp_chain->b_datap->db_base[16]; 
        self->check25 = self->vnd_mp_chain->b_datap->db_base[17]; 

        printf("SRC MAC CHECK %02x:%02x:%02x:%02x:%02x:%02x =? %02x:%02x:%02x:%02x:%02x:%02x\n",
        self->check10, self->check11, self->check12, self->check13, self->check14, self->check15,
        self->check20, self->check21, self->check22, self->check23, self->check24, self->check25);
}

```

**Comment by rmustacc** [comment]
Thanks for tracking it down. I was suspicious that it might be there. I think this was an oversight to use bcopy here and the results are basically undefined. Which is probably why we're lucky enough to have it work 99% of the time, but not 100%. I'll put together a test platform here that properly uses memove(). Sorry for the trouble and thanks again for digging into this.

**Comment by rmustacc** [comment]
@jgc234 I've put together a test platform that should properly use memmove here. I have the raw tgz, an iso, and a usb image. If you have a chance, could you give this a shot and verify it fixes your problem?

platform: https://us-east.manta.joyent.com/rmustacc/public/preview/smartos-live%23659/platform-20160909T150823Z.tgz
iso: https://us-east.manta.joyent.com/rmustacc/public/preview/smartos-live%23659/platform-20160909T150823Z.iso
usb: https://us-east.manta.joyent.com/rmustacc/public/preview/smartos-live%23659/platform-20160909T150823Z.usb.bz2

The diff looks more or less like:

```diff --git a/usr/src/uts/common/io/vnd/vnd.c b/usr/src/uts/common/io/vnd/vnd.c
index 2abb6f9..be28dff 100644
--- a/usr/src/uts/common/io/vnd/vnd.c
+++ b/usr/src/uts/common/io/vnd/vnd.c
@@ -2162,7 +2162,7 @@ vnd_mac_input(vnd_str_t *vsp, mac_resource_t *unused, mblk_t *mp_chain,
                mp->b_rptr -= mhip->mhi_hdrsize;
                vid = VLAN_ID(mhip->mhi_tci);
                if (mhip->mhi_istagged && vid != VLAN_ID_NONE) {
-                       bcopy(mp->b_rptr, mp->b_rptr + 4, 12);
+                       memmove(mp->b_rptr + 4, mp->b_rptr, 12);
                        mp->b_rptr += 4;
                }
```

**Comment by jgc234** [comment]
Brilliant!.. @rmustacc - that did the job.  USB image above tested.  PPPoE came up fine in the VM (debian), along with IPv6, OSPFv2 and OSPFv3 - all working fine so far.

**Comment by rmustacc** [comment]
On 9/9/16 15:05 , jgc234 wrote:
> Brilliant!.. @rmustacc - that did the job.  USB image above tested.  PPPoE came up fine in the VM (debian), along with IPv6, OSPFv2 and OSPFv3 - all working fine so far.

Great thanks. I'll make sure this goes back and we get it in the next
release. Apologies for the long standing bug here.

**Comment by rmustacc** [comment]
Review is available at https://cr.joyent.us/#/c/446. Once this makes it back, I'll close this.

**Comment by jsonn** [comment]
I can confirm that the image fixes the problems I have been seeing.

**Comment by rmustacc** [comment]
Resolved in https://github.com/joyent/illumos-joyent/commit/a3c3b8eebcf93bc73b8baeb392f9124ba5dc8fd4. This will be in the upcoming release. Sorry for the trouble.
