### ISSUE TITLE
illegal memory access in lx_mount

### ISSUE THREAD

**Issue by terinjokes** [joyent/smartos-live#661]
When booting from `joyent_20160901T054050Z` I get the following panic:

```
BAD TRAP: type=e (#pf Page fault) rp=ffffff004049bff0 addr=7fffff3ce2f8 occurred
 in module "unix" due to an illegal access to a user address
```

The stack follows, pointing at lx_mount:

```
ffffff004049c0f0 strcmp+0x1e(7fffff3ce2f8, fffffffff82c1676)
ffffff004049ce70 lx_mount+0x60b(7fffff3ce264, 7fffff3ce2f8, 7fffff3ce264,
1000006, 7fffff3ce860)
ffffff004049cef0 lx_syscall_enter+0x16f()
ffffff004049cf10 sys_syscall+0x145()
```

**Comment by jclulow** [comment]
Bug filed internally as [OS-5646](https://smartos.org/bugview/OS-5646).

**Comment by jjelinek** [comment]
Fixed in commit 12a530b

**Comment by terinjokes** [comment]
@jjelinek Is that in this repo, or another one?

**Comment by rmustacc** [comment]
@terinjokes it's in illumos-joyent. See https://github.com/joyent/illumos-joyent/commit/12a530b543020dda34973ca16b31b66007141141.
