### ISSUE TITLE
Can't update `max user processes`

### ISSUE THREAD

**Issue by medcl** [joyent/smartos-live#663]
It seems it can not be configured, it always stay with 
```
max user processes              (-u) 2000
```
I tried both Centos and Ubuntu

tried modify /etc/security/limits.conf 
```
* - nproc unlimited
```

 and modify /etc/security/limits.d/90-nproc.conf 
```
* - nproc unlimited
```

but no lucky, 
maybe i am doing wrong, hope to have some tips.

**Comment by pfmooney** [comment]
The nproc limit in LX has an upper bound set by the max_lwps configuration for the zone.

**Comment by medcl** [comment]
@pfmooney  Thanks
