### ISSUE TITLE
imgadm import docker container dosen't work "imgadm import: error (ActiveImageNotFound)"

### ISSUE THREAD

**Issue by bouktaibMohssin** [joyent/smartos-live#665]
Hello Community
there is a problem when i want to import an docker image i get this error:

imgadm import: error (ActiveImageNotFound): an active image "name of image" was not found in image sources

i use this version SmartOS (build: 20160906T181054Z) installed on VirtualMachine (VmwarePlayer)

**Comment by rmustacc** [comment]
Hi, can you please share the exact command that you ran and what your imgadm sources has been configured to?

**Comment by bouktaibMohssin** [comment]
[root@smartos ~]# imgadm sources
https://images.joyent.com
https://docker.io
[root@smartos ~]# 

the exact command is this : 

[root@smartos ~]# imgadm import busybox
imgadm import: error (ActiveImageNotFound): an active image "busybox" was not found in image sources

**Comment by bouktaibMohssin** [comment]
hello @rmustacc i'm still having this issue i'v tried it in a physical server , in the smartos discuss i get this response : the plain imgadm tool does not support V2 of the docker repo api atm.
So more and more images do not work anymore. is there a solution or should i wait for an update ?

**Comment by trentm** [comment]
@bouktaibMohssin Unfortunately, imgadm's support for pulling Docker images still only supports the v1 Docker Registry API. That is quite old at this point and many images in Docker Hub (i.e. docker.io) no longer support v1.  Basic support for the v2 registry API is there in the 'node-docker-registry-client' that imgadm is using, but it would still take some coding work on imgadm to get it doing v2 pulls. See https://github.com/joyent/smartos-live/issues/644 for that work (I'm not currently working on it, but eventually plan to get there).   Sorry this isn't there yet.
