### ISSUE TITLE
kstat returns invalid json

### ISSUE THREAD

**Issue by dtrv** [joyent/smartos-live#668]
If your locale setting has a comma as decimal delimiter, kstat -j returns invalid JSON:

```
[root@nessi ~]# LC_ALL=de_DE.UTF-8 kstat -m acpi  -j | json 0 > /dev/null 
json: error: input is not JSON: Bad string at line 7, column 22:
            "snaptime": 1105095,740386387,
    .....................^
[root@nessi ~]#
```

To get correct JSON one have to change the locale:

```
[root@nessi ~]# LC_ALL=C kstat -m acpi  -j | json 0 > /dev/null
[root@nessi ~]#
```

kstat should not honor the locale if it outputs JSON.

**Comment by bahamat** [comment]
This has been filed as [OS-4907](https://smartos.org/bugview/OS-4907).

**Comment by dtrv** [comment]
[OS-4907](https://smartos.org/bugview/OS-4907) does not address the problem with the comma as decimal delimiter.

**Comment by rmustacc** [comment]
Yes, these are different bugs. This isn't OS-4907. @dtrv is right and we should really only use the C locale for this. @jclulow that make sense?

**Comment by rmustacc** [comment]
This was resolved in https://github.com/joyent/illumos-joyent/commit/71eae4d.
