### ISSUE TITLE
hostname.iface and hostname6.iface do not get create correctly

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#672]
While debugging a SaltStack issue I noticed zones create on SmartOS are not correctly setting /etc/hostname.iface and /etc/hostname6.iface.

Here is an example of a dual stack zone:
/etc/hostname.net0

```
172.16.xxx.100/24 up
2001:470:xxx:xx::100/64 up
```

As per the docs (I think this should also/still apply to illumos):
https://docs.oracle.com/cd/E19455-01/806-0916/ipconfig-13/index.html
https://docs.oracle.com/cd/E19455-01/806-0916/ipref-10/index.html

hostname.iface should just hold the ipv4 address and a file hostname6.iface should hold the ipv6 entry.

I had a look around I cannot locate were the files are created (zoneinit??) but /lib/svc/method/net-physical is at least parsing these wrong.

@melloc since you did all the IPv6 in zone lifting, I'm pinging you as you probably know were this stuff gets created.

**Comment by melloc** [comment]
@sjorge SmartOS has a pretty different /lib/svc/method/net-physical than illumos-gate and other distributions do. It expects a slightly different format in `/etc/hostname.*`. The file gets recreated every boot by the `mdata:fetch` service, so that it matches whatever the latest zone configuration is.

**Comment by melloc** [comment]
If you're looking to get information about NICs on SmartOS for SaltStack, you can use `mdata-get`. I've stabilized the format of several metadata keys, and documented them here:

https://eng.joyent.com/mdata/datadict.html

**Comment by sjorge** [comment]
Saltstack actually querries via ifconfig... which hopefully has accurate information :)
I bumped into this while trouble shooting the python issues from illumos#7494 I was looking at all things in play (/etc/inet/hosts, /etc/inet/ipnodes, /etc/nsswitch.conf, /etc/hostname.*, /etc/nodename, ...)

Perhaps there should be a small man mage for the hostname.iface files describing what the format is and that mdata:fetch will set them every boot, etc... ?
