### ISSUE TITLE
Why smartos do not have zonestat command, but has its manual in smartos-live/man/src?

### ISSUE THREAD

**Issue by wudixiaotie** [joyent/smartos-live#680]
Is there a plan that SmartOS will include zonestat on future version?

**Comment by jjelinek** [comment]
The zonestat command depends on the zonestatd daemon, and we have found
that these can induce performance problems with zones running on the
system, so we have chosen not to include either of these components in
SmartOS. We have no plans to include either of these.

Jerry

**Comment by wudixiaotie** [comment]
@jjelinek 👍  very helpful 💯 .
