### ISSUE TITLE
Change VM's cpu type from dedicated-cpu to shared-cpu always need to reboot twice to take effect, Why?

### ISSUE THREAD

**Issue by wudixiaotie** [joyent/smartos-live#684]
Hi, guys!

When I try to modify some CPU config of a VM, I found something odd.

**Change CPU type to dedicated**:
`zonecfg -z <my_zone> "clear cpu-shares; remove capped-cpu; add dedicated-cpu; set ncpus=1; end; verify; commit;"`

**Change cpu type to shared**:
`zonecfg -z <my_zone> "remove dedicated-cpu; set cpu-shares=100; add capped-cpu; set ncpus=1; end; verify; commit;"`

These are two commands I used.

If I type '**Change CPU type to dedicated**' command and reboot the VM, the change takes effect, the CPU is dedicated now.

But then I type '**Change CPU type to shared**' command and reboot the VM, the change does not take effect, the pool of VM's CPU is still there. After I try to reboot VM for another time, the change finally takes effect.

Can anyone help? Any idea?

**Comment by wudixiaotie** [comment]
@melloc Any idea?

**Comment by wudixiaotie** [comment]
My colleague found out there are some other ways to kill the pool instead of reboot twice.
After type '**Change CPU type to shared**' then one of these way can work:
1. stop vm then start it.
2. zoneadm -z <my_zone> shutdown -r

**Comment by bassu** [comment]
To update any of the machine related stuff, e.g. `cpu_cap`, `vcpus`, `ram`, etc, I have to do this:

* stop the vm
* update via vmadm
* start the vm

There aren't that many things which you can live update in SmartOS stack.
See `man vmadm` for more details.

**Comment by wudixiaotie** [comment]
@bassu OK. Thank you for answering me. So this is not an issue.
