### ISSUE TITLE
Periodic crash in speedstep_pstate_transition

### ISSUE THREAD

**Issue by glasspelican** [joyent/smartos-live#686]
I am having a periodic crash running smartos on my lab computer when attempting to read the current power state 
 
`rdmsr+2()  
speedstep_pstate_transition+0x5a(f)  
xc_serv+0x192(0, 0)  
apix_dispatch_by_vector+0x8c(f0)  
apix_dispatch_hilevel+0x15(f0, 0)  
switch_sp_and_call+0x13()  
apix_do_interrupt+0xfe(ffffff001e805ad0, 0)  
_interrupt+0xba()  
i86_mwait+0xd()  
cpu_idle_mwait+0x109()  
idle+0xa7()  
thread_start+8()
`

for whatever reason write_ctrl is not showing up in the stacktrace
when i disassemble rdmsr function it is at the rdmsr instruction 
Panic is of type:  `BAD TRAP: type=d (#gp General protection)`
from the instruction set reference GP exception is only thrown when privilege level is not 0 or the MSR address does not exist/is reserved 

I have[ a small connection of core files](https://cloud.glasspelican.ca/index.php/s/tOho3LXGClQcx8V) with the same stack trace from 
joyent_20160815T190116Z    - vmcore.0
joyent_20160921T151251Z    - vmcore.1
joyent_20161021T132114Z     - vmcore.2
joyent_20161111T210102Z     - vmcore.5
and an possibly related wrmsr from 
joyent_20161021T132114Z    - vmcore.3
joyent_20161111T210102Z     - vmcore.6

vmcore.4 is unrelated

I started using smartos in my lab in april and i know for a fact that i had some early crashed that i didnt keep the core file from, i started keeping the cores when i decided to try to debug what is happening

System
Xeon 1230v2
16G DDR3 1600 clocked at 1333
Motherboard Asus p8h77-m/csm
ecc not supported by motherboard

BIOS
C6 disabled
No setting for  C7

**Comment by rmustacc** [comment]
Thanks for filing this. From taking a look at things, this host does seem to indicate that it supports speedstep (at least, we detected that from the BIOS). Based on that, it's pretty weird that we're seeing this. I wonder if there's some erratum that we need to dig into. I'll have to reach out to Intel and see if there are other cases that might cause this to end up resulting in a pagefault.

**Comment by glasspelican** [comment]
Thanks for your time

Looks like the errata for the e3-12**v2 are nolonger posted on the intel site :( 
but i did find this (processor diagnostic tool)[https://downloadcenter.intel.com/download/19792/Intel-Processor-Diagnostic-Tool], so i'll give that a go later tonight

**Comment by glasspelican** [comment]
traced fault to power supply 3.3v rail going out of spec

**Comment by rmustacc** [comment]
Wow, how'd you end up tracking that down?

**Comment by glasspelican** [comment]
I stumbled across a youtube video by [Mark Furneaux](https://www.youtube.com/watch?v=TBk1o7BYj84) where he tears down a power supply that had been giving him trouble, at about 4:45 he says 

> "If you ever have a system that has all sorts of strange erratic usually kernel level problems that you just can't figure out . . . you should definitely look into the power supply"

 at the same time he is demoing on the same brand of power supply I am(soon to be was) using.
So I got my Motorola HC11 dev kit and programmed it to measure the voltages on the 3.3, 5, and 12 volt rails displaying the highest and lowest values it sees on its display. Next time the system crashes i look at the measurements and the 3.3v rail drooped to 1.7 volts
