### ISSUE TITLE
trivial imgadm(1M) manpage fix  (gz -> gzip)

### ISSUE THREAD

**Issue by OranguTech** [joyent/smartos-live#690]
manpage states:

>  -c <comp>, --compression=<comp>
>                        One of "none", "gz", "bzip2" or "xz" for the compression
>                        to use on the image file, if any. Default is "none".

However attempting to use "gz" yields:

"imgadm create: error (Usage): invalid -c,--compression "gz": must be one of "none", "bzip2", "gzip", "xz""

(Verified that "gzip" is valid/required.)

Will fix and create PR.

**Comment by OranguTech** [comment]
https://cr.joyent.us/4270

**Comment by OranguTech** [comment]
@rmustacc - Pinging here, as it's been a couple weeks. I know this is very minor, but was hoping to get this rolled into a release soon. Difficult to contribute further.

**Comment by jclulow** [comment]
Sorry for the delay -- we've been pretty busy and it's been a vacation week
in the US.  I'll take a look at the CR this evening.

**Comment by jclulow** [comment]
@OranguTech I can't seem to find a CR at the URL you pasted (CR 4270).  Are you sure that's the correct number?  Sorry for the trouble.

**Comment by OranguTech** [comment]
I can't verify the URL, the CR should be correct, it was whatever was the output after pushing it, but I don't have that session anymore. (And apparently my terminal wasn't logging sessions like I thought it was.)

I have never been able to view the CR on Jerrit even after creating it, which I thought was a bit odd, but it's my first time so I assumed it was working as intended... 🤷‍♂️

**Comment by OranguTech** [comment]
I'm still very new to Gerrit, so if there's some commands I could try (re-pushing the CR, doing a fake new patchset?) I can do that too.

**Comment by jclulow** [comment]
@OranguTech Sorry for the delay.  I think something must have happened to your original CR.

I've pushed a new one with the patch from your pull request, and fixed up the commit message to meet our standards: https://cr.joyent.us/#/c/4536/

I've reviewed it, and if it still looks OK to you in Gerrit, I'll integrate it!

Thanks again, and sorry it's been a long road to get here.

**Comment by OranguTech** [comment]
Oh wow, was slightly disappointed this wasn't in the latest SmartOS release, but I didn't realize you were waiting(?) on me. 

I don't have the mental bandwidth to learn more Gerrit interface right now, but it looks okay to me? I mean, it's two bytes in a readme...

**Comment by jclulow** [comment]
Integrated as 17c3a1a1a22c468f3cfe4801e034fa76dbddb9aa.  Thanks!  This will be in the next release.
