### ISSUE TITLE
sm-prepare-image fails on rm -f /.zonedata/metadata.sock

### ISSUE THREAD

**Issue by thegatsbylofiexperience** [joyent/smartos-live#700]
Hi!
I have noticed an issue with sm-prepare-image. When running he script in the latest base-64-lts (16.4.1) zone, I get the following error: "rm: cannot remove '/.zonecontrol/metadata.sock': Read-only file system"

This looks like it could be due to changes in permissions for the /var/zonedata/ directory in [OS-5783](https://github.com/joyent/smartos-live/commit/8074b65033c088e50f9abaed4294358704396d0f) where this directory has been given permissions 755.

I have found that removing the zone's associated metadata.sock file via the global zone before running the script allows the sm-prepare-image script to run without issue.

I am running platform joyent_20170119T014200Z for my server. I believe that this *could* just be a permissions issue.

Thanks for making an awesome operating system :)

**Comment by morphinz** [comment]
Hi. 
I have this problem too but im just closing the field  from "/opt/local/bin/sm-prepare-image" ;  
  
-> # Remove this socket file explicitly:
-> #rm -f /.zonecontrol/metadata.sock
  
I don't know what are consequences but that works for me.

**Comment by matthiasg** [comment]
Did anybody look at this in more detail ?

**Comment by drscream** [comment]
I've the same issue at the latest SmartOS version `joyent_20170803T064301Z`. I'm also not sure if the `metadata.sock` really need to be removed in the `sm-prepare-image` script and if it's more a bug there.
