### ISSUE TITLE
Please, update RSYNC binary

### ISSUE THREAD

**Issue by jcea** [joyent/smartos-live#708]
Current RSYNC binary is version 3.0.6, dated 2009. It is lacking quite a number of useful features of current RSYNC software (version 3.1.2).

Please, upgrade RSYNC version in the live image. Thanks.

**Comment by pfmooney** [comment]
Open as [OS-6009](https://smartos.org/bugview/OS-6009)

**Comment by jcea** [comment]
Bump!. RSYNC security update today, time to upgrade the live image! :-)

**Comment by melloc** [comment]
Resolved in 5a6e22cb76.

**Comment by jcea** [comment]
@melloc, This is supposed to be fixed in May 2017.

I see this in my global zone:

```
[root@xXx ~]# uname -a
SunOS xXx 5.11 joyent_20170916T185915Z i86pc i386 i86pc
[root@xXx ~]# rsync --version
rsync  version 3.0.6  protocol version 30
Copyright (C) 1996-2009 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 32-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, no IPv6, batchfiles, inplace,
    append, ACLs, no xattrs, iconv, no symtimes

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

That is, my platform is 20170916, this was apparently fixed in may, but I am still seeing an ancient "rsync" binary.

:-?

**Comment by melloc** [comment]
@jcea Sorry, the commit date on that commit is in May, but it first appears in 20171221. You'll want something after that to get the newer rsync. There's a separate ticket, that should be fixed by the next release, for adding the patches to fix the December CVEs (see [OS-6532](https://smartos.org/bugview/OS-6532)).

**Comment by OranguTech** [comment]
Don't know how helpful this is, but can confirm:

```
[root@smart1 ~]# uname -a
SunOS smart1 5.11 joyent_20171221T020409Z i86pc i386 i86pc

[root@smart1 ~]# rsync --version
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 32-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, no prealloc

...
```
(
