### ISSUE TITLE
Updating resolvers with `vmadm` does not affect OS zones

### ISSUE THREAD

**Issue by themisanthrope** [joyent/smartos-live#709]
This happens under Triton, but may also happen under vanilla SmartOS.

**Initial Configuration**
```
# vmadm get 97b93049-3622-ce67-f8d7-c8d6fc67caa8 | json resolvers
[
  "10.253.15.2",
  "10.253.15.7"
]
```

**Reconfiguration**
```
# echo '{ "resolvers": [ "10.253.15.2", "10.1.0.133" ] }' | vmadm update 97b93049-3622-ce67-f8d7-c8d6fc67caa8
Successfully updated VM 97b93049-3622-ce67-f8d7-c8d6fc67caa8

# vmadm stop 97b93049-3622-ce67-f8d7-c8d6fc67caa8 && vmadm start 97b93049-3622-ce67-f8d7-c8d6fc67caa8
```

Expected `/etc/resolv.conf` contents;
```
# cat /etc/resolv.conf
nameserver 10.253.15.2
nameserver 10.1.0.133
```

Actual `/etc/resolv.conf` contents;
```
# cat /etc/resolv.conf
nameserver 10.253.15.2
nameserver 10.253.15.7
```

It appears that `/etc/resolv.conf` is static once written, rather than being re-written whenever the DHCP lease details change.

I don't know if this happens under LX, as I've had no call to change one yet, but it doesn't happen under KVM.

**Comment by rmustacc** [comment]
This is expected. The contents of /etc/resolv.conf are not edited due to the `maintain_resolvers` property being false by default. It ends up working for KVM, because KVM is configured by default to use dhcp.

**Comment by themisanthrope** [comment]
My apologies!

I've updated `maintain_resolvers` on all our OS zones.
