### ISSUE TITLE
Support New LSI SAS3224 Card (9305-16i)

### ISSUE THREAD

**Issue by noahmehl** [joyent/smartos-live#720]
As discussed with @rmustacc on IRC, we are having a problem bringing up mpt_sas for the LSI 9305-16i (SAS3224) card.

We did a prtconf -d to get the PCI info:

pci1000,3190 (pciex1000,c4) [LSI Logic / Symbios Logic SAS3224 PCI-Express Fusion-MPT SAS-3]

Tried to bring up the card with update_drv:

`# update_drv -a -i '"pciex1000,c4"' mpt_sas`

Received the following error message in /var/adm/messages:

...WARNING: /pci@0,0/pci8086,6f02@1/pci1000,3190@0 (mpt_sas0):#012#011Number of phys supported by HBA (24) is more than max supported by driver (16).  Driver will not attach.

Found this mailing list thread regarding the mpt_sas driver:

http://thread.gmane.org/gmane.os.illumos.devel/26863

**Comment by rmustacc** [comment]
I put an image together that has both the PCI ID update and the increase in the phy size. I also audited the code to see if any issues would come from increasing it and it doesn't look like it should be too bad from increasing it. https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt32.tgz

**Comment by noahmehl** [comment]
@rmustacc that's amazing! We will test this on Sunday hopefully. Thanks so much for the speedy update!

**Comment by noahmehl** [comment]
@rmustacc I was able get that platform image to boot, however, I get errors on boot and cannot continue.  I'm wondering if we want to remove the PCI ID, so that we can load the driver manually to get good logging output?

<img width="836" alt="screen shot 2017-05-06 at 12 45 27 pm" src="https://cloud.githubusercontent.com/assets/263452/25774255/2df518b8-325a-11e7-9151-ad07990434a8.png">

**Comment by rmustacc** [comment]
Does the system end up in a loop there and never progress? What is it that you have plugged into the system at this time?

**Comment by noahmehl** [comment]
@rmustacc it ends up in a loop, and I wasn't able to get to the console login within 10 minutes.  Also, there were 11 HD's plugged in at the time.

**Comment by noahmehl** [comment]
@rmustacc as discussed on IRC, can you get me a platform image wihtout the PCIe ID so that I can load via CLI and get you the /var/adm/messages?

**Comment by mguegan** [comment]
Hi,
As the 9300-16i (SAS3108) is now replaced by the 9305-i16 it would be nice to have support on this.
(btw I found this thread : http://thread.gmane.org/gmane.os.illumos.devel/26863 )

**Comment by noahmehl** [comment]
@mguegan, @rmustacc did get me a platform image with the ID and the variable updated.  However, that did not work.  We had to switch to the 9300-8i in the interim to complete the project.

**Comment by rmustacc** [comment]
@mguegan If you have the card and are willing to help with the testing and debugging, then happy to work through that.

**Comment by mguegan** [comment]
@rmustacc thanks, I don't have the card yet. I'll ask my supplier if we can get one for testing/debugging purpose. I'll keep you in touch.

**Comment by mguegan** [comment]
@rmustacc FYI next week we will have a server available with this HBA for testing/debugging.

**Comment by mguegan** [comment]
@rmustacc the server is ready with 20170622T212149Z and the HBA plugged in. How can I share the credentials to you for test/debug ?

**Comment by rmustacc** [comment]
Hi @mguegan, thanks for your patience. I've put a few different images here:

```
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170719T171006Z.iso
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170719T171006Z.tgz
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170719T171006Z.usb.bz2
```

Note, you'll need to manually use something like `update_drv -i 'pciex1000,XXXX' mpt_sas`. The XXXX should be replaced with PCI ID of this particular part. So by default, booting this won't attach the HBA. Let me know if there are additional questions.

**Comment by mguegan** [comment]
Thanks @rmustacc ! I have booted on this platform image, and tried to attach the HBA with the driver, but this is not working as expected (I think this is the [same](https://github.com/joyent/smartos-live/issues/720#issuecomment-299652011) error): 
![capture d ecran 2017-07-24 a 11 35 27](https://user-images.githubusercontent.com/4387995/28519112-a8ad0914-706a-11e7-8167-06a798c28366.png)

**Comment by rmustacc** [comment]
@mguegan can you share the full /var/adm/messages output somewhere? I'm starting to put together a D script, but having the full thing rather than a screenshot, might help. Thanks!

**Comment by mguegan** [comment]
@rmustacc that was not so simple (no network, remote desktop, java etc), but here it is :

https://repository.virtua.ch/joyent/messages.20170726.bz2

**Comment by rmustacc** [comment]
I've spent some time trying to decode why that request failed. Unfortunately, it's creating more mysteries than answers. I'm following up with Broadcom to see if we can get some additional documentation. One challenge is that this part seems to be a slightly newer MPI interface version than we have support for, so this may be even more involved than I initially thought as I hadn't realized that the MPI rev had happened. It's only a minor version, so hopefully it won't be too bad.

While at first I thought that the entry at phy 25 was invalid, it seems like that's not the case as we have a valid WWN there. I'm not sure at the moment if additional DTrace will help until I figure out more about what's going on and can better decode this error message.

**Comment by rmustacc** [comment]
Actually, I may have a lead on the problem. We may be incorrectly determining the chain size. Let me see if I can put together an updated image to test. Though that might be Monday at this point.

**Comment by rmustacc** [comment]
I was able to track down another, and probably more egregious problem. Thanks to the messages you provided @mguegan I was able to figure out that this has a newer MPI version than the one that we were using and eventually found the place that wasn't properly detecting that which also would cause us to create the wrong sgl chain entries.

I've put together an updated driver that has both of these pieces. Hopefully this gives us something better.

Images are at:

```
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170730T000734Z.iso
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170730T000734Z.tgz
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170730T000734Z.usb.bz2
```

**Comment by mguegan** [comment]
Thanks for the update @rmustacc ! Sadly I've got a crash when tried to load the driver : 

![vlcsnap-2017-07-31-10h18m32s255](https://user-images.githubusercontent.com/4387995/28768952-e000a05a-75d9-11e7-8b9a-e0b17b58ecfa.png)

**Comment by rmustacc** [comment]
@mguegan Can you give these images a shot please?

```
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170731T161026Z.iso
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170731T161026Z.tgz
https://us-east.manta.joyent.com/rmustacc/public/tmp/mpt_sas/platform-20170731T161026Z.usb.bz2
```

Also, if you only need a single one of these, let me know and I'll switch to uploading only those.

**Comment by mguegan** [comment]
@rmustacc thanks for the update, I only need the `.iso` file. Similar crash again, here is the screenshot : 

![vlcsnap-2017-07-31-21h02m41s671](https://user-images.githubusercontent.com/4387995/28793585-bb706ca2-7633-11e7-923f-b9f8297d4a06.png)

**Comment by rmustacc** [comment]
Due to personal issues, I haven't had the time to figure out the right next steps for this. We'll need to really dig into the memory allocation issues. I may have to see about what it looks like to get a sample unit of this locally given that the time involved has been stretching out due to matters beyond my control, sorry.

**Comment by mguegan** [comment]
Sure. We assumed this was a simple problem, but it seems that's not the case after all. Totally agree with you @rmustacc . Just tell me if I can help you more (by providing you the HBA for example ?).

**Comment by mguegan** [comment]
@rmustacc my supplier told me that he can lend you the HBA. However, it may take some times, but maybe it could help ?

**Comment by rmustacc** [comment]
I think I've sorted out the problems here I'm going through and testing the updated driver right now. If anyone else is interested in testing this, please let me know and I'll provide something. Hopefully we can wrap this up for the subsequent release.

**Comment by mguegan** [comment]
nice @rmustacc ! sure I want to test this, how can I ?

**Comment by mguegan** [comment]
FYI I should receive this HBA this week for testing

**Comment by rmustacc** [comment]
These changes should actually be in the most recent release. Per https://github.com/joyent/illumos-joyent/commit/9094e85. Depending on the card you have, a different PCI ID may need to be added. For the time being since we should have support for this part, I'm going to close this. However, if you find that it doesn't work for whatever reason, please add a note here.

**Comment by mguegan** [comment]
For the record, I've just tested the HBA with great success. Thanks @rmustacc for your efforts !

**Comment by rahulndr** [comment]
Hi All , 
I see the default driver (00.00.00.24) for 9305-16i with latest smartOS release. I not able to find the latest driver for smartOS from Broadcom. The latest driver needs to be custom build on latest smartOS release 
 to support HBA 9305-16i ? Please advise. 

Thanks.
