### ISSUE TITLE
Cannot build smartos-live on restricted networks

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#724]
If the git protocol is not allowed on a network it is impossible to build smartos-live.
I got futher by patching the scripts to fetch the repos via https:// instead of git:// but the rabbit hole is very very deep.

As a lot of submodule are also checked out as via git://

**Comment by sjorge** [comment]
I could provide a patch/gerrit thingy for smartos-live repo but I have not made it to a sucessful build yet :-1: 

So also how would this be tacked properly? Do the sub projects's submodules first and move back up the stack?

**Comment by sjorge** [comment]
After lots of fiddling I got it to compile, will switch to the compile platform soon for testing.

**Comment by sjorge** [comment]
The following files were updated to make it work in a restricted network:

- smartos-live
  -  src/fw/test/node_modules/glob/package.json
  -  src/fw/tools/fwrule/package.json
  -  src/fw/tools/ramsey/node_modules/hogan.js/package.json
  -  src/img/node_modules/bunyan/package.json
  -  src/img/node_modules/cmdln/node_modules/dashdash/package.json
  -  src/img/node_modules/cmdln/package.json
  -  src/img/node_modules/docker-registry-client/node_modules/tough-cookie/package.json
  -  src/img/node_modules/extsprintf/package.json
  -  src/img/node_modules/nodeunit/package.json
  -  src/img/node_modules/once/package.json
  -  src/img/node_modules/progbar/package.json
  -  src/img/node_modules/restify/node_modules/keep-alive-agent/package.json
  -  src/img/node_modules/restify/node_modules/lru-cache/package.json
  -  src/img/node_modules/restify/node_modules/semver/package.json
  -  src/img/node_modules/restify/package.json
  -  src/img/node_modules/rimraf/package.json
  -  src/img/node_modules/sdc-clients/node_modules/async/package.json
  -  src/img/node_modules/sdc-clients/node_modules/lru-cache/package.json
  -  src/img/node_modules/sdc-clients/node_modules/ssh-agent/package.json
  -  src/img/node_modules/sdc-clients/package.json
  -  src/img/node_modules/tabula/package.json
  -  src/img/node_modules/vasync/package.json
  -  src/img/node_modules/verror/package.json
  -  src/img/package.json
  -  src/node-bunyan/package.json
  -  src/node-expat/package.json
  -  src/node-libuuid/package.json
  -   src/node-lockfd/node_modules/v8plus/package.json
  -  src/node-lockfd/package.json
  -  src/node-zonename/node_modules/v8plus/package.json
  -  src/node-zonename/package.json
  -  src/vm/node_modules/nodeunit-plus/node_modules/once/package.json
  -  src/vm/node_modules/nodeunit-plus/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/buffer-equal/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/difflet/node_modules/traverse/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/difflet/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/glob/node_modules/inherits/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/glob/node_modules/minimatch/node_modules/sigmund/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/glob/node_modules/minimatch/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/glob/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/inherits/package.json
  -  src/vm/node_modules/nodeunit/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/burrito/node_modules/uglify-js/package.json
  -  src/vm/node_modules/vasync/node_modules/verror/node_modules/extsprintf/package.json
  -  src/vm/node_modules/vasync/node_modules/verror/package.json
  -  src/vm/node_modules/vasync/package.json
- kvm-cmd
  - submodules
- ur-agent
  - submodules
- mdb_v8
  - submodules
- node-v0.10.26-32
  - submodules
node-v0.10.26-32strap (same repo as above?)
  - submodules

Changes everywhere were simply replacing git://github.com/... with https://github.com/ so the change itself is rather trivial, just the scope is rather big.

**Comment by melloc** [comment]
@sjorge You should be able to ignore the `package.json` files in `smartos-live`, since the build doesn't actually do `npm install` at any point. Those are all just metadata files for the checked-in packages. The ones that do get referenced only get used when scripts like `./fw/tools/bin/rebuild-node-modules` or `./img/tools/update-node-modules.sh` to help update to newer versions.

You may want to also update `sample.configure.smartos` in `smartos-live` to use `https://`.

**Comment by sjorge** [comment]
First build failed on the submodule again, as I was expecting since I only edited sample.configuration.smartos.

Will report back after 2nd try.

**Comment by sjorge** [comment]
@melloc I think I succesfully pushed it to gerrit https://cr.joyent.us/#/c/2031/

**Comment by sjorge** [comment]
@melloc anything else that still needs to be done?

**Comment by sjorge** [comment]
@melloc bump

**Comment by melloc** [comment]
@sjorge Sorry, I missed your ping several weeks ago. The CR looks good to me. Can you update the commit message to be:

```
joyent/smartos-live#724 Cannot build smartos-live on restricted networks
```

**Comment by melloc** [comment]
(Actually, nevermind, I took care of updating it.)

**Comment by sjorge** [comment]
Yay! Nearly there, as there was one submodule that also used plain git!
I'll see if I can get a pr/cr for that one this weekend.

**Comment by melloc** [comment]
@sjorge Thanks for taking care of this! Sorry that it fell off my radar for a while.
