### ISSUE TITLE
tools/tzcheck build failure

### ISSUE THREAD

**Issue by youzhongyang** [joyent/smartos-live#731]
<pre>
[root@batfs9920-yydev2 ~/smartos-live/tools/tzcheck]# gmake
gcc -c -gdwarf-2 -Wall -Wextra -Werror -std=c99 -D__EXTENSIONS__ -D_REENTRANT -I../common -I../../src/common/strings -o strpath.o ../../src/common/strings/strpath.c
In file included from ../../src/common/strings/strpath.c:20:0:
/usr/include/libcmdutils.h:41:2: error: #error "libcmdutils.h can only be used in a largefile compilation environment"
Makefile:58: recipe for target 'strpath.o' failed
gmake: *** [strpath.o] Error 1
</pre>

**Comment by jasonbking** [comment]
I have a fix for this that I'm currently testing.. If you need a fix (it won't be quite the same as the final fix I'm testing), I can provide one.

**Comment by jasonbking** [comment]
I've just pushed the fix, so you should now be able to pull the latest smartos-live and build.
