### ISSUE TITLE
Traffic from different VLAN inside of KVM

### ISSUE THREAD

**Issue by discostur** [joyent/smartos-live#732]
Hi,

i have two tagged vlans on the Switch Port of my SmartOS host, vlan_269 and vlan_270. I configured a KVM with the following network settings:

```
      "vlan_id": 269,
      "allow_ip_spoofing": true,
      "allow_mac_spoofing": true,
      "allow_restricted_traffic": true,
      "allow_unfiltered_promisc": true,
      "ip": "192.168.67.21",
```

Inside the KVM i configured an additional IPv6 address:

```
    inet6 2001:4180:2:269:192:168:67:21/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 2001:4180:2:269:b05e:37ff:fe26:4abf/64 scope global mngtmpaddr dynamic 
       valid_lft 86392sec preferred_lft 14392sec
```

After booting the KVM, the CentOS auto-configured the following IPv6 address:

```
    inet6 2001:4180:2:270:b05e:24fe:ae35:5abf/64 scope global mngtmpaddr dynamic 
       valid_lft 86392sec preferred_lft 14392sec
```

As you can see, this is an auto-generated address from the other vlan (vlan_270). How could that happen? I only attached vlan_269 to the KVM via vmadm configuration...

**Comment by rmustacc** [comment]
This happened because you selected the  "allow_unfiltered_promisc": true. The purpose of that function is to see all traffic from the underlying device. Is there a reason you enable it and disabled every antispoofing option?

**Comment by discostur** [comment]
@rmustacc thanks for your explanation! maybe it would be helpful if you add this to the documentation:

```
       nics.*.allow_unfiltered_promisc:

           With this property set to true, this VM will be able to have multiple
           MAC addresses (eg. running SmartOS with VNICs).  Without this option
           these packets will not be picked up as only those unicast packets
           destined for the VNIC´s MAC will get through.  Warning: do not enable
           this option unless you fully understand the security implications.
```
