### ISSUE TITLE
vmadm should check for VNC port conflicts

### ISSUE THREAD

**Issue by dn0** [joyent/smartos-live#740]
Currently it is possible to configure the same vnc_port for two virtual machines. In this case, the VMs start correctly and there is nothing in the their logs. However, the vmadmd service goes to maintenance state and in its service log there is a `Uncaught Error: listen EADDRINUSE` message.

**Comment by bahamas10** [comment]
(CR is created here https://cr.joyent.us/#/c/2353/)

**Comment by dn0** [comment]
Just noticed that this will probably close #481

**Comment by bahamas10** [comment]
Internal OS ticket created: [OS-6336](https://smartos.org/bugview/OS-6336)

**Comment by bahamas10** [comment]
Integrated! https://github.com/joyent/smartos-live/commit/faa8f38c6c58e2324583d187f8fb89981fba1216

Thanks for the CR - I'll close #481 as a result as well.
