### ISSUE TITLE
How does a dsapid use its own image 

### ISSUE THREAD

**Issue by liufengxin123** [joyent/smartos-live#742]
How do I create my own image server ？
I visited the joyent's blog: http://blog.smartcore.net.au/dsapid-build-smartos-dataset-server 

So I installed that and tried to figure out how I could add my own image there 
But it now looks like a mirrors, which will synchronize joyent's image through the network 
，Of course if I put this thing on a outer net, someone else's mirrors can sync image from me 
， This is not what I want. I want to use it myself and can add my own image，

Is there any way to add my images  ？

1b6c7ae6-894a-11e7-9188-832deb75e989 folder is the image created by myself, other UUID named folders are the images and lists of joyent from the online synchronization, but the image I created can not be displayed on the web 
![333](https://user-images.githubusercontent.com/31117926/29960407-131b4e50-8f2e-11e7-8d16-9cc80631dd6c.png)

![444](https://user-images.githubusercontent.com/31117926/29960442-34780034-8f2e-11e7-935b-cce3d4753cc3.png)

**Comment by bahamat** [comment]
The SmartCore blog and `dsapid` are by @MerlinDMC, not Joyent. You'll need to open this against [merlindmc/dsapid](/merlindmc/dsapid).
