### ISSUE TITLE
System hangs when running PowerDNS in a LX-brand zone ("sendmsg … Invalid argument")

### ISSUE THREAD

**Issue by smokris** [joyent/smartos-live#751]
I've been running PowerDNS in an LX-brand (CentOS 7) zone successfully for about 9 months now.  But starting a few days ago, this zone has been sporadically been bringing down the whole system.

The problem starts with a flood of messages like this in the LX zone's `/var/log/messages`:

    pdns_server: Dec 08 15:19:01 Error sending reply with sendmsg (socket=5, dest=[…]:49117): Invalid argument

(The date and the `dest` IP address and port change, but the rest of the message remains the same.  That error is logged by [this line of code](https://github.com/PowerDNS/pdns/blob/fd95c884bd875e2d374dae217277fd5075acba13/pdns/nameserver.cc#L303).)

At this point, the DNS server is no longer serving responses.  `dmesg` in the LX zone is empty, and `dmesg` in the global zone shows periodic `rsyslogd: -- MARK --`s but no other messages since the system finished booting.

If I `kill` the `pdns_server` process, the whole system hangs (yikes).  After a few minutes, I pull the plug and bring the system back up.  I checked `/var/crash/volatile`, but there's nothing new in it.

Any thoughts on how I can continue debugging this issue?

**Comment by jjelinek** [comment]
We need a panic dump in order to see why the system is hung. If possible, you could force an NMI when the system is in this state and that will generate a dump. If you don't have the ability to force an NMI on your HW, you could use dtrace with the following trick to try to force a dump. Issue the following command in a separate session, immediately before you kill the pdns_server process.
```
dtrace -wn 'tick-1min{ panic(); }'
```
Unless the system is completely non-functional, that will force a dump after 1 minute.

**Comment by smokris** [comment]
Thanks, @jjelinek.  I was able to force a coredump using `dtrace`.  Here's the stack trace:

    # cd /var/crash/volatile
    # savecore -f vmdump.2
    # mdb 2
    Loading modules: [ unix genunix specfs dtrace mac cpu.generic uppc apix scsi_vhci ufs ip hook neti sockfs arp usba mm stmf_sbd stmf zfs sd lofs idm sata crypto random cpc logindmux ptm kvm sppp nsmb smbsrv nfs ipc ]
    > ::status
    debugging crash dump vmcore.2 (64-bit) from …
    operating system: 5.11 joyent_20171207T064532Z (i86pc)
    image uuid: (not set)
    panic message: BAD TRAP: type=e (#pf Page fault) rp=ffffff00466c7990 addr=8 occurred in module "ip" due to a NULL pointer dereference
    dump content: kernel pages only
    > $C
    ffffff00466c7ab0 udp_bind_hash_remove+0x87(ffffff0d5d195800, 0)
    ffffff00466c7ae0 udp_do_close+0x38(ffffff0d5d195500)
    ffffff00466c7b10 udp_close+0x19(ffffff0d5d195500, 83, ffffff0dc2a897d0)
    ffffff00466c7b70 so_close+0x7a(ffffff0d69b292c0, 83, ffffff0dc2a897d0)
    ffffff00466c7ba0 socket_close_internal+0x1b(ffffff0d69b292c0, 83, ffffff0dc2a897d0)
    ffffff00466c7c10 socket_vop_close+0xe8(ffffff0d6a29c980, 83, 1, 0, ffffff0dc2a897d0, 0)
    ffffff00466c7c90 fop_close+0x61(ffffff0d6a29c980, 83, 1, 0, ffffff0dc2a897d0, 0)
    ffffff00466c7cd0 closef+0x5e(ffffff0d8d546508)
    ffffff00466c7d10 closeall+0x67(ffffff0d6b6abfc8)
    ffffff00466c7da0 proc_exit+0x45c(2, f)
    ffffff00466c7dc0 exit+0x15(2, f)
    ffffff00466c7e40 psig+0x38c()
    ffffff00466c7f00 post_syscall+0x805(fffffffffffffffc, 0)
    ffffff00466c7f10 0xfffffffffb800ccc()

**Comment by smokris** [comment]
This backtrace looks very similar to https://www.illumos.org/issues/8653, which is reportedly fixed in SmartOS build 20180118T013028Z.  Tentatively closing as a duplicate of that.
