### ISSUE TITLE
SmartOS not booting from USB 2.0 stick on USB 3.0 port while OpenIndiana Hipster 2017.10 is booting successfully

### ISSUE THREAD

**Issue by zloster** [joyent/smartos-live#761]
The motherboard is Gigabyte [GA-N3150N-D3V](https://www.gigabyte.com/Motherboard/GA-N3150N-D3V-rev-10#ov). The CPU is soldered to the motherboard.
The same system is booting OpenIndiana Hipster 2017.10 successfully and loading the GUI live mode.
With SmartOS there is a restart if non verbose boot is attempted.

SmartOS version is the ~~latest available~~: http://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/smartos.html#20180118T013028Z

Update: I just discovered that I was trying to boot from an USB 3.0 port. SmartOS shows boot menu but can't load. OpenIndiana Hipster 2017.10 is able to boot from the same USB stick and USB 3.0 port even if their documentation is warning against it.

**Comment by rmustacc** [comment]
Could you possibly specify -k on the command line (or use the kmdb option)? This will let us get a sense of what's going wrong and hopefully it'll drop into the kernel debugger when the reset occurs so we can understand what's happening and why.

**Comment by zloster** [comment]
The strange thing is that I'm not able to reproduce the restart currently.
SmartOS boots successfully with the same USB drive from every single USB port on the computer: 2 USB 2.0 on the backplate, 2 USB 3.0 on the backplate and 2 USB 3.0 on the front of the computer case.
The things happened to the flash drive: I've installed a SmartOS on a separate single disk using the flash drive. There are two HDDs in the computer. SmartOS was installed on the smaller/older one.
