### ISSUE TITLE
Kernel panic in nvmeadm get-features on smartos-20180203T031130Z-USB

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#766]
nvme device: intel optane 900p 280G pci-e.

'nvmeadm get-features nvme0' fails after 'Media read-only:    disabled' with '...programming error: invalid field in cmd fff...'. (rmustacc has more detailed stack trace available)

Both the server and the nvme device are brand new, this was first smoke test to see the hardware is working properly.

**Comment by jessegit** [comment]
At least on 20180329T002644Z the panic no longer happens (I did not have a chance to try other releases in-between)

**Comment by rmustacc** [comment]
I believe that this may have been https://www.illumos.org/issues/8808.
