### ISSUE TITLE
DL360 G10: disks not detected

### ISSUE THREAD

**Issue by schmurfy** [joyent/smartos-live#774]
The server is using HP disk (SAS) which are correctly detected at boot with:

```
Controller #00 found at PCI Slot:0, Bus:B1, Dev:00, Func:00
Controller Model: HPE Smart Array P408i-a
Firmware Version: 1.04-0
Memory Size     : 2048 MiB
Serial Number   : XXX     : YYY

Dev#0 - Single    931.51GiB     OK
Dev#1 - Single    931.51GiB     OK
2 Physical Drive(s) Found
```

but when I boot the server on the latest smartos (20180315T080815Z) the setup process stops at the last step saying no disks were found, if I type `diskinfo` there is indeed nothing shown.

I can provide more informations if I know how to gather them.

PS: I tried on linux and the disks are correctly detected as scsi devices

**Comment by schmurfy** [comment]
After loking around more I found this commits: `https://github.com/joyent/smartos-live/commit/171325b8c31dd9694df9872bdbb1ffd22d72825a` which led me to finding and trying `prtconf` on one of the servers which returned device id which may match the HP SmartArray based on the previous commit:

```
System Configuration:  HPE  i86pc
Memory size: 32436 Megabytes
System Peripherals (Software Nodes):

i86pc
    scsi_vhci, instance #0
    ramdisk, instance #0
    pci, instance #0
        [...]
        pci8086,a190, instance #0
            pci103c,22be, instance #0
            pci103c,22be, instance #1
            pci103c,22be, instance #2
            pci103c,22be, instance #3
    [...]
```

Can `pci103c,22be` be the id I am looking for ? I don't really have anything setup to build a smartos release and would prefer to avoid that if not necessary...

I am booting the server using PXE, when the initial setup asks for disks can I manually force smartos to load the cpqary3 driver for the id above ?

**Comment by jclulow** [comment]
I believe you have a new generation of Smart Array branded part, the _Adaptec Smart Storage PQI 12G SAS/PCIe 3_.  We do not yet have a driver for that part, unfortunately.  I would recommend installing an LSI SAS HBA in IT mode instead.

**Comment by schmurfy** [comment]
Do you have any link for one of the card you suggest ?
I don't think installing another storage adapter is an option with this server sadly...
I really prefer running SmartOS on this but I guess I will have to look at other options.

**Comment by ahjohannessen** [comment]
Any news on driver support for SmartArray in DL360 Gen10?

**Comment by rmustacc** [comment]
On 12/4/18 10:45 , Alex Henning Johannessen wrote:
> Any news on driver support for SmartArray in DL360 Gen10?
> 

Unfortunately, it is not something that we are currently working on.

**Comment by ahjohannessen** [comment]
@rmustacc That is very unfortunate. What is required to get support for that smart arrary?

**Comment by rmustacc** [comment]
On 12/6/18 3:06 , Alex Henning Johannessen wrote:
> @rmustacc That is very unfortunate. What is required to get support for that smart arrary?
> 

The new generation of SmartArray parts requires a new device driver to
be written. So we would need the specifications (not sure if we have
them) and units, assuming we had the people available to write the driver.

**Comment by ahjohannessen** [comment]
@rmustacc I see, thanks.

**Comment by andy-js** [comment]
The driver for [Solaris 11](https://storage.microsemi.com/en-us/downloads/unix/sun_solaris/productid=asr-3154-8i&dn=microsemi+adaptec+smartraid+3154-8i.php) sort of works.  You will need to add your own implementation of [bioaligned](https://docs.oracle.com/cd/E88353_01/html/E37855/bioaligned-9f.html) but it's easy enough.
