### ISSUE TITLE
i40e driver does not enable 100M ethernet with X722 + X557 on 20180329T002644Z

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#776]
On smartos-20180329T002644Z:
```
# dladm show-linkprop i40e0
LINK         PROPETY        PERM VALUE          DEFAULT        POSSIBLE
...
i40e0        adv_100fdx_cap  r-   0              0              1,0 
i40e0        en_100fdx_cap   r-   0              0              1,0 
...
```

The datasheet lists 100BASE-TX as supported; https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/x557-at-at2-at4-10gbe-phy-datasheet.pdf

**Comment by rmustacc** [comment]
We'll have to figure out why the hardware doesn't enable it by default as we're using the default set of hardware enablings here.

**Comment by rmustacc** [comment]
Can you share the output of: `mdb -ke 'i40e_glist::walk list | ::print i40e_t i40e_phy'`

**Comment by jessegit** [comment]
`i40e_phy = {
    i40e_phy.phy_type = 0xc000a
    i40e_phy.link_speed = 0xc
    i40e_phy.abilities = 0x17
    i40e_phy.eee_capability = 0
    i40e_phy.eeer_val = 0x11
    i40e_phy.d3_lpan = 0
    i40e_phy.phy_type_ext = 0
    i40e_phy.mod_type_ext = 0
    i40e_phy.ext_comp_code = 0
    i40e_phy.phy_id = [ 0x42, 0x2, 0x54, 0x1 ]
    i40e_phy.module_type = [ 0, 0, 0 ]
    i40e_phy.qualified_module_count = 0
    i40e_phy.qualified_module = [
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
    ]
}
i40e_phy = {
    i40e_phy.phy_type = 0xc000a
    i40e_phy.link_speed = 0xc
    i40e_phy.abilities = 0x17
    i40e_phy.eee_capability = 0
    i40e_phy.eeer_val = 0xe
    i40e_phy.d3_lpan = 0
    i40e_phy.phy_type_ext = 0
    i40e_phy.mod_type_ext = 0
    i40e_phy.ext_comp_code = 0
    i40e_phy.phy_id = [ 0x42, 0x2, 0x54, 0x1 ]
    i40e_phy.module_type = [ 0, 0, 0 ]
    i40e_phy.qualified_module_count = 0
    i40e_phy.qualified_module = [
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
        {
            oui = [ 0, 0, 0 ]
            reserved1 = 0
            part_number = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
            revision = [ 0, 0, 0, 0 ]
            reserved2 = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
        },
    ]
}
`

**Comment by rmustacc** [comment]
Unfortunately based on the phy type bitfield, there is no support for 100BASE-TX. And for the X722, it's actually specifically reserved. The X722 controller says it doesn't support operating at that speed. So unfortunately, it looks like this is expected.
