### ISSUE TITLE
system/manifest-import borken on DEBUG builds

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#783]
On debug builds this (svc:/system/manifest-import:default) service is broken.
Due to that the dependant service coreadm (svc:/system/coreadm:default) also does not start.

Running the start script from console gives the same error message as in the logs.

```
[root@carbon /var/svc/log]# ksh -x /lib/svc/method/manifest-import
+ [ -f /lib/svc/share/smf_include.sh ]
+ . /lib/svc/share/smf_include.sh
+ SMF_EXIT_OK=0
+ SMF_EXIT_NODAEMON=94
+ SMF_EXIT_ERR_FATAL=95
+ SMF_EXIT_ERR_CONFIG=96
+ SMF_EXIT_MON_DEGRADE=97
+ SMF_EXIT_MON_OFFLINE=98
+ SMF_EXIT_ERR_NOSMF=99
+ SMF_EXIT_ERR_PERM=100
+ activity=false
+ EMI_SERVICE=svc:/system/early-manifest-import:default
+ PROFILE_DIR_SITE=/etc/svc/profile/site
+ X=''
+ ALT_REPOSITORY=''
+ ALT_MFST_DIR=''
+ early=false
+ [ '' == svc:/system/early-manifest-import:default ]
+ getopts nd:f: opt
+ [ -n '' -a -z '' ]
+ [ -n '' -a -z '' ]
+ [ false = false ]
+ deathrow=/etc/svc/deathrow
+ [ -s /etc/svc/deathrow ]
+ SVCCFG_CHECKHASH=1
+ export SVCCFG_CHECKHASH
+ [ false = false ]
+ [ -z '' ]
+ /usr/bin/grep '^ar_svc_[^/]*/md5sum opaque '
+ 1> /dev/null
+ /usr/bin/svcprop smf/manifest
+ 2> /dev/null
+ [ -n '' -a -n '' ]
+ [ false = true ]
+ import_manifests /lib/svc/manifest true
+ import_manifests /var/svc/manifest true
+ [ -d /opt/custom/smf ]
+ import_manifests /opt/custom/smf true
+ apply_profile
/etc/svc system profiles not found: upgrade system profiles
+ apply_site_profile /etc/svc/profile
+ handle_upgrade
+ apply_site_profile /var/svc/profile
+ touch /etc/svc/smf_rwtest.202217
+ 1> /dev/null 2>& 1
+ [ 0 -eq 0 ]
+ rm -f /etc/svc/smf_rwtest.202217
+ /usr/sbin/svcadm _smf_repository_switch perm
svcadm: failed to switch repository: File operation error: (see console)
+ echo 'Repository switch back operation failed, \c'
Repository switch back operation failed, + echo 'please check the system log for the'
please check the system log for the
+ echo 'possible fatal error messages.'
possible fatal error messages.
+ exit 95
```

This is printed on the console mentioned
```
svc.configd: Fatal error: Backend copy failed: opening /etc/svc/volatile/fast_repository.db: No such file or directory
svc.configd: Fatal error: Backend copy failed: remove /etc/svc/volatile/fast_repository.db: No such file or directory
```

Not really sure how to fix this.

**Comment by mgerdts** [comment]
On Sun, May 27, 2018 at 3:38 AM, Jorge Schrauwen <notifications@github.com>
wrote:

> On debug builds this (svc:/system/manifest-import:default) service is
> broken.
> Due to that the dependant service coreadm (svc:/system/coreadm:default)
> also does not start.
>
> <snip>

> This is printed on the console mentioned
>
> svc.configd: Fatal error: Backend copy failed: opening /etc/svc/volatile/fast_repository.db: No such file or directory
> svc.configd: Fatal error: Backend copy failed: remove /etc/svc/volatile/fast_repository.db: No such file or directory
>
> Not really sure how to fix this.
>

Before this you will see that / filled up.  The root ramdisk needs to be
larger for debug builds.  See OS-6345 and OS-6983.  The fix for the
previous time we had to monkey with this is at
https://github.com/joyent/smartos-live/commit/c336ed2 .

**Comment by sjorge** [comment]
I'll try this tonight or tomorrow, if the error is gone I will open a cr for this.

**Comment by jlevon** [comment]
I filed OS-6968 recently on this.

**Comment by sjorge** [comment]
@jlevon my build is just finish so I am going to reboot. Do you want to have it resized only for DEBUG or just in general? I can do either of those. I'll get a cr in this week for this.

**Comment by jlevon** [comment]
@jjelinek expressed a preference to bump it for all cases. Thanks!

**Comment by sjorge** [comment]
@jlevon Done https://cr.joyent.us/#/c/4020
