### ISSUE TITLE
Unable to specify bootrom via vmadm for bhyve

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#784]
bhyve's zone init will use a bootrom configure via zonecfg. Currently this cannot be done via vmadm.

- [x] specify a bootrom (as path)
- [ ] ~~optionally specify BIOS and UEFI as a string to automatically select the bundled CSM or UEFI roms. (Currently one CSM rom is shipped)~~

I'd be willing to implement this my self, as I now have a rough idea how to do it. Any objections to me starting with the first items on the list?

**Comment by mgerdts** [comment]
I'm supportive of you taking on the first one.  I've opened OS-6984 for this.

**Comment by sjorge** [comment]
I'll give it a whack this weekend, the 2nd item also does not fit into RFD 121 anyway after rereading that one.

**Comment by sjorge** [comment]
Done, it was surprisingly easy https://cr.joyent.us/#/c/4118

**Comment by sjorge** [comment]
Closing this as this is now fixed, the 2nd item was not in line with RFD 121

**Comment by sjorge** [comment]
I did the 2nd part as well in June, just now submitted as https://cr.joyent.us/#/c/4664 given a ticket in jira popped up to implement this. The work was already mostly done. I just changed upper case BIOS/UEFI to lowercase.
