### ISSUE TITLE
"Double fault" panic on boot with 20180524T002819Z

### ISSUE THREAD

**Issue by smokris** [joyent/smartos-live#785]
On one of my systems (which has successfully been running SmartOS for a few years), the latest SmartOS release panics on boot, then immediately reboots.

   - 20180426T014228Z — OK
   - 20180505T015357Z — OK
   - 20180510T153535Z — OK
   - 20180524T002819Z — `BAD TRAP: type=8 (#df Double fault) rp=fffffffffbc13f10 addr=0`

Here are the symbols in the stack trace:

    unix:die
    unix:trap
    unix:_patch_xrstorq_rbx
    unix:sbmap
    unix:getblock
    unix:bufsread
    unix:BRD_READ
    unix:kobj_boot_read
    unix:kobj_read
    unix:kobj_read_file
    unix:kobj_load_module
    genunix:mod_load
    genunix:mod_hold_installed_mod
    genunix:modrload
    genunix:modload
    unix:impl_bus_initialprobe
    unix:impl_setup_ddi
    genunix:create_devinfo_tree
    genunix:setup_ddi
    unix:startup_modules
    unix:startup
    genunix:main
    unix:_locore_start

And screenshots as it quickly scrolled by:

![widget-panic2-0](https://user-images.githubusercontent.com/190164/40674901-1ac8b4fe-6344-11e8-84a4-1f58ab165660.jpg)
![widget-panic2-1](https://user-images.githubusercontent.com/190164/40674914-2906374e-6344-11e8-8bcc-03378e62d07e.jpg)
![widget-panic2-2](https://user-images.githubusercontent.com/190164/40674919-2dcdfba4-6344-11e8-8d0f-c5cc09f057d7.jpg)

Any thoughts on how I can continue debugging this issue?  (I tried booting into kmdb, but I couldn't get the keyboard to respond.)

**Comment by mgerdts** [comment]
This is also known as OS-6985

https://smartos.org/bugview/OS-6985

**Comment by n-connect** [comment]
Same issue, 20180510T153535Z boots, but 20180524T002819Z fails with: BAD TRAP: type=8 (#df Double fault) rp=fffffffffbc13f10 addr=0 .

PLATFORM: ProLiant-MicroServer-Gen8.

What's the way to debug this?
<img width="1280" alt="bad trap double fault" src="https://user-images.githubusercontent.com/25623619/40871285-1a80bf58-6639-11e8-8070-2472a6f69ba5.png">

**Comment by tgerczei** [comment]
I have a very similar problem: 20180510T153535Z works whereas 20180524T002819Z doesn't as the box reboots immediately as soon as the kernel banner is displayed - same holds true with -kd supplied; the system fails to enter the debugger following the crash, simply restarts instead. The system is an HP N36L Microserver. That said, the message I get is slightly different:

![booboo](https://user-images.githubusercontent.com/6317973/40883643-ac2cac7c-6702-11e8-84f7-82ace4039b6e.jpg)

**Comment by skippie81** [comment]
Hi,
Same issue here.
System is a Supermicro X8DT3 with Intel(R) Xeon(R) CPU E5620

Not having issue on other hardware configuration (different cpu, memory, ...)

If more info needed, ore some dumps can help finding the issue. The system can be rebooted 20180524T002819Z any time (not a production system). So just give me some info what data to collect if needed.

**Comment by skippie81** [comment]
Hi
I made some screen captures while booting version 20180524T002819Z. Hope it can be of some help.

<img width="745" alt="screen shot 2018-06-05 at 21 44 49" src="https://user-images.githubusercontent.com/31068429/40999082-1cf91cb6-690a-11e8-98d7-0f8c8559a925.png">

**Comment by skippie81** [comment]
Hi,

Just tested new version: 20180607T005809Z
This newest build boots without any problems.

**Comment by smokris** [comment]
> Just tested new version: 20180607T005809Z This build boots without any problems.

Yes, same here.

**Comment by tgerczei** [comment]
I confirm I could boot 20180607T005809Z.
