### ISSUE TITLE
Sysinfo get_bhyve_compatibility() does not evaluate properly. 

### ISSUE THREAD

**Issue by dustyhair** [joyent/smartos-live#791]
function get_bhyve_capability()
{
    Bhyve_Capable="false"
    Bhyve_Max_Vcpus="0"

    if [[ -x /usr/lib/brand/bhyve/bhhwcompat ]]; then
        if /usr/lib/brand/bhyve/bhhwcompat; then
            Bhyve_Capable="true"
            vcpus=$(/usr/lib/brand/bhyve/bhhwcompat -c | /usr/bin/grep "^[0-9]*$")
            if [[ -n ${vcpus} ]]; then
                Bhyve_Max_Vcpus=${vcpus}
            fi
        fi
    fi
}

There seems to be an error in the second if statement. 
 if /usr/lib/brand/bhyve/bhhwcompat; then

Should probably be

 if [ /usr/lib/brand/bhyve/bhhwcompat ]; then

**Comment by sjorge** [comment]
What kind of error do you get? That 2nd if does look fine to me though.

The if block is only entered if the executing of /usr/lib/brand/bhyve/bhhwcompat exists with 0.
It's a cleaner version of
```bash
/usr/lib/brand/bhyve/bhhwcompat
if [ $? -eq 0 ]; then
  echo "we have bhyve compatibility"
fi
```

**Comment by dustyhair** [comment]
If i run sysinfo unmodified i get  Bhyve Capable = false  
when I run /usr/lib/brand/bhyve/bhhwcompat manually it outputs nothing so I assume it returns fine. 
with the -c i get 32

**Comment by sjorge** [comment]
What do yo uget when you run '/usr/lib/brand/bhyve/bhhwcompat ; echo $?'

**Comment by dustyhair** [comment]
Ok, -v showed my issue. Though I do not understand what it means.
 
processor does not support desired unrestricted guest controls??

**Comment by dustyhair** [comment]
Is there an easy way to see if EPT is supported? I thought I had KVM working before previously but it has been a while since I looked at it.

**Comment by dustyhair** [comment]
Thanks for your help you I guess The issue can be closed since the original issue appears to be working as it should.
