### ISSUE TITLE
Windows 10 asserts when accesing a vioblk device

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#797]
While playing around and installing windows 10 on bhyve I manage to get it to assert reliably with:
```
Assertion failed: n >= 2 && n <= BLOCKIF_IOV_MAX + 2, file pci_virtio_block.c, line 239
```

Using the latest virtio-win.iso from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso

This is both with lpc at slot 1 or slot 31, I am using the UEFI firmware image provided by @mgerdts.
To install I have one virtioblk disk attached and 2 ahci-cd's (virtio-win.iso + windows10.iso [boot]). I can load the storage driver from the driver CD just fine but on the first write to the vioblk device I hit the assert.

I will retry with virtio-win-0.1.118 as recommende by the FreeBSD people and report back on that also.

**Comment by sjorge** [comment]
On a side note, with lpc on slot 1 it still works but looks like the output on the serial console is messed up... but since I am installing using VNC this is not a problem.

**Comment by sjorge** [comment]
This is fixed upstream. https://reviews.freebsd.org/D10581

**Comment by plitc** [comment]
same on Windows 2016 Server

I was just trying to install windows 2016 in uefi mode, after loading the virtio drivers and trying to format the hard drive, bhyve crashed

version_windows=Win2016.14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_DE-DE.ISO
version_virtio=virtio-win-0.1.139.iso

Bhyve:

``[root@it-labor-smartos ~]# pgrep bhyve``
``6714``
``[root@it-labor-smartos ~]# pargs 6714``
``6714:   bhyve -H -U 7d16df63-50f7-432f-8cfe-946bf6d23425 -B 1,manufacturer=Joyent,produ``
``argv[0]: bhyve``
``argv[1]: -H``
``argv[2]: -U``
``argv[3]: 7d16df63-50f7-432f-8cfe-946bf6d23425``
``argv[4]: -B``
``argv[5]: 1,manufacturer=Joyent,product=SmartDC`` ``HVM,version=7.20180824T100914Z,serial=7d16df63-50f7-432f-8cfe-946bf6d23425,sku=001,family=Virtual Machine``
``argv[6]: -s``
``argv[7]: 1,lpc``
``argv[8]: -l``
``argv[9]: bootrom,/usr/share/bhyve/uefi-rom.bin``
``argv[10]: -l``
``argv[11]: com1,/dev/zconsole``
``argv[12]: -l``
``argv[13]: com2,socket,/tmp/vm.ttyb``
``argv[14]: -c``
``argv[15]: 2``
``argv[16]: -m``
``argv[17]: 2048``
``argv[18]: -s``
``argv[19]: 4:0,virtio-blk,/dev/zvol/rdsk/zones/7d16df63-50f7-432f-8cfe-946bf6d23425/disk0``
``argv[20]: -s``
``argv[21]: 3:0,ahci-cd,/Win20126.14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_DE-DE.ISO``
``argv[22]: -s``
``argv[23]: 2:0,ahci-cd,/virtio-win-0.1.139.iso``
``argv[24]: -s``
``argv[25]: 5:0,virtio-net-viona,net0``
``argv[26]: -s``
``argv[27]: 30:0,fbuf,vga=off,unix=/tmp/vm.vnc``
``argv[28]: -s``
``argv[29]: 30:1,xhci,tablet``
``argv[30]: SYSbhyve-35``
``[root@it-labor-smartos ~]# vmadm stop 7d16df63-50f7-432f-8cfe-946bf6d23425``

Bhyve Crash:

``[root@it-labor-smartos /zones/7d16df63-50f7-432f-8cfe-946bf6d23425/cores]# pstack core.bhyve.7524``
``core 'core.bhyve.7524' of 7524: bhyve -H -U 7d16df63-50f7-432f-8cfe-946bf6d23425 -B 1,manufacturer=Joy``
``-----------------  lwp# 1 / thread# 1  --------------------``
`` fffffc7fef2b618a _portfs () + a``
`` 0000000000423ec8 mevent_dispatch () + 78``
`` 000000000041d70f main (1f, fffffc7fffdffaf8) + 53f``
`` 0000000000418783 _start_crt () + 83``
`` 00000000004186e8 _start () + 18``
``-----------------  lwp# 2 / thread# 2  --------------------``

``-----------------  lwp# 33 / thread# 33  --------------------``
`` fffffc7fef2b6f6a _lwp_kill () + a``
`` fffffc7fef248f40 raise (6) + 20``
`` fffffc7fef221578 abort () + 98``
`` fffffc7fef22191a ???????? ()``
`` 0000000000433ddc pci_vtblk_proc (68a690, 68a6e0) + 37c``
`` 0000000000433e41 pci_vtblk_notify (68a690, 68a6e0) + 51``
`` 00000000004452c4 vi_pci_write (66ffe0, 1, 6895e0, 0, 10, 2, 0) + 2d4``
`` 000000000042c7ad pci_emul_io_handler (66ffe0, 1, 0, 2010, 2, fffffc7fe9001e3c, 6895e0) + cd``
`` 00000000004220de emulate_inout (66ffe0, 1, 4651c8, 0) + 3be``
`` 000000000041c584 vmexit_inout (66ffe0, 4651c8, fffffc7fe9001efc) + 54``
`` 000000000041ce1f vm_loop (66ffe0, 1, 0) + cf``
`` 000000000041c356 fbsdrun_start_thread (6694d8) + 56``
`` fffffc7fef2af9ba _thrp_setup (fffffc7feeeeea40) + 8a``
`` fffffc7fef2afcd0 _lwp_start ()``
``[root@it-labor-smartos /zones/7d16df63-50f7-432f-8cfe-946bf6d23425/cores]#``

**Comment by sjorge** [comment]
There is now a related CR/4770

**Comment by GernotS** [comment]
I am confident  this issue can be closed.
