### ISSUE TITLE
Guest initiated shutdown does not disable autoboot for bhyve

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#798]
She starting a bhyve guest using ```vmadm start``` autoboot gets set to true, when stopping it with ```vmadm stop``` autoboot gets set to false.

When issuing a poweroff/shutdown/halt from inside the guest will leave the zone in the 'stopped' state but autoboot will still be set to true.

This results in a bunch of bhyve guests that were cleanly shutdown from inside the guest to autoboot when the CN rebooted. Which is not the expected behavior.

**Comment by mgerdts** [comment]
Opened a Jira ticket: https://smartos.org/bugview/OS-7135

**Comment by sjorge** [comment]
I’ll close this as there is now a jira for this.
