### ISSUE TITLE
Adding a disk to a bhyve vm destroys disk0

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#804]
While testing things on bhyve + windows I wanted to add a small 2nd disk to test vioblk change by pmooney.

```
[root@boron ~]# echo '{"add_disks": [ {"size": 1, "model": "virtio"} ]}' | vmadm update 2ab5fd8a-3ac8-63a9-8e11-98e72bea7836
Command failed: cannot create 'zones/2ab5fd8a-3ac8-63a9-8e11-98e72bea7836/disk0': dataset already exists
```

This was the result... afterwords zones/2ab5fd8a-3ac8-63a9-8e11-98e72bea7836/disk0 got destroyed... presumable in the cleanup steps for the failed command.

it looks like it was a recusrive destroy as it took away the snapshots as wel. (I think one had a hold but I am not sure about that)

**Comment by sjorge** [comment]
Just ran into this again when trying to add an extra disk, I did not specify a media for it just a model and size.

**Comment by bahamat** [comment]
Filed internally as [OS-7004](https://smartos.org/bugview/OS-7004).

**Comment by sjorge** [comment]
Probably also related to #788

**Comment by sjorge** [comment]
This got merged
