### ISSUE TITLE
disklist stopped working  on 20180927T004151Z

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#807]
I just noticed disklist no longer lists my SATA disks on one server (iostat still shows the info).
I checked on my other box and it also does not list the disks attached to my LSI SAS2 controlers, ircu2sas still shows them present and the pools are also still happy.

**Comment by daleghent** [comment]
Are you sure that you’re running it as root?

**Comment by sjorge** [comment]
Yes, there are no other users in the global zone I can long into.

~ sjorge

**Comment by sjorge** [comment]
Reboot fixed it on both CNs :/ closing as it works fine after reboot.

**Comment by rzezeski** [comment]
@sjorge This is an intermittent bug that I've hit before as well. A reboot will fix it. @rmustacc knows about the nature of the bug but hasn't been able to successfully reproduce it (IIRC).

**Comment by sjorge** [comment]
Well that rule out a very odd random fluke, shame it’s not reliably reproducible.
