### ISSUE TITLE
joyent_20181026T222825Z panics right after boot

### ISSUE THREAD

**Issue by tyuxar** [joyent/smartos-live#810]
Hi,

Just like as it was reported in https://www.listbox.com/member/archive/184463/2018/10/sort/time_rev/page/1/entry/0:67/20181027094405:5C6F4348-D9EE-11E8-9D2C-8DE5C97BEF1F/ , joyent_20181026T222825Z crashes for me, too, right after boot. The platform is an Intel NUC i5 DC53427HYE.

See the attached screencap about the console.
![smartos 20181026t222825z after boot crash](https://user-images.githubusercontent.com/35227795/47621244-4f796a80-daf5-11e8-895f-f64c36a1b18c.png)

**Comment by tyuxar** [comment]
![20181026t222825z_kmdb](https://user-images.githubusercontent.com/35227795/47621773-ce25d600-dafc-11e8-9a8a-e68aa322625c.png)

Bear with me please, I've never used kmdb before. I booted the NUC from the network with -kd added to the parameters, and just entered a ':c' at the kmdb prompt after the kernel and the boot archive had been loaded. I've attached the result.

Tell me if I can try something else or help you in some other ways.

**Comment by jclulow** [comment]
Hey, that's great so far!  At the `[0]>` prompt, after the panic, can you type `$C` to see the full stack trace?  I think it will probably allow you to page through as it doesn't appear to entirely fit on one screen, and it would help to be able to see the top of the stack.

**Comment by jlevon** [comment]
Interesting: I got the same kobj-era issue on my vmware instance, and presumed it was in-flight changes I had. But maybe not?

**Comment by jlevon** [comment]
Here's the full bootrd_debug=1 output I get:

https://pastebin.com/1q5qjfRa

Will investigate some more...

**Comment by jlevon** [comment]
BTW I was booting from ISO

**Comment by jlevon** [comment]
This doesn't happen booting from the last release ISO for me though, so it might be unrelated after all.

**Comment by jclulow** [comment]
@tyuxar What boot loader are you using when you PXE boot?

**Comment by tyuxar** [comment]
@jclulow I use pxeboot.0 and mboot.c32 from Syslinux (and a simple menu). I can try iPXE, but could not yet compile it in a SmartOS zone (even the GNU binutils linker can't find some elf32-i386 binary script/template/whatever it needs).

I did not forget your request about the stack traces, but unfortunately I haven't yet had time for that.

**Comment by pfmooney** [comment]
See [OS-7332](https://smartos.org/bugview/OS-7332)

**Comment by ChrisWills** [comment]
I'm also hitting this issue. 

@pfmooney could you provide the patch to ipxe which avoids using the memory in 0xc700000 - 0xc7fffff?

**Comment by jclulow** [comment]
@ChrisWills If you grab a build of the `sdcboot` project, it contains the files `boot/ipxe.lkrn` and `boot/undionly.kpxe`.  The former is the iPXE binary we put on USB keys and chainload through grub, the latter is the one we provide over TFTP when hosts are booting using the PXE ROM build in to their system firmware or NIC firmware.

e.g., https://us-east.manta.joyent.com/Joyent_Dev/public/builds/sdcboot/master-20170503T001907Z/sdcboot/sdcboot-master-20170503T001907Z-ga487b30.tgz

**Comment by ChrisWills** [comment]
@jclulow thanks for the reply! 

As it turns out, I was able to figure out the patch by digging around in https://github.com/joyent/ipxe (I didn't realize you guys open sourced your port of ipxe when I sent my previous reply). I couldn't get the joyent ipxe fork to build cleanly on linux so I ported the patch to vanilla ipxe (see https://github.com/ChrisWills/ipxe/commit/f41246cc70d03a2c9cd71bc08c632d455def1d8f)

For those that want to follow along you can do the following:
```
git clone https://github.com/ChrisWills/ipxe/ cwills-ipxe
cd cwills-ipxe/src
make bin/ipxe.pxe
<deploy bin/ipxe.pxe on your tftpserver>
```

**Comment by tyuxar** [comment]
> This is built from [sdcboot](https://github.com/joyent/sdcboot) which includes our [iPXE fork](https://github.com/joyent/ipxe) as a submodule.

I've grabbed and compiled it (w/ a bit tinkering in parserom.pl), using undionly.kpxe from this repo netboot now works properly, even with joyent_20181108T015750Z.

**Comment by jlevon** [comment]
Now OS-7332 is back, we should boot even with bootloaders lacking this change. Closing.
