### ISSUE TITLE
vmadm: lofs mount of a non-existent source path leaves VM in wedged state

### ISSUE THREAD

**Issue by danderson** [joyent/smartos-live#819]
If you try creating an OS VM that has a lofs mount with a source path that doesn't exist in the GZ, `vmadm create` fails but doesn't cleanly unwind the half-created zone. You end up with a zone that vmadm cannot use, but also cannot delete, and you have to go use `zonecfg`, `zfs destroy` and `zoneadm` to clean up the leftover state.

I'm still quite unfamiliar with the codebase, but it feels like there's a combination of a missing validation step for lofs mounts (check that the path exists during validation - although that can be racy, it'll definitely help standalone users at least), and missing unwinding logic to tear down the half-built zone when zonecfg/zoneadm fail due to the invalid spec.

**Comment by mgerdts** [comment]
related: https://smartos.org/bugview/OS-7350

**Comment by bahamas10** [comment]
CR: https://cr.joyent.us/#/c/5594/
Ticket: https://smartos.org/bugview/OS-7350
Commit: https://github.com/joyent/smartos-live/commit/1633dfcadffd609293a38d9aac697db2fa6e7f90

This fix will be available in the 2/28/2019 version of SmartOS.

Feel free to re-open this ticket or create a new ticket if the issue persists, thanks!
