### ISSUE TITLE
"first of 1 error: Command failed: clear zfs-io-priority: No such entry"

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#821]
```
[root@carbon ~]# vmadm get 37519bde-8801-e237-9457-aee035bd0add | json zfs_io_priority
100
[root@carbon ~]# vmadm update 37519bde-8801-e237-9457-aee035bd0add zfs_io_priority=
Successfully updated VM 37519bde-8801-e237-9457-aee035bd0add
[root@carbon ~]# vmadm update 37519bde-8801-e237-9457-aee035bd0add zfs_io_priority=
first of 1 error: Command failed: clear zfs-io-priority: No such entry
```

This is because after a fix for #815 we are now properly remove the property... however calling clear if the propery is already gone results in an error. It's it has no functional impact AFAIK just an error message.

cc @bahamas10

**Comment by bahamas10** [comment]
oof, darn.  I'll take a look at this - thanks for reporting.

**Comment by bahamas10** [comment]
Issue: https://smartos.org/bugview/OS-7588
CR: https://cr.joyent.us/#/c/5597/

I'll update this issue as more as known... for now that CR should fix it.

**Comment by sjorge** [comment]
Any update on this? I don’t think it is fixed yet.

**Comment by jlevon** [comment]
Fixed by above PR
