### ISSUE TITLE
zone stuck in 'provisioning' status

### ISSUE THREAD

**Issue by tuxillo** [joyent/smartos-live#826]
Hi,

I just realised a zone has been stuck in 'provisioning' state for at least 5 days (current uptime). After speaking to LeftWing on #smartos here's the information requested:

    # vmadm list |fgrep provision
    bef9bf02-d239-6c20-9ca1-93a8f20bbbd1  OS    2456     provisioning      sm01-gate1
    # zoneadm list -civ |fgrep bef9
    # vminfo status -jf
    {
      "pid": 2830,
      "uptime": "452161.336435552s (5.23d)",
      "memory": {
        "rss": 49500160,
        "heapTotal": 28908416,
        "heapUsed": 9406000
      },
      "state": "running",
      "status": "working",
      "numVms": 16,
      "curDate": "2019-02-02T00:11:31.770Z",
      "curTime": "452216.610700853",
      "queue": {
        "now": "452216.610930495",
        "paused": false,
        "idle": true,
        "vasync_queue": {
          "concurrency": 1,
          "npending": 0,
          "nqueued": 0,
          "pending": {},
          "queued": []
        }
      },
      "lastRefresh": "251.157794585s (4.18m)",
      "refreshErrors": [],
      "eventsListeners": {
        "19c302c4-6c10-469a-d4f7-a193594dc4e9": {
          "userAgent": "Metadata Agent - VminfodWatcher - sm01/3104 (/usr/vm/sbin/metadata)",
          "createdTime": "61.604646569",
          "createdDate": "2019-01-27T18:36:10.409Z",
          "createdAgo": "452155.006399150s (5.23d)"
    },
        "4ab844e8-48e6-46ad-91e0-af7d796ac0f8": {
          "userAgent": "VM.js events - vmadmd ZoneEvent - sm01/4034 (/usr/vm/sbin/vmadmd)",
          "createdTime": "70.447166571",
          "createdDate": "2019-01-27T18:36:19.251Z",
          "createdAgo": "452146.163879148s (5.23d)"
        },
        "83b88909-b6ed-ef7c-aa61-fea95f90480a": {
          "userAgent": "VM.js unsetTransition (bef9bf02-d239-6c20-9ca1-93a8f20bbbd1) - sm01/4034 (/usr/vm/sbin/vmadmd)",
          "createdTime": "70.548020403",
          "createdDate": "2019-01-27T18:36:19.351Z",
          "createdAgo": "452146.063025316s (5.23d)"
        }
      },
      "refreshLog": [],
      "fswatcher": {
        "message_delays": {
          "1": 1,
          "10": 0.3,
          "100": 0.34,
          "1000": 0.758
        },
        "watching": [
          "/tmp/.sysinfo.json",
          [... list of VM stuff where bef9 doesn't appear ...]
        ],
        "not_yet_watching": [
          [... list of VM stuff where bef9 doesn't appear ...]
        ],
        "pending_actions": {},
        "watcher_pid": 2867,
        "running": true
      }
    }
    # vminfo vm bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
    bad statusCode: 404

I have gcore and vminfo logs on demand to be sent privately.

Restarting vminfod had no effect:

    # vmadm list |fgrep bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
    bef9bf02-d239-6c20-9ca1-93a8f20bbbd1  OS    2456     provisioning      sm01-gate1

Let me know if you need more information.

Regards,
Antonio Huete

**Comment by tuxillo** [comment]
In my infinite wisdom I have thought of "overwriting" it, thus ending up with two:

    # vmadm create -f sm01-gate1.json
    first of 1 error: vminfod watchForEvent timeout exceeded
    # vmadm list |fgrep bef9
    bef9bf02-d239-6c20-9ca1-93a8f20bbbd1  OS    2456     provisioning      sm01-gate1
    bef9bf02-d239-6c20-9ca1-93a8f20bbbd1  OS    2456     provisioning      sm01-gate1
    # vmadm destroy bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
    Failed to delete VM bef9bf02-d239-6c20-9ca1-93a8f20bbbd1: first of 1 error: vminfod watchForChanges timeout exceeded

Restarting vminfod cleared the latest one (I think).

**Comment by bahamas10** [comment]
Hi @tuxillo 

FWIW, to delete these zones unfortunately `vmadm` won't currently do the trick - you can use `zoneadm` and `zonecfg`:

```
zoneadm list -cv
```

Look for the zone in question there - it should be in state "configured".  Then, delete it with:

```
zonecfg -z <uuid> delete -F
```

As for the actual issue, how was the zone created?  Did you run a `vmadm create` command to create it (I'm guessing you did based on your last comment).  If you are able to reproduce this, can you run the following and paste the output?

```
VMADM_DEBUG_LEVEL=debug vmadm create -f foo.json
```

This will output debug level logging which will show exactly what failed during the provision.

Let me know if you need anything else to help track this down.

**Comment by tuxillo** [comment]
@bahamas10 thanks, that did the trick and the zone went away. I created it some time ago I think. It was created with 'vmadm send' if I recall correctly but I don't know what I did wrong that it stayed in that status. There wasn't even a dataset related to it.

**Comment by bahamas10** [comment]
@tuxillo hm, interesting.

I know we have tests around `vmadm send` / `vmadm recv`, but that is certainly an area that has given me issues in the past - I don't think the tests are as all-encompassing as they could be.  With the introduction of vminfod (OS-2647) in September of 2018, there have been issues around timeouts being exceeded, so this isn't necessarily the result of something you did wrong, in fact I'd be willing to bet you did nothing wrong and the codebase surround `vmadm recv` is weak.

Any logs from this action will have most likely been rotated out and removed already (they would be in `/var/log/vm`).  Unfortunately, that would be the only real way to determine why the VM failed to send.

Going forward, if you attempt to send/recv a VM like that, try invoking `vmadm` with the environmental variable set `VMADM_DEBUG_LEVEL=debug`... this will dump a lot of logging to stderr that can be used to figure out exactly what failed and why.

**Comment by tuxillo** [comment]
I think I know what I did to cause the problem but I don't think I can provide all the details.

- When migrating SmartOS from a VM to another, I had a failure sending this particular zone with 'vmadm send'.

- After that, even without removing the failed zone transfer I think (not 100% sure) I use ansible's vmadm module to adjust the zone configuration, see below the ansible yml code:


       - name: Create sm01-gate1 zone
         vmadm:
           brand: joyent
           state: present
           alias: sm01-gate1
           hostname: sm01-gate1.xxx.yyy
           image_uuid: c6a275e4-c730-11e8-8c5f-9b24fe560a8f
           indestructible_zoneroot: yes
           max_physical_memory: 3072
           max_swap: 4096
           quota: 50
           resolvers: [192.168.1.1,8.8.8.8]
           nics:
             - nic_tag: internal
               ip: dhcp
               primary: true

- Then I removed the bad definition with zonecfg as specified in the previous comment and the zone was gone. But after running again the ansible playbook, the zone status was left as 'configured'. I tried 'vmadm install' which failed with a timeout, then 'vmadm stop' and it was sent to stopped status, then start and it's set as running now. I can't do anything with it right now:

       # vmadm list |grep gate
       bef9bf02-d239-6c20-9ca1-93a8f20bbbd1  OS    2456     running           sm01-gate1
       # vmadm destroy bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
       Failed to delete VM bef9bf02-d239-6c20-9ca1-93a8f20bbbd1: VM bef9bf02-d239-6c20-9ca1-93a8f20bbbd1 not found
       # vmadm info bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
       Unable to get VM info for VM bef9bf02-d239-6c20-9ca1-93a8f20bbbd1: bad statusCode: 404
       # vmadm stop bef9bf02-d239-6c20-9ca1-93a8f20bbbd1
       VM bef9bf02-d239-6c20-9ca1-93a8f20bbbd1 not found
       # zoneadm list -cv |grep bef9
       # zonecfg -z bef9bf02-d239-6c20-9ca1-93a8f20bbbd1 delete -F
       bef9bf02-d239-6c20-9ca1-93a8f20bbbd1: No such zone configured
       bef9bf02-d239-6c20-9ca1-93a8f20bbbd1: No such zone configured

Sorry for the mess :)

**Comment by tuxillo** [comment]
This can be probably closed
