### ISSUE TITLE
metadata daemon not detecting VM status changes

### ISSUE THREAD

**Issue by YanChii** [joyent/smartos-live#828]
Hi,

It seems that there's a regression in metadata service on all new SmartOS platforms this year (and also before). It is not picking up any notifications from vminfod about (H)VM starts or reboots. It is very inconvenient because it hits hard all buggy `cloud-init` installations.

How to replicate:
Just tail `/var/svc/log/system-smartdc-metadata:default.log` and start/reboot any VM (tested with KVM). It will detect the VM only during periodic 1-minute checks.

Impact:
VM is up to 1 minute without metadata replies.

Fix:
My fix for this is to change the line here
https://github.com/joyent/smartos-live/blob/release-20190131/src/vm/lib/metadata/agent.js#L499
to this:
```
state = state[0].newValue;
```

Jan

**Comment by bahamas10** [comment]
Hi,

Thanks for reporting this - this is definitely a bug and an oversight on my part with OS-2647 (introducing vminfod).

I'll create an internal ticket to track this, and will come up with a fix and test it based on your stated change.  I'll update this issue with details.

**Comment by bahamas10** [comment]
Ticket: http://smartos.org/bugview/OS-7581
CR: https://cr.joyent.us/#/c/5586/
Commit: https://github.com/joyent/smartos-live/commit/10f94f74af8aab34527fae645bbf25b962e10f7f

This will be fixed in the 2/28/2018 release of SmartOS.

Thanks! :+1:

**Comment by sjorge** [comment]
Would this also make vmadmd correctly open the VNC listening socket on HVM stop/start? Or is the service restart still needed for those?

**Comment by bahamas10** [comment]
@sjorge I don't know if these 2 things are related... I want to say they are *not* related.  Is there a ticket for what you're talking about wrt vmadmd?

**Comment by sjorge** [comment]
Yep! https://github.com/joyent/smartos-live/issues/816

Been broken since vminfod landen, as vmadmd is no longer opening/closing the ports in HVM start/stop/create/destroy or vnc_port parameter update.

Only way is to restart vmadmd, which then queries all info from vminfod (I think, last I looked at the logs I saw a new client connect to vminfod and suck up all the current info)

**Comment by bahamas10** [comment]
@sjorge Ah thanks! I remember now.  I was shifted off that as different issues were prioritized, but I will circle back and try to figure out the latest with that.  Last I remember it was a fairly complex issue.
