### ISSUE TITLE
SmartOS crash on boot on Xeon Phi 7250

### ISSUE THREAD

**Issue by bweather** [joyent/smartos-live#834]
Booting SmartOS on [Supermicro](https://www.supermicro.com/products/system/tower/5038/SYS-5038K-I.cfm) with a [Xeon Phi 7250](https://ark.intel.com/content/www/us/en/ark/products/94035/intel-xeon-phi-processor-7250-16gb-1-40-ghz-68-core.html) results in a crash.

![iKVM_capture](https://user-images.githubusercontent.com/9702913/55369825-02872f00-54ad-11e9-92bd-1fc73e8e53a5.jpg)
![iKVM_capture (1)](https://user-images.githubusercontent.com/9702913/55369828-061ab600-54ad-11e9-9255-b4f382445ce0.jpg)

**Comment by jlevon** [comment]
Thanks for the report.

To get past this particular issue can you try adding to the end of the kernel line in grub menu:

```-kd```

as boot option. Then, when KMDB comes up, type:

```
ht_exclusion/z 0
:c 
```

But I suspect this is the first time we've been booting on a Phi like this. I think we're seeing 4 threads per core here. As the system doesn't support hardware virtualization, you shouldn't need ht_exclusion.

**Comment by bweather** [comment]
Hello John,
Thanks for the tip. I was able to boot.

<img width="369" alt="prtdiag" src="https://user-images.githubusercontent.com/9702913/55449024-ddfb8780-557e-11e9-950b-3ec4a42792e1.png">

However, SmartOS only enables 256 cores instead of 272.
Using `prtconf` I can see that all cores are visible to the system but exactly 16 do not have a driver attached.
<img width="370" alt="prtconf" src="https://user-images.githubusercontent.com/9702913/55449017-d805a680-557e-11e9-986a-251f88574cbc.png">

Is there a way to get around that as I need all my cores working?

Thank you

**Comment by jlevon** [comment]
No, there is no workaround. It would need some non-trivial OS work. But I must admit it's hard to imagine what you're planning to run where an extra 6% of CPUs are critical?

**Comment by bweather** [comment]
>But I must admit it's hard to imagine what you're planning to run where an extra 6% of CPUs are critical?

I am not really planning anymore as my workload is already underway on Linux.
The more interesting question is why SmartOS can only use a maximum of 256 cores while Linux and Windows do not have this limitation. I really like to use SmartOS anywhere I can and I don't think that should exclude HPC workloads.

Should I create another issue for that?

**Comment by rmustacc** [comment]
On 4/3/19 16:28 , Boris Hristov wrote:
>> But I must admit it's hard to imagine what you're planning to run where an extra 6% of CPUs are critical?
> 
> I am not really planning anymore as my workload is already underway on Linux.
> The more interesting question is why SmartOS can only use a maximum of 256 cores while Linux and Windows do not have this limitation. I really like to use SmartOS anywhere I can and I don't think that should exclude HPC workloads.
> 
> Should I create another issue for that?
> 

The x86 kernel has a maximum number of CPUs that it supports which
influences various structure sizes which are, for historical reasons,
statically sized. That value is currently set to 256 on x86 (the `NCPU`
macro in uts/i86pc/sys/machparam.h). That's why we hit this. It would be
nice to change that and get away from the static sizing, but it's not
something that we're currently focusing on.

**Comment by bweather** [comment]
Thank you, closing as invalid.
