### ISSUE TITLE
imgadm import out of space in global zone Stderr from zfs receive: cannot receive new filesystem stream: out of space - when it isn't.

### ISSUE THREAD

**Issue by ParkyCode** [joyent/smartos-live#838]
Hi There,
I’m struggling with a couple of things. 1) is that your version 4.1 isn’t recognised in “https://images.danubecloud.org/images” as I think its missing some quotes around it. This also means your (step 2) statement about doesn’t work: curl -s https://images.danubecloud.org/images/ | json -c ‘this.name == “esdc-mgmt-ce” && this.version >= “2.4.0”‘

I worked this out but when I try and import the image I get this error:
zones/91a06646-fbd0-4960-96bf-3b73f82e2743 [========================> ] 25% 198.38MB 2.98MB/s 3m16s Stderr from zfs receive: cannot receive new filesystem stream: out of space

This is a new install of smartos build version 20190605T231205Z on a VirtualBox VM with 16Gb of dynamically added vdi storage.

root@SmartOSHead /zones]# zpool list
NAME SIZE ALLOC FREE CKPOINT EXPANDSZ FRAG CAP DEDUP HEALTH ALTROOT
zones 15.5G 2.12G 13.4G – – 0% 13% 1.00x ONLINE –

[root@SmartOSHead /zones]# zfs list
NAME USED AVAIL REFER MOUNTPOINT
zones 14.4G 593M 530K /zones
zones/archive 24K 593M 24K /zones/archive
zones/config 32.5K 593M 32.5K legacy
zones/cores 340M 593M 24K none
zones/cores/global 340M 593M 340M /zones/global/cores
zones/dump 1.00G 593M 1.00G –
zones/opt 24K 593M 24K legacy
zones/swap 12.3G 12.9G 12K –
zones/usbkey 32.5K 593M 32.5K legacy
zones/var 787M 593M 787M legacy

[root@SmartOSHead /zones/global]# df -h .
Filesystem Size Used Available Capacity Mounted on
zones 15G 530K 8.88M 6% /zones

This doesn't as if its reporting the sizes correctly.  I also add autoexpand and still the same error.

Any ideas?

regards
Adrian

**Comment by mgerdts** [comment]
The amount of space available is shown by this first line from zfs list:

NAME USED AVAIL REFER MOUNTPOINT
zones 14.4G 593M 530K /zones

It looks to me as though you have a 15 GB pool (14.4G + 593M) and only 593
MB is available.  The "available" space is the space that's not already
used by data, metadata, snapshots, or reservations.  In your case, it looks
like zones/swap is rather large for the amount of disk space you have
available.

Take a look at the output of this command:

zfs get all zones/swap | egrep 'NAME|used|size'

You will see that it has a refreservation that is somewhere around 13G.  To
fix this, shrink your swap space.  For instance, the following will shrink
it to 2 GB (assuming I made no typos).

swap -d /dev/zvol/dsk/zones/swap
zfs set volsize=2g zones/swap
zfs set refreservation=auto zones/swap
swap -a /dev/zvol/dsk/zones/swap

HTH,
Mike

**Comment by ParkyCode** [comment]
Many thanks Mike, that did the trick
