### ISSUE TITLE
configure should import configure-build if exists

### ISSUE THREAD

**Issue by atcorner** [joyent/smartos-live#839]
There is a bug in configure script regarding sourcing of `configure-build` file.
Function `source_vars` is responsible for sourcing `configure-build` file, but it's flawed, `$file` variable isn't defined anywhere.

```
function source_vars
{
       if [[ -f "configure-build" ]]; then
               source "$file" || fatal "failed to source configure-build"
       fi
}
```

I have a [fix](https://github.com/atcorner/smartos-live/commit/afa00458cb866c3f2599b698dab1f69bb237a544) in my fork of smartos-live and can push it to cr.joyent.us for review if it's acceptable.

I did change a logic of using `configure-build` in a way that `default.configure-build` file  is **always** sourced and if `configure-build` file exists  it is sourced after `default.configure-build` file. That way we don't need whole copy of defaults file in order to make a change on just one variable.  (e.g I only need to override OVERLAYS variable)

regards
Ante

**Comment by jlevon** [comment]
Hi Ante, thanks, and please do put it up on cr.joyent.us.

On a related note, what do you do with OVERLAYS? I am looking at ripping out all the overlay logic, but wouldn't want to make things significantly harder for you. Can you email me about this at john.levon@joyent.com ?

**Comment by jlevon** [comment]
Fixed, thanks: https://github.com/joyent/smartos-live/commit/e6609fd70d1b8fa90aa4d22a05ec30abf6b28add
