### ISSUE TITLE
networking between zones causes total network outages

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#857]
Host A (joyent_20190829T000927Z) (uptime 41 days):
zone AA (most probably multiarch-lts 15.4.1, vmadm send eats information): [screen] mutt
  net0: X/24, mapped to gz admin interface vlan Z
zone AB (most probably base 14.2.0, vmadm send eats information): dovecot
  net0: Y/24, mapped to gz admin interface vlan Z
both zones vmadm send'd from another host

Reading a mail on zone AA (hit enter on an item on muttt in screen) bigger than ~40KB causes zone AA to lose all network connectivity, everywhere (repeatable now with any message bigger than ~40KB; smaller emails are ok). arp -an says there is no mapping for default gw nor dns (both on the same subnet) after a while. zone AA will go on a rampage sending arp requests for default gw and dns on the lan (observed on host B)
```
Fetching message... 40K/89K (44%)packet_write_wait: Connection to AA port 22: Broken pipe
```
Reading the mail with Apple Mail imaps from another network C is not a problem for zone AB before/during/after.

Zone AB is still functioning properly the whole time. GZ is still functioning properly. Zone AA; zlogin AA: ifconfig down/up doesn't fix the problem. vmadm reboot AA fixes the problem.

Happened 3-4 times since the upgrade to the plattform image, randomly (worked on 2008*something* without a problem), now repetable on every email (about 6 times in the past 24h).

Rebooting AA doesn't affect the results. Rebooting AB doesn't affect the result.

When the 'Fetching...' happens,
  waiting causes IRC on the interface to Ping timeout
  except when doing vmadm reboot within (<tcp-timeout?) and the reason is EOF Fom client or Connection reset be peer (courtesy of android andchat)

The Effect can be observed as arp -an losing the default gw and ns mac address (empty fields), but apparenntly after (arp?) timeout.

Looking at snoop at AA and separate hardware (B) in the same vlan (in hardware B, the vlan is the native vlan), it looks like... packets go missing. Not always the same direction but mostly towards AA, and when they arrive they're not acted upon (no arp updates).

I have some snoop logs of AA and B doing ping and snoop, but they don't really make much sense (arp; most of the time AA doesn't receive anything, but randomly it does but there is no effect)

I have a production environment to repeat the problem at the moment; I'll be migrating some or all zones to host B depending on what fixes the problem for now within two days or so.

I can't provide dumps (production data) but I can fail the system couple of times and go peeking for details until I move the zone(s).

For more info, jesse_@#smartos

**Comment by sjorge** [comment]
Maybe related to https://cr.joyent.us/#/c/6990/, there is all sort of fallout, mostly to do with local traffic now being different from external traffic. e.g. most VPNs are broken among other issues.

**Comment by jessegit** [comment]
I upgraded to a version that fixed bug mentioned above and I haven't seen the problem repeat since.
