### ISSUE TITLE
lldp/server does not start on a PI build yesterday

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#873]
While testing a PI that has joyent/illumos-joyent#228 to see if #814 is resoleved I noticed the `lldp/server` ends up in error.

I tried a few restarts with no success, reverting to my old PI which was from 2 days ago.... and everything is fine again.

The following error is in the log

```
/var/run/lldpd.sock:19
[Error] Unable to bind to the unix domain socket for client registration!
[Error] Unable to listen to the unix domain socket for client registration!
Would stuff interface #: 1
[ERROR] in config file: invalid location_data_format '0'
Would stuff interface #: 2
[ERROR] in config file: invalid location_data_format '0'
```

I cannot find a log file it is trying to read either ?

**Comment by sjorge** [comment]
New PI from today does not have the issue... weird... but closing.

**Comment by rzezeski** [comment]
This happens from time to time and has been a thing for a while. No one has had time to root cause it. The changes I made in illumos-joyent#228 have nothing to do with LLDP.
