### ISSUE TITLE
Switch to newer UEFI firmware like OmniOS has

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#889]
```
[16:04:35] sjorge :: andyf what are the UEFI bhyve changes in the latest release?
[11:41:24] @andyf ::  sjorge - yes, and the OmniOS ones :D
[11:41:46] @andyf ::  The firmware should work fine on SmartOS too, but I haven't tested
[22:34:44] @andyf ::  jorge - now that I am not trying to type on my 'phone
[22:35:18] @andyf :: sjorge - the new firmware is based on https://github.com/freebsd/uefi-edk2/tree/bhyve/edk2-stable201903
```

I will ask for the binary and give it a test spin this week.

**Comment by citrus-it** [comment]
The firmware binary from OmniOS is at https://downloads.omnios.org/misc/BHYVE_UEFI_2.70.fd
This is built from https://github.com/omniosorg/uefi-edk2/tree/edk2-stable201903
based on https://github.com/freebsd/uefi-edk2/tree/bhyve/edk2-stable201903

As well as being much newer than the existing firmware (2019 versus 2014) it is also built with gcc9.
(The CSM variant does not work at all when built with gcc7/8/9 and doesn't completely work even then - we are not planning to ship a CSM variant of this firmware in OmniOS - anyone needing CSM will have to continue with the old binary)

**Comment by sjorge** [comment]
I can test the following:
- [ ] windows 10
- [ ] opnsense (freebsd 11 based)
- [ ] omnios (not sure, bloody a few months old)

I will update this list once done

**Comment by sjorge** [comment]
```
root@inflaton:~#  tr '\0' '\n' < /system/boot/environment | grep -i efi
efi-version=2.70
```

OmniOS works fine, so it is just windows that is not happy!
I did have to reinstall as my bloody install was apparently broken, sorry for the wrong info the first time round.

**Comment by sjorge** [comment]
For completelyness, IIRC this the change that causes the fbuf error
https://github.com/freebsd/uefi-edk2/pull/9/commits/7e4d61570ba0526e6c59e374dd1906fa60592e18

**Comment by citrus-it** [comment]
@sjorge can you try the new binary at https://downloads.omnios.org/misc/BHYVE_RELEASE-2.70.fd please?

**Comment by sjorge** [comment]
I'll give it a go later this weekend, what changed?

**Comment by sjorge** [comment]
Ah looks like you just reverted the one change to get nvme to work: https://github.com/omniosorg/uefi-edk2/commit/37bd0194688c4ce47a07fe8bccb29ad3546953c7

**Comment by sjorge** [comment]
@citrus-it see also https://reviews.freebsd.org/D24066

**Comment by sjorge** [comment]
Well windows 10 boots fine with the one patch reversed:
![](https://imgur.com/yCLnUfr.png)

Although I can't find the 2.70 verison info on windows 🤷‍♂

**Comment by sjorge** [comment]
With https://github.com/omniosorg/illumos-omnios/pull/682 applied the original firmware (including the NVME change) also boots!

```
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json bootrom
/var/BHYVE_UEFI_2.70.fd
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json vnc_port
5901
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json pci_devices
[
  {
    "path": "/devices/pci@5e,0/pci8086,2030@0/pci8086,37c0@0/pci8086,37c5@3/pci15d9,37d2@0,1",
    "model": "passthru",
    "pci_slot": "0:8:0"
  }
]
```

However VNC is broken!

![](https://imgur.com/mciJrKM.png)

**Comment by sjorge** [comment]
```
@andyf
we're going to provide both firmwares in omnios r151034, I just need to decide which is the default
[11:53:19]
I use emulated nvme ramdisks as extra scratch space and for testing nvme stuff
[11:53:34]
sjorge
cleaner interface? (as NVMe seems rather well designed compared to ahci)
[11:53:34]
andyf, what about an 'uefi-auto' mode where you use the NVMe enabled one unless a passthru device is present?
[11:54:02]
@andyf
I think we'd just leave 2.4 as the default until 2.7 has the problems fixes
[11:54:27]
I think we'd just leave 2.4 as the default until 2.7 has the problems fixed
[11:54:28]
sjorge
Also I'd like to see how the situation is once papertig1rs has synced all of the pci_emul and stuff that got skipped with the last sync.
[11:54:33]
@andyf
but people can switch if they want to
[11:54:33]
sjorge
andyf sounds fair
[11:54:41]
NVMe works on 2.4 too right?
[11:54:50]
@andyf
yes
[11:55:17]
sjorge
Yeah sticking with 2.4 seems like a good idea
[11:56:35]
I'll update the smartos ticket too
```

Looks like 2.4 pretty much works in all cases, vnc (with and without the new upstream diff), nvme, and passthru while 2.7 has stuff broken.

I'll close this for now as sticking with 2.4 seems like a stable option ATM.
