### ISSUE TITLE
running 'gmake clean' breaks build

### ISSUE THREAD

**Issue by sjorge** [joyent/smartos-live#905]
I build my own PIs and since about (1-2 weeks) ago I cannot do:
```gmake clean ; gmake world```

It will bread on:
```
rm -f 0-*-stamp 1-*-stamp
/root/smartos-live/tools/build_strap make \
    -a /root/smartos-live/illumos-adjunct.20130131.tgz -d /root/smartos-live/proto.strap -j 128 \

gmake: *** [Makefile:364: 0-strap-stamp] Error 2
```

The only way forward seems to be to delete smartos-live, git clone smartos-live, ./configure, gmake world live

**Comment by sjorge** [comment]
I also tried a `gmake clobber` this has the same effect

**Comment by sjorge** [comment]
I think this commit broke it:
```https://github.com/joyent/smartos-live/commit/d241d249d8849e4f0e31a72da405161c6a40e3b6```

But was unable to revert it to verify

**Comment by sjorge** [comment]
```
# not iterest in gmake clean output, just to show it creates proto.strap as a dir
[root@proton ~/smartos-live]# ls -ld proto.strap
drwxr-xr-x 2 root root 2 Feb 19 12:41 proto.strap
[root@proton ~/smartos-live]# rmdir proto.strap
[root@proton ~/smartos-live]# gmake clean 2> /dev/null >/dev/null
[root@proton ~/smartos-live]# ls -ld proto.strap
drwxr-xr-x 2 root root 2 Feb 19 12:53 proto.strap
```

So from IRC chat between me and John... `gmake clean` creates proto.strap as a directory.
That means that gmake world will fail as it calls an rm.

Doing `gmake clean; rmdir proto.strap; gmake world` seems to work!

(Note: I had a odd self referencing symlink in /opt/SmartOS/build-cache/HASH/SAMEHASH, after removing the symlink the above (with rmdir) seems to work)

**Comment by jlevon** [comment]
Thanks, moving over to OS-8114
