### ISSUE TITLE
zonecfg exports are not importable

### ISSUE THREAD

**Issue by dtrv** [joyent/smartos-live#912]
As described on [Managing Instances](https://wiki.smartos.org/managing-instances-with-vmamd/#manual-migration), `zonecfg` should be used to export and import zone configs. But
`zonecfg -z uuid export > uuid.zcfg` lead to `uuid.zcfg` that is NOT importable by `zonecfg -z uuid -f uuid.zcfg`. Example to reproduce below.

From `/etc/zones/uuid.xml`:
```
...
<attr name="qemu-extra-opts" type="string" value="LXNtcCB0aHJlYWRzPTQ="/>
<attr name="alias" type="string" value="d2luZG93cw=="/>
...
```
(first line is `qemu-extra-opts` `-smp threads=4` and the second line is `alias` `windows`)

leads to the following lines in `uuid.zcfg`:
```
...
add attr
set name=qemu-extra-opts
set type=string
set value=LXNtcCB0aHJlYWRzPTQ=
end
add attr
set name=alias
set type=string
set value=d2luZG93cw==
end
...
```

Both fail with (uuid and line number replaced) ...
```
syntax error on line <no> at '='
<USAGE message>
resource specification incomplete
Zone <uuid> failed to verify
<uuid>: Insufficient specification
Configuration not saved.
```
... because of missing quotes. Quoting the values fixes this problem and `uuid.zcfg` can be imported.
```
...
set value="LXNtcCB0aHJlYWRzPTQ="
...
set value="d2luZG93cw=="
...
```

I suggest to quote all base64 encoded values.

**Comment by bahamat** [comment]
This was fixed in joyent/illumos-joyent@c8236ea
