### ISSUE TITLE
Boot hangs on Supermicro 5019A-FTN4

### ISSUE THREAD

**Issue by erwinlem** [joyent/smartos-live#928]
I made an USB image with SmartOS 20200422T203030Z, enabled legacy mode in the bios. After turning on verbose mode it hangs at the following line :

<img width="826" alt="image" src="https://user-images.githubusercontent.com/6923105/80381460-419ad600-88a1-11ea-9e10-88dbd5f95c5f.png">

I have updated the bios & firmware to the latest version, Hipster hangs at the same point. I got a [5018A-FTN4](https://www.supermicro.com/en/products/system/1U/5018/SYS-5018A-FTN4.cfm) which boots fine. This machine ran freebsd for a year so I don't think anything is wrong with the hardware. I tried disabling as many features as possible in the bios but that made no difference. Tried running the version I use on the 5018A but that hangs at the same point.

Component | Description
------------ | -------------
Machine | [5019A-FTN4](https://www.supermicro.com/en/products/system/1U/5019/SYS-5019A-FTN4.cfm)
Motherboard | [A2SDi-8C-HLN4F](https://www.supermicro.com/en/products/motherboard/A2SDi-8C-HLN4F)
Ram | 2x 16GB
Disks | 2x 700GB ssd and 12TB spinning which are zfs disks from the freebsd install
Network | ipmi & 4 network interfaces are connected to a MikroTik switch.

Is there any step I can take to see where it is hanging? Or does anybody else had the same problem?

**Comment by jasonbking** [comment]
Can you load kmdb from the option menu at boot and try pressing F1-A and see if that puts you into kmdb? What might be useful is running `::cpustack -c XX` for each CPU on the system (XX being the cpu number starting at 0). That might give us a hint where things are hanging.

Also, if you have the IPMI port configured, you can enable serial console redirection in the BIOS, and then select 'ttyb' for the console in the loader (I think it's also under the options menu), then use ipmitool to connect to the console via a terminal session (this can be nicer for gathering output since you don't need screenshots).

**Comment by jasonbking** [comment]
Also, did any previous versions boot without issue?

**Comment by erwinlem** [comment]
Thank you for the suggestions. I'm a little closer. Apparently if SoL exist (even if disabled) the output still goes to the serial console.  As discussed [here](https://github.com/joyent/smartos-live/issues/290#issuecomment-136217278). At the serial console I get a login prompt. 

I will close this issue since it boots fine. Maybe it's a good idea to document this behaviour in [the installer documentation](https://wiki.smartos.org/install/). It was quite unexpected.

**Comment by jasonbking** [comment]
There were some issues with the boot loader -- so that release is being respun (hopefully will be available today or tomorrow) -- that might be why you're only seeing a login prompt there -- it should normally have one on both locations.

**Comment by jlevon** [comment]
FWIW https://wiki.smartos.org/debugging/

**Comment by jlevon** [comment]
Can you open a bug against github.com/joyent/smartos-docs? I agree we should have better details console configuration regardless of this.

**Comment by jasonbking** [comment]
I filed https://github.com/joyent/smartos-docs/issues/32

**Comment by andy-js** [comment]
I'm seeing the same behaviour on an Intel S2600WFT configured to boot in UEFI mode.  It seems like a bug rather than something that needs to be documented.
