### ISSUE TITLE
UniFi video fails to launch on Ubuntu 16.04 LX zone

### ISSUE THREAD

**Issue by ismell** [joyent/smartos-live#955]
I'm setting up [UniFi Video](https://www.ui.com/download/unifi-video/) on an ubuntu 16.04 zone. It's failing on this line

```
# /native/usr/bin/truss /usr/bin/jsvc -cwd /usr/lib/unifi-video -user unifi-video -home /usr/lib/jvm/java-1.8.0-openjdk-amd64 -cp /usr/share/java/commons-daemon.jar:/usr/lib/unifi-video/lib/airvision.jar -pidfile /var/run/unifi-video/unifi-video.pid -procname unifi-video -Dav.tempdir=/var/cache/unifi-video -Djava.security.egd=file:/dev/./urandom -Xmx491M -Xss512K -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=1024M -Djava.library.path=/usr/lib/unifi-video/lib -Djava.awt.headless=true -Djavax.net.ssl.trustStore=/usr/lib/unifi-video/data/ufv-truststore -Dfile.encoding=UTF-8 com.ubnt.airvision.Main -nodetach -debug -verbose -outfile /tmp/unifi.out -errfile /tmp/unifi.err start
```

I can't seem to find any stderr or stdout logs. I have attached a `truss` trace of the process.

SmartOS (build: 20200826T232925Z)

[truss.log](https://github.com/joyent/smartos-live/files/5214513/truss.log)

**Comment by liv3010m** [comment]
Hi ismell,
I'm currently running NVR v. 3.10.13 with openjdk-8 v. 8u252-b09-1~deb9u1 on a debian 9.13 LX zone without any problems so far.
Did you ever got it running or it's the first time you try it? Did you edit the /usr/sbin/unifi-video file?

**Comment by ismell** [comment]
Debian works. Thanks!
