### ISSUE TITLE
OpenBSD BHYVE VM does not boot in SmartOS 20210311T001742Z and 20210325T002528Z anymore

### ISSUE THREAD

**Issue by janv37** [joyent/smartos-live#983]
Hello,
I'd like to report a possible regression in SmartOS' BHYVE in 20210311T001742Z and 20210325T002528Z platform images - OpenBSD VM does not boot anymore with "**Failed to emulate instruction sequence** "

The Hardware is HP Microserver N36L with 4x10T drives in ZRAID10 and 16G non-ECC RAM and dualcore CPU AMD Athlon(tm) II Neo N36L.

I've tested various releases using method of halving the interval starting with known good of 20210114T163038Z and having known not working 20210311T001742Z. I've also tested latest 20210325T002528Z. I suppose the not tested releases work. 

I've attached platform.log from last two not working releases and also prtdiag and prtconf.

If this is somehow CPU-feature-related, at some point I ran physical OpenBSD on the same BOX before ( https://dmesgd.nycbug.org/index.cgi?do=view&id=3050 ) Only HDDs and RAM modules have been upgraded.

The box is co-located, runs personal production, so I'm available for further testing and/or debugging.

Thank you,
JV

## RELEASES BREAKDOWN
```
20210325T002528Z BHYV DOES NOT WORK
20210311T001742Z BHYV DOES NOT WORK
20210226T213821Z BHYV WORKS
20210225T124034Z not tested
20210224T232633Z BHYV WORKS
20210211T163919Z not tested
20210211T055122Z not tested
20210128T022709Z not tested
20210114T163038Z BHYV WORKS
```

## attachments
[platform-joyent_20210311T001742Z.log](https://github.com/joyent/smartos-live/files/6245705/platform-joyent_20210311T001742Z.log)
[platform-joyent_20210325T002528Z.log](https://github.com/joyent/smartos-live/files/6245706/platform-joyent_20210325T002528Z.log)
[prtconf.txt](https://github.com/joyent/smartos-live/files/6245707/prtconf.txt)
[prtdiag.txt](https://github.com/joyent/smartos-live/files/6245708/prtdiag.txt)

**Comment by janv37** [comment]
fixed typo 16M->16G in description

**Comment by jperkin** [comment]
This is a known issue, logged as https://www.illumos.org/issues/13686

**Comment by janv37** [comment]
Missed that report. Thank you Jonathan.

**Comment by janv37** [comment]
Fix landed in 20210923T003059Z, all works as expected now on my HP N36L Microserver. Big thanks to everyone who made this possible! -> Closing the issue.
